### ISSUE TITLE
Auto placement

### ISSUE THREAD

**Issue by FezVrasta** [FezVrasta/popper.js#1]
Improve the `placement` to support an `auto` mode which will calculate the available space on the 4 directions and will then put the popper on the direction with more space.

**Comment by rosskevin** [comment]
`auto` with a preference or ordered array of preferences i.e. `['right', 'bottom', 'left', 'top']` is what I would want to see.

**Comment by FezVrasta** [comment]
@rosskevin I'm going to work on this issue, may you elaborate your idea? What would be the difference between yours, and just the current array of order preferences we have?

**Comment by FezVrasta** [comment]
This PR (#87) has been closed since it was based on outdated code. The issue is still in my to do list if nobody else wants to adopt it.

**Comment by FezVrasta** [comment]
Addressed.
