### ISSUE TITLE
Cleaning references. popper.destroy (); should call: window.cancelAnimationFrame ()

### ISSUE THREAD

**Issue by PawelGIX** [FezVrasta/popper.js#101]
Popper latest stable
### CodePen demo

https://codepen.io/PawelGIX/pen/VmKxoq
`
popper.onUpdate(data => {   
  console.log('update')
});
`
Runs after poper.destroy() call.

### Steps to reproduce the problem

1.  Open console and run https://codepen.io/PawelGIX/pen/VmKxoq
2.  There should be no  "update" in console after "destroy".

**Comment by FezVrasta** [comment]
fixed
