### ISSUE TITLE
Popper placed outside of boundary with contentType = 'node'

### ISSUE THREAD

**Issue by Narretz** [FezVrasta/popper.js#102]
Hi, first of all I have to say that this is a great library!

### Steps to reproduce the problem

http://codepen.io/anon/pen/WoRKoO

1.  Create a popper that uses an element that is *not* part of the document, via `content` and `contentType` parameters, and has a reference element that is close to the boundary (viewPort) edge

### What is the expected behavior?

The popper is not placed outside the (boundary) viewport.

### What went wrong?

The popper is placed outside the (boundary) viewport.

### Any other comments?

The same thing does not happen when I use the same element, but append it to the body prior to creating the popper. I'm not sure if this is expected behavior, but if it is, then this should be clarified in the docs.

**Comment by FezVrasta** [comment]
Hi. thanks for the report.

I'm sorry but this feature has been deprecated and removed from the v1 version of Popper so I'm not going to maintain or fix it.
I'm trying to focus all my free time to release v1.

A PR to fix it in v0 is welcome tho.

I hope you understand the decision.

**Comment by Narretz** [comment]
Thanks for the response, but could you please be more specific. 
Which feature are you talking about exactly? I've onöy used the options that were in the docs so if anything is deprecated it should be in the docs or removed from the docs. I would also appreciate if you could tell me how this would be solved in 1.x

**Comment by FezVrasta** [comment]
The feature to tell Popper to attach/create the popper element has been removed.

The docs are not updated because these changes will be effective only once v1 will be released.

In v1 there will be a separated library meant to replace the "create popper" features.
