### ISSUE TITLE
V1 docs are quite out of date.

### ISSUE THREAD

**Issue by lukebatchelor** [FezVrasta/popper.js#106]
I'll preface this with, thank you so much for this library! Super awesome and SO much better than the alternatives.

I know you're already aware of this and are super busy at the moment, but just raising this for awareness.

We've been relying on the v1 dev branch for a long time now hoping for the v1 release as thats what had all the fixes we required. It's just super painful trying to dev at the moment when none of the docs match up and we have to go to the src to check how things work.

Things like: (it looks like) the boundariesElement API has changed, the offset API is commented in `modifiers/offset.js` but not in the docs anywhere, the flipVariation api is not documented anywhere, etc. 

It's just been a lot of paper cuts for us trying to use this.

Thanks again!

**Comment by FezVrasta** [comment]
Hi, there is a command to generate an updated documentation. It should be `grunt docs` but please double check in the Gruntfile for confirmation.

If you want you can send a PR with the updated documentation. It would be very helpful.

Thanks!

**Comment by lukebatchelor** [comment]
Oh! It's possible i wasn't generating them properly then!

I was cd'ing into docs and running `jekyll serve`

Definitely looking at pushing some docs for the things we've found. Cheers!

**Comment by lukebatchelor** [comment]
So, having a look at this, the docs for the offset modifier /were/ in the docs, apologies. There were two copies, one as the options to  the new popper Instance and one as the Modifiers object. The modifiers one is correct.

We could easily copy and paste the offsets docs from the offset modifier but that doesnt seems scalable, keeping two sets of docs up to date per modifier. 

But perhaps there wont be ~too~ many changes and this is acceptable.

Just raising this here in case you have any ideas. Maybe just copying to main bits across (the API shape, type and default value) and linking the the relevant Modifer docs?

**Comment by FezVrasta** [comment]
I have updated some docs, generated new markdown files that are now stored in `/doc` folder.
Added the docs links in the README and updated the README as well with new informations.
I also updated CONTRIBUTING.md following your indications from PR #110.

Is it enough to close this issue? If not, please reply here and I'll reopen it.
