### ISSUE TITLE
How to change offset

### ISSUE THREAD

**Issue by klemensz** [FezVrasta/popper.js#107]
Hi,
I might not be seeing the obvious, but how can I change the offset of a Popper instance so that it moves up "at runtime"? Is this possible? I tried this:

```
      var fixToTop = function(data) {
        data.popper.offsets.top = 50;
        return data;
      }
      popper.runModifiers({}, [fixToTop], {});
```
But it will throw an error because data.popper is undefined and it's not clear to me what the first parameter (data) should be? Sorry if this is not really an issue but rather a question. Maybe it could help making the documentation a bit clearer.
Thanks!

**Comment by lukebatchelor** [comment]
You'll need to use `data.offsets.popper.top`

See #95

👍

**Comment by lukebatchelor** [comment]
Raised #108 for this.

**Comment by klemensz** [comment]
Thanks a lot, now it doesn't throw an error any more ;) but doesn't actually move the popper. Any pointers to how moving (changing the offset so that it moves 30px up for example) can be achieved?

**Comment by lukebatchelor** [comment]
You're creating a custom modifier there, you need to just use the default offset modifier

```
const popper = new Popper(targetNode, popperContentNode, {
  placement: 'top right',
  modifiers: {
    offset: {
      enabled: true,
      offset: 10
    }
  },
});
```

**Comment by klemensz** [comment]
That will give me a `TypeError: this._options.modifiers.map is not a function`.
Btw. I'm using version 0.6.4. According to the documentation, options.offset ist just a number? https://popper.js.org/documentation.html#new_Popper
What I actually want is to change the offset later, once the Popper is already shown.

**Comment by lukebatchelor** [comment]
I changed that a few minutes ago, sorry. I've been working with the dev-1 version, very different API. See the above

**Comment by TheCaptainDate** [comment]
@lukebatchelor Hi!
Offsets doesn't work for me :/
Trying to do this thing:

```
var anotherPopper = new Popper(element, popper, {
 $(".test").click(function (el) {
        var element = $(el.toElement);

        var popper = $('.popper');
        var anotherPopper = new Popper(element, popper, {
            placement: 'top',
            offset: 10
        });

    });
```

And nothing happens. Even if i trying to change placement to 'bottom' - no effect, still 'top' actually.

**Comment by klemensz** [comment]
Same thing here, cannot get it to work.

**Comment by TheCaptainDate** [comment]
Well i am finally found a tricky way to add offset. Guess what? A 'margin' with negative values applied to popper div. The only working way for me now :/

**Comment by lukebatchelor** [comment]
@TheCaptainDate 100%, I'd reccomend against doing it with -ve margins.

I hadnt actually worked with the old API before, so I had a quick go at it. Turns out the offset option moves you **along** the positioned side, not away from it. The new api is much more flexible. This codepen should give you a good starting point to work from though for getting your offsets working
http://codepen.io/hotmilo23/pen/vyZRMq?editors=1111

Pasting here in case I ever change that pen accidentally

```
var target = document.querySelector('.foo');
var popperElem = document.querySelector('.bar');

// takes the current top offset and adds 50
var offsetTopModifier = function(data) {
  data.offsets.popper.top += 50
  return data;
}

var popper = new Popper(target, popperElem, {
  placement: 'bottom-end',
  offset: 10, // this moves us 10px to the right (not what you need)
  modifiers: [ 'shift', 'offset', 'preventOverflow', 'keepTogether', 'arrow', 'flip', offsetTopModifier, 'applyStyle']
});

/* We apply the offsetTopModifier BEFORE the apply style modifier so that it gets included*/
```

**Comment by FezVrasta** [comment]
thank you for the information!

sorry but I'm not in my country these weeks and I'm still trying to organize myself to be able to work from here.

**Comment by WebKieth** [comment]
Issue didnt solved.
This plugin has got the most terrible API which I ever seen. God damn those idiots who install it on my current project. 
I try to update offsets by merging options of my wrapper class and this plugin like @lukebatchelor and doesnt work

```javascript
 let activeRefClass = ref.getAttribute('data-active-mod'),
        activeLayClass = layout.getAttribute('data-active-mod');
        let modifyOffsets = (data) => {
            let mergedProps = this._mergeProps(this.options.offsets, data.offsets);
            data.offsets = mergedProps
            return data
        }
        let popperInstance = new Popper(ref, layout, {
            placement,
            modifiers: [ 'shift', 'offset', 'preventOverflow', 'keepTogether', 'arrow', 'flip', modifyOffsets, 'applyStyle']
        });
        layout.classList.add(activeLayClass);
        ref.classList.add(activeRefClass);
```
ModifyOffsets function just dont execute

**Comment by WebKieth** [comment]
Working version:
``` javascript
let modifyOffsets = (data) => {
            let mergedProps = this._mergeProps(this.options.offsets, data.offsets);
            data.offsets = mergedProps
            return data
        }
        let popperInstance = new Popper(ref, layout, {
            placement,
            modifiers: {
                offset: {
                    fn: modifyOffsets
                }
            }
        });
        layout.classList.add(activeLayClass);
        ref.classList.add(activeRefClass);
```

**Comment by FezVrasta** [comment]
@WebKieth I'm not even sure why I'm replying to you, considering how rude are you, but here I am.

The reason why the offset modifier doesn't allow you to do `{ top: 10, right: 20, bottom: -20, whatever}` is because 99% of the times, you don't want to work with absolute coordinates, but with ones relative to the current popper placement.

So, you want to say "offset the popper from the reference element by 20px, and offset it by its side by 10px".

Anyways, I'm gonna lock this thread, let's open a new one and make sure to follow the issue template if more help is needed.
