### ISSUE TITLE
popper element causes document overflow inside css grid

### ISSUE THREAD

**Issue by PhilReinking** [FezVrasta/popper.js#111]
Hey there,

I played the last few hours a lot with popper.js. My goal was to build a dropdown menu which automatically shifts it's position, when it normally would flow out of the viewport.

In my project I use Bootstrap and of course my dropdown element is somehow nested into Bootstraps grid. If I call the popper function I would expect the popper element always to stay in the viewport boundaries. But instead the element causes the page to render vertical scrollbars on some resolution (for example in a viewport between ~900 - ~1200px).

If I remove Bootstrap grid CSS, then i get the expected result and no overflow is happening at all.

So because of this I guess that somehow the margins and paddings on the bootstrap grid classes are not respected by popper.js.

Here is my Codepen. Try to play with the window size to see the bug.
http://codepen.io/PhilReinking/pen/BQYemN

Regards,
Philipp

**Comment by FezVrasta** [comment]
This is weird.

May I ask you to try out the same codepen using 1.0.0-alpha.6? If it fails there as well then we'll want to create a test case and make sure it passes.

**Comment by PhilReinking** [comment]
I just tried out my example with v1.0.0-alpha.6 and there was only one change required to make it work.

If the minimum body height is not set to the viewports height (100vh) then the plugin would position the element out of the screen and add the `x-out-of-boundaries` attribute to it.

The absolute positioning seems to work with the v1.0.0-alpha.6.

Here is my Codepen with the mentioned changes:
http://codepen.io/PhilReinking/pen/ObZaxN

**Comment by FezVrasta** [comment]
Ah nice! 

I'll keep this issue around since it's still a v0 bug, but I don't plan to spend time on v0 to fix it since v1 is near its first stable beta.

I hope it makes sense.

**Comment by PhilReinking** [comment]
Yep, for me it is ok. I stick with the new version.

**Comment by FezVrasta** [comment]
Since v1 is almost here, I'm going to close this issue suggesting everybody to move to v1.
