### ISSUE TITLE
Popper cut off when target element is inside element with overflow: hidden;

### ISSUE THREAD

**Issue by mm2ha** [FezVrasta/popper.js#112]
First of all, thank you so much for putting this project together. It is absolutely awesome and I was extremely happy when I found it. 

I ran across one issue when testing it in our application and I figured I would let you know because I could not find anything like this mentioned in the already existing issues.

----------------

### CodePen demo

https://codepen.io/anon/pen/rWvMPO

### Steps to reproduce the problem

1.  Have a target element inside an element that has property overflow: hidden;
2.  Create popper
3.  Popper will be cut off at the limits of the innermost element with overflow: hidden;

### What is the expected behavior?

I expected that the popper should be visible.

### What went wrong?

Looking at the popper code, it seems like it never moves the popper element to a different place in the DOM to avoid this issue.

### Any other comments?

Similar behavior occurs when an element has overflow: scroll. In that case I would expect the popper to be initially visible and then scroll with the target.

**Comment by FezVrasta** [comment]
hi, this is the expected behaviour. the nice thing about Popper is its ability to position poppers even if they are in contexts different from their reference element.

you should move the popper element outside of the `overflow: hidden` container.

I hope it answers your question

**Comment by mm2ha** [comment]
@FezVrasta thanks for the tip, I got it working!

**Comment by clintharris** [comment]
@FezVrasta does this mean it works, for example, if `<Popper>` is in the "root" of `<body>` and `<Target>` is in an `overflow:hidden` container nested much deeper in the tree? (i.e., position has to be calculated or something?)

**Comment by FezVrasta** [comment]
Yes it should work in the case you describe

**Comment by akhilaudable** [comment]
Say, we have a parent component which has `overflow: hidden` and in one of the children component we should implement `Popper`. Now how can I go back to the parent and change the parent's style(remove  `overflow: hidden`) to get the Popper? How will this become expected behavior?
