### ISSUE TITLE
Positioning on spans

### ISSUE THREAD

**Issue by miljan-aleksic** [FezVrasta/popper.js#116]
Hi, seems the positioning is failing when using spans. Check

### CodePen demo

https://codepen.io/miljan/pen/pNGaoE

### Steps to reproduce the problem

1.  Just open the pen

### What is the expected behavior?

I would expect the pop to be centered over the ref on bot situations

### What went wrong?

When using span it doesn't happen

### Any other comments?

It does work fine with alpha7

**Comment by FezVrasta** [comment]
Thanks for the report.

I simplified the example here:
https://codepen.io/FezVrasta/pen/LbqQyX

Seems like a regression with the way we calculate the element' sizes

**Comment by FezVrasta** [comment]
fixed!

**Comment by miljan-aleksic** [comment]
@FezVrasta, the issue seems persisting - https://jsfiddle.net/miljan/1qsozyt4/

**Comment by FezVrasta** [comment]
You are using beta.1 there. With beta.2 this is the result:
https://jsfiddle.net/mcasomts/1/

Which is still weird, but on the tests I added I can't reproduce this specific problem. If you can create a PR with this specific case it would be great.

**Comment by miljan-aleksic** [comment]
I can confirm this works well with v1b4. Thanks!
