### ISSUE TITLE
Add option to disable/pause event listeners

### ISSUE THREAD

**Issue by sqal** [FezVrasta/popper.js#117]
I just have a simple question. Is it possible to temporarily prevent popper from calculating position (on scroll mainly) when i need to? E.g I have tooltip component and when element isn't visible i see that popper is still calculating position when I scroll and `onUpdate` callback is called like 100 times. Can I prevent this from happening without initializing instance before tooltip is shown and destroying it after is hidden? (that sounds like a really bad idea though :/). Unfortunately I don't see any option which could help me with this, so is there currently any solution for this problem of mine? Thanks for the any help/tips/anything.

P.S. I am using latest version - v1.0.0-beta.1

**Comment by FezVrasta** [comment]
hi! first, latest beta is beta.2 😛

focusing on your question:

what's the problem in destroying and recreating the instance when you toggle the visibility?

**Comment by sqal** [comment]
> what's the problem in destroying and recreating the instance when you toggle the visibility?

Hmm not sure.. just feel that it's unnecessary to do it every time I toggle my tooltip, I would like to initialize an instance just once. Also i guess it would be more memory efficient to initialize popper just once. What you think about adding `disabled` option that would turn off all modifiers? It wouldn't be so difficult to implement I think. If you want, I can try to do it.

**Comment by FezVrasta** [comment]
Sure, feel free to send a PR with this feature. Thanks!
