### ISSUE TITLE
Event hooks?

### ISSUE THREAD

**Issue by lerayj** [FezVrasta/popper.js#12]
I'm not able to find any hooks from the attached popper's element.
For example it would be cool to set an onHover behavior at the instanciation.
Isn't it possible? 
Is there the place for write one of what you call modifier?

**Comment by lerayj** [comment]
#

**Comment by FezVrasta** [comment]
Hi @lerayj !

As pointed [here](https://github.com/FezVrasta/popper.js/issues/8) right now there's not support for it. Feel free to continue on the issue I've linked here if you need anything else.
