### ISSUE TITLE
Removing pop from dom issue

### ISSUE THREAD

**Issue by miljan-aleksic** [FezVrasta/popper.js#123]
In previous alphas was possible to remove the pop from dom and get it back without any issue. Now is throwing some nasty errors. Is this a new limitation or a bug?

### CodePen demo

http://codepen.io/FezVrasta/pen/dNbgxv

### Steps to reproduce the problem

Open the jsfiddle and check the console

### What is the expected behavior?

To don't throw any error on removing the pop from dom.

**Comment by FezVrasta** [comment]
We should make a check to be sure the popper node is still in the DOM.

Why do you want to remove the popper node leaving the instance up?

**Comment by miljan-aleksic** [comment]
In my Tooltip implementation where only one popper at a time can be visible, I thought to keep the dom clean. No any clear advantage, so I can adapt my code.

**Comment by FezVrasta** [comment]
Why don't you destroy the Popper instance?

**Comment by miljan-aleksic** [comment]
If that's the recommended way, I can do that. I thought it could affect performance?

**Comment by FezVrasta** [comment]
actually the overhead of the initialization is very low, it's almost l like a simple update

**Comment by FezVrasta** [comment]
I just profiled the difference, the initialization takes 1.5ms and the updates take 1ms.

**Comment by FezVrasta** [comment]
I fixed the problem here:
https://github.com/FezVrasta/popper.js/commit/85e144cce15aa85ad42f3516d786fd21e1e8e403

Seems to work properly now.

**Comment by miljan-aleksic** [comment]
I can confirm this works well with v1b4. Thanks!
