### ISSUE TITLE
Dist files in beta.4 aren't transpiled to es5

### ISSUE THREAD

**Issue by sqal** [FezVrasta/popper.js#125]
After updating popper.js to beta.4, I was suddenly started getting this error from UglifyJs while trying to build my bundle:

```
ERROR in static/js/app.3d0a532b.js from UglifyJs
SyntaxError: Name expected [static/js/app.3d0a532b.js:5351,10]
```

Quick look into dist/popper.es5.js, turns out it's not es5 version, it's full es6 syntax so that's why UglifyJs can't minify this file and hence above error

**Comment by FezVrasta** [comment]
Thanks for the heads up. I will look at it ASAP

**Comment by FezVrasta** [comment]
Should be fixed now. I have not released a new beta tho, so to test it you have to compile them manually.

**Comment by FezVrasta** [comment]
@sqal any reason why are you minifying the files manually instead of use the provided minified version? I switched to babili as minifier to generate the smallest bundles possible.

**Comment by sqal** [comment]
@FezVrasta I am using webpack

**Comment by FezVrasta** [comment]
I see, but webpack shouldn't require the `jsnext:main`entry point?
