### ISSUE TITLE
Complete react example

### ISSUE THREAD

**Issue by rsaccon** [FezVrasta/popper.js#130]
Is there a complete react example on how to integrate popper v1 ? I saw your [comment](https://github.com/souporserious/react-popper/issues/1#issuecomment-269799594) on how you recommend to implement it, but I did not fully understand how such an implementation is going to look like, but I guess more simple and more performant, and less boilerplate, if rendering into portal react component can be skipped. I also saw this complete but older example of yours: https://gist.github.com/FezVrasta/6533adf4358a6927b48f7478706a5f23. What about the follow-up comment about `raf` ? Is that still valid ?

**Comment by FezVrasta** [comment]
Yup the gist you linked seems like was bugged.

What isn't clear in my comment on `react-popper`?

**Comment by rsaccon** [comment]
thanks for quick replay. What I was concerned was the comment https://gist.github.com/FezVrasta/6533adf4358a6927b48f7478706a5f23#gistcomment-1757433 about infinte loop. Is that still relevant ? Otherwise I guess I just use `ref` to react components for popper and reference, and that is all, no wrapper component like `react-popper` needed, right ?

**Comment by FezVrasta** [comment]
I updated the gist to use the new v1 API:
https://gist.github.com/FezVrasta/6533adf4358a6927b48f7478706a5f23

I have not tested it but it should be a good starting point.

**Comment by rsaccon** [comment]
Great, thanks.

**Comment by FezVrasta** [comment]
If you manage to create a working component please consider publishing it on npm, or if you prefer you may want to contribute to `react-popper` to add this behavior.

**Comment by silvenon** [comment]
@FezVrasta a question about your gist: I see that the `update()` method isn't being called anywhere. Was this supposed to be `componentDidUpdate()`?

**Comment by FezVrasta** [comment]
Good catch, it shouldn't be needed I think. You may want to use it if you need to hide/show the popper.
