### ISSUE TITLE
3rd party wrappers

### ISSUE THREAD

**Issue by FezVrasta** [FezVrasta/popper.js#139]
So, we have a pretty good standalone and abstractable (does this word even exists) library here.

Some cool people started to work on wrappers to integrate in popular frameworks and libraries, I would like to actively support at least one for each popular framework to give something that works out of the box to the Popper users.

### [react-popper](https://github.com/souporserious/react-popper)
This is a great wrapper and properly supports everything you'd expect from it.

### [ak-layer](http://aui-cdn.atlassian.com/atlaskit/registry/ak-layer/latest/index.html)
The guys at Atlassian work on this component but as far I know, they haven't released the source code isn't released. I'm not able to help with this one so.

### [angular-popper](https://github.com/jacobharasimo/angular-popper)
I talked with the owner, Jacob, and he said that he has not time to actively work on it. Any help to upgrade it to v1 would be very appreciated!

### [vue-popper-component](https://github.com/antongorodezkiy/vue-popper-component)
This one supports v1 but not having experience with Vue I don't know the quality of it or if it supports all the features. Feedbacks are welcome.

## Inferno
I don't think there are wrappers for Inferno, but once we have a React version working I don't think porting it should be difficult?

## Preact
Same as Inferno?

## Ember.js
I talked with the maintainer of [liquid-tether](https://github.com/pzuraq/liquid-tether)(@pzuraq), he's working on an Ember.js wrapper!
https://github.com/kybishop/ember-popper

## Glimmer.js
I don't know much about it, if it's similar to Ember.js then I think that @pzuraq will be able to port its library?

---------

This issue aims to keep track of the work done on the wrappers and to let know people that I'm open to help anyone that wants to write one if needed.

**Comment by antongorodezkiy** [comment]
Just updated [vue-popper-component](https://github.com/antongorodezkiy/vue-popper-component) to support Popper.js v1

**Comment by FezVrasta** [comment]
awesome! thanks

**Comment by FezVrasta** [comment]
Closing in favor of [MENTIONS.md](https://github.com/FezVrasta/popper.js/blob/master/MENTIONS.md).
