### ISSUE TITLE
Bootstrap dropdown example

### ISSUE THREAD

**Issue by 719media** [FezVrasta/popper.js#150]
Hello

I wrote a quick dropdown example for usage with bootstrap.

https://jsfiddle.net/13xr2mcd/14/

Do you mind giving it a quick once over just to see if there is anything that could be done differently or more efficiently using library methods I may not be aware of?

It did not seem that popper.js had anything that "moved" the dropdown-menu automatically based on any configuration, if you were trying to escape relatively positioned elements. Which is fine and I am not saying is necessary. I just wanted to make sure I understood the library enough to say that this is a way to have it work with bootstrap.

Thanks for your time and for making this library.

**Comment by FezVrasta** [comment]
Something weird is happening 😅

![image](https://cloud.githubusercontent.com/assets/5382443/21942482/9e87acc0-d9cd-11e6-85a7-bb01fde94077.png)

**Comment by FezVrasta** [comment]
Yes, Popper doesn't move elements around, you have to move them by yourself.

The code seems pretty linear, looks good to me.

**Comment by 719media** [comment]
Hm interesting, I can't seem to mimic that behavior. I tried using latest chrome/firefox/safari on mac, and they all work. What dropdown was giving that behavior?

I made the dropdown have unique prefixes to easily tell which one is open.

https://jsfiddle.net/13xr2mcd/15/

**Comment by 719media** [comment]
OK thanks. I was just trying to put something together to add to convo over at bootstrap. Thank you

**Comment by FezVrasta** [comment]
Great, if you have any other questions please let me know!

**Comment by FezVrasta** [comment]
@719media just tought you could use `disableEventListeners` and `enableEventListeners` instead of create and destroy Popper.js each time the dropdown is hidden and shown.

https://popper.js.org/popper-documentation.html#Popper+enableEventListeners

**Comment by kunal02singh** [comment]
https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js
Download and Add popper.min.js befour bootstrap.min.js

**Comment by FezVrasta** [comment]
LOL? 😅
