### ISSUE TITLE
Flipping all around

### ISSUE THREAD

**Issue by HHogg** [FezVrasta/popper.js#167]
Currently the `behaviour` property on the flip modifier allows for a `flip` value, which will consider the opposite side. Do you think popper.js should provide core behaviour for flipping on all sides where the opposite side is secondary, followed by the opposite axis?

_I know this can be done by passing in a custom behaviour array_

For example:

```js
new Popper({ 
  placement: 'left',
  modifiers: {
    flip: {
      behaviour: 'around',
    },
  }, 
});
```

Which would result in the flip order becoming...

```js
[
  'left', 'left-start', 'left-end',
  'right', 'right-start', 'right-end',
  'top', 'top-start', 'top-end',
  'bottom', 'bottom-start', 'bottom-end',
]
```

If you think this belongs in popper.js, I'm more than happy to send a PR to implement it.

_I'm sure this is something you (@FezVrasta) have considered going by the issue  on [Tether #158](https://github.com/HubSpot/tether/issues/158)._

**Comment by FezVrasta** [comment]
So, should we have `clockwise` and `counterclockwise`?

**Comment by HHogg** [comment]
Yeah, that would actually be better. It seems unnecessary to also have `around`, I'll put together a PR and we can see how it feels.

**Comment by HHogg** [comment]
I'm thinking @FezVrasta, maybe the `start` and `end` variants aren't needed because of the awesome arrow moving functionality?

**Comment by FezVrasta** [comment]
yup probably they aren't needed

**Comment by kyletinsley** [comment]
I think clockwise does not work as expected in the latest version of popper:
https://codepen.io/anon/pen/barMXr

**Comment by FezVrasta** [comment]
@kyletinsley may you open a new issue pls?

**Comment by hualu00** [comment]
@FezVrasta , I don't think 'clockwise' work as expected either, here is an example,  
https://codepen.io/anon/pen/xJrEry
