### ISSUE TITLE
.babelrc shouldn't be published to npm

### ISSUE THREAD

**Issue by janwidmer** [FezVrasta/popper.js#168]
### CodePen demo
Build Stack issues cannot be showcased on codepen.

### Steps to reproduce the problem

1.  Setup an FE Build Stack with Gulp and Popper.js
2.  Add popper.js to your build
3.  When building, the following command line error appears:

[09:01:35] Plumber found unhandled error:
 ReferenceError in plugin 'gulp-babel'
Message:
    Unknown plugin "external-helpers" specified in ".../node_modules/popper.js/.babelrc" at 0, attempted to resolve relative to ".../node_modules/popper.js"

### What is the expected behavior?

The expected behaviour is, that the build works and the popper.js gets included to my generated app.js

### What went wrong?

The current behaviour is, that popper.js does not get included because of the above problem.

### Any other comments?

According to the Babel documentation, the plugin "external-helpers" can be added by installing the "babel-cli". This probably needs to be added to the package.json of popper.js (see https://babeljs.io/docs/plugins/external-helpers/#detail-getting-the-external-helpers)

**Comment by FezVrasta** [comment]
we already define `babel-plugin-external-helpers`so we don't need `babel-cli`

I guess I need a repro to understand the problem, as far I know, it works just fine with both Webpack and Rollup. What bundler do you use?

**Comment by janwidmer** [comment]
I'l try to setup a demo repo, where the problem can be seen..

**Comment by janwidmer** [comment]
Hey..
I created a demo repo where you can see the problem: https://github.com/janwidmer/popper-js-test

1. Checkout the repo
2. Run npm install
3. Run gulp develop
4. You see the above error in the command line

Notes:
The Demo Repo contains our open source frontend prototyping framework (See https://github.com/namics/generator-nitro) It is a node js based framework to make frontend protoptypes and applications. The Assets (js / css) get assembled by gulp. You can see the assemble config in the fil config.json at root level.

**Comment by FezVrasta** [comment]
Sorry I have not experience with gulp... this is what I get when I run `gulp develop`:

```
▶ gulp develop
module.js:472
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/gulp/node_modules/v8flags/cache/5.4.500.45.flags.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:25:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by janwidmer** [comment]
Just to make sure, did you run "npm install" before running "gulp develop"?

mmh maybe try to run "npm install -g yo gulp generator-nitro" which are libraries needed for the frontend framework..

**Comment by FezVrasta** [comment]
Ok installing that bunch of stuff globally fixed the problem (emh..)

By the way, if I remove the `external-helpers` from the `.babelrc`, it complains about `stage-2`, looks like the build step doesn't have access to any of the babel plugins and presets needed.

I guess we shouldn't publish `.babelrc` to npm since the bundles sent to npm are already transpiled.

**Comment by FezVrasta** [comment]
Published as 1.0.6.

@janwidmer it works locally on the repro you provided. It fails on the minification step but it has nothing to do with this problem from what I see.

**Comment by janwidmer** [comment]
@FezVrasta Perfect, now the error is gone. About the minification error, that appears, when I use the standard version popper.js (containing es6  code) because the gulpify task cannot handle es6 code (see http://stackoverflow.com/a/40521802) Therefore I have to use the popper.es5.js and it works.

Thanks for your support.
Jan

**Comment by FezVrasta** [comment]
yw!

**Comment by janwidmer** [comment]
maybe a hint in the readme would be good, since one probably does not except a js plugin to contain es6 code in the standard version of a plugin.. on the other hand, one could see that there is an es5 version.. ;-)

**Comment by FezVrasta** [comment]
Actually the default version **is** the ES5 one:
https://github.com/FezVrasta/popper.js/blob/master/package.json#L5-L6

Maybe your build tool is using the `next` version for some reason?
