### ISSUE TITLE
placement: 'top' - does not flip the popper when it touches the upper viewport boundary 

### ISSUE THREAD

**Issue by Maaahki** [FezVrasta/popper.js#171]
### Steps to reproduce the problem
1.  Visit https://popper.js.org
2.  In the first example (#example10positionSelector) choose 'top'
3.  Scroll down

### What is the expected behavior?
Popper should be placed under the trigger, as soon as the upper viewport boundary is hitting the popper's top border.

### What went wrong?
Popper is not flipped to bottom.

### Any other comments?
Choosing placement: "bottom" works as expected

**Comment by FezVrasta** [comment]
Nope, most of these examples are constrained by their parent boxes, not by the viewport. It's working as expected. The only one constrained by viewport is the 5th

**Comment by FezVrasta** [comment]
Thank you for the report. If you (or anyone else) could send a PR with a new test that reproduces the problem it would be super useful.

**Comment by FezVrasta** [comment]
Just an update to inform that #178 haven't fixed this problem.

I'm not sure if @claudiobmgrtnr wants to dig into it (if he has time)?

**Comment by FezVrasta** [comment]
I'm working on it.
