### ISSUE TITLE
Popper content inside translateX parent causes misalignment

### ISSUE THREAD

**Issue by bengummer** [FezVrasta/popper.js#172]
### CodePen demo

http://codepen.io/bgummeratlassian/pen/egwEjZ

### Steps to reproduce the problem

(see codepen demo)

1. Place the trigger and content as siblings, in the same parent
2. Position the parent at the bottom of the screen, with translateX style
3. Create a new Popper instance for the trigger and content, with `placement: top`

### What is the expected behavior?

Popper content should be shown above the button, which is at the bottom of the page

### What went wrong?

With translateX on the parent, the popper content is shown underneath the button even though we have `placement: top`

### Any other comments?

In the codepen example, disabling the `translateX` style (then refreshing the page and clicking the button) works as expected.

**Comment by nblackburn** [comment]
Getting this issue too

**Comment by FezVrasta** [comment]
@nblackburn please may you open a new issue and post a minimal codepen example without any extra dependencies? Thank you!

**Comment by nblackburn** [comment]
@FezVrasta The dependencies were added to make it realistic to the scenario i was faced with so you could see what i was seeing.

**Comment by FezVrasta** [comment]
yup I get it, but please may you open a new issue with a simplified codepen? 🙂

**Comment by nblackburn** [comment]
Do we have a ETA on the fix for this?

**Comment by FezVrasta** [comment]
It would be easier for me to work on this if someone could send a PR that adds a failing test for this specific bug in our test suite.

By the way, nope, I haven't an ETA, I don't work full-time on this project and I try to allocate some time on it during my free time.

PRs are super welcome.

**Comment by FezVrasta** [comment]
I'm merging this into #202 since they are strictly related.

**Comment by ventralnet** [comment]
I had a similar problem to this if a parent node had overflow: auto;
