### ISSUE TITLE
Modifier / Custom Modifier Syntax

### ISSUE THREAD

**Issue by janwidmer** [FezVrasta/popper.js#173]
Hi There,
Finally I managed to update my popper from version 0.6.4 to 1.0.6. Including it in my build stack now works.

Apparently, the syntax around the modifiers has changed a little bit and I cannot seem to find the information in the documentation.

My Case:
I have a list of modifiers, which I want to apply. This list also contains a custom modifier which applies special styling for certain viewports.

You can see the setup in this codepen demo: http://codepen.io/janwidmer/pen/PpYWRN

My question is: How can I define a list of (default) modifiers (without any changes from default values) and have one custom modifier being called before the "applyStyle" modifier?

Best Regards
Jan

**Comment by FezVrasta** [comment]
Hi, here you can find an example:
https://github.com/FezVrasta/popper.js#react-vuejs-angularjs-emberjs-etc-integration

We also have a test that shows it:
https://github.com/FezVrasta/popper.js/blob/master/tests/functional/core.js#L692-L711

The documentation is available here:
https://github.com/FezVrasta/popper.js/blob/master/docs/_includes/popper-documentation.md#modifiers--object

Also, check out the migration guide to read more about the changes of the modifiers from v0 to v1:
https://github.com/FezVrasta/popper.js#migration-from-popperjs-v0

I hope it answers your question.

**Comment by janwidmer** [comment]
Great, that was the information I could't find. Now it works with the newest version, thanks.

**Comment by FezVrasta** [comment]
yw
