### ISSUE TITLE
Popper position calculation fails if offsetParent is inside an offsetParent

### ISSUE THREAD

**Issue by claudiobmgrtnr** [FezVrasta/popper.js#177]
We tried already to narrow the bug down and opened #174 however we didn't manage to reproduce the real underlying problem.

### CodePen demo

https://codepen.io/claudiobmgrtnr/pen/QpWNVL

![popper-offsetparentbug](https://cloud.githubusercontent.com/assets/3873078/23260748/90aca04e-f9d3-11e6-9838-9840ea71f48b.png)

### Steps to reproduce the problem

1.  Create a `wrapper` and a `outer-wrapper` with `position:relative`
2.  Add a `ref` and `pop` with `position:relative`
3.  Pop the popper: 

```js
new Popper(ref, pop, {
  modifiers: {
    preventOverflow: {
      boundariesElement: 'viewport',
    }
  }
})
```

### What is the expected behavior?

Popper keeps tooltip element into the viewport

### What went wrong?

Tooltip is outside the viewport

### Possible solution

After looking into popper.js we found the root for this issue here:

https://github.com/FezVrasta/popper.js/blob/f5a309e2cf56064ffca3a2c64796aed67e83f367/src/popper/utils/getOffsetRect.js#L23-L26

```js
   left: element.offsetLeft, // Relative to the offsetParent not to the viewport
   top: element.offsetTop, // Relative to the offsetParent not to the viewport
```

We created an additional function for the cases where the position relative to the viewport was needed and could fix the error.

Do you want us to create a merge request for this?

We are not 100% sure but this might also fix #172

**Comment by FezVrasta** [comment]
May you send a PR with a test that reproduces the problem and your fix please?
