### ISSUE TITLE
Arrow position

### ISSUE THREAD

**Issue by nblackburn** [FezVrasta/popper.js#179]
How would i go about positioning the arrow to the left when placement is `bottom-start` as i can't seem to find anything about this in the documentation?

**Comment by FezVrasta** [comment]
You should write your own modifier, the arrow position isn't customizable at the moment.

**Comment by nblackburn** [comment]
@FezVrasta Can you give me an example on that is done?

**Comment by FezVrasta** [comment]
I replied a similar question recently:
https://github.com/FezVrasta/popper.js/issues/173

You should create a modifier that edits the `data.offsets.arrow` value

**Comment by FezVrasta** [comment]
If by chance you end up creating this modifier, please consider to publish it to npm 👍

**Comment by nblackburn** [comment]
@FezVrasta Thanks and of course i would share it, i am not a monster.

**Comment by FezVrasta** [comment]
Ahah sorry, it's just that lot of people don't think about it, not with bad intentions, they just think it's something not useful to others.

**Comment by rmartins90** [comment]
Any new on this? I'm trying also to write a modifier to position arrow.

**Comment by FezVrasta** [comment]
Nope, the solution is still the same, create a modifier or send a PR to add this functionality.

**Comment by OliverJAsh** [comment]
Does anyone have an example of how to do this using v2 of the library?
