### ISSUE TITLE
Polymer element

### ISSUE THREAD

**Issue by JosefJezek** [FezVrasta/popper.js#18]
Could you create polymer element?

- https://www.polymer-project.org/1.0/docs/start/reusableelements.html
- https://elements.polymer-project.org/elements/paper-tooltip
- https://customelements.io/

**Comment by FezVrasta** [comment]
May you give me some hint about what would you expect from such polymer element?

Should it be a component that accepts as argument the reference/trigger element or should be an element which spawns the popper?

**Comment by FezVrasta** [comment]
I'm going to close it as the OP is not giving details about his feature request.
