### ISSUE TITLE
I'm confused with the padding of flip and preventOverflow in the doc

### ISSUE THREAD

**Issue by bojoyzhou** [FezVrasta/popper.js#180]
`preventOverflow.padding` is actually what I want, but their description are the same.

![image](https://cloud.githubusercontent.com/assets/5258697/23497597/d5eaccfe-ff5e-11e6-9bbe-b3557d4361b1.png)

**Comment by FezVrasta** [comment]
They are two different paddings, the first is used during the preventOverflow algorithm (the one that shifts your popper to keep it in its constraints), the other is the one used to decide when the popper should flip.

The documentation should be improved to reflect these informations.
