### ISSUE TITLE
Weirdness when scrolling over the popout element inside a scrollable element

### ISSUE THREAD

**Issue by ryanzec** [FezVrasta/popper.js#181]
So I was looking for an alternative to tether.js as I noticed issues with scrolling over the popout element causing scrolling of the parent to stop / be janky and pretty sure it had to do with the fact that while the popout element appears in the scrollable container, in the DOM it is not so when the mouse moves of it, the parent no longer scrolls. This library seemed to be recommended and when looking at the demo, it seemed like the popout element was not being render outside of the parent like with tether.js. I found a React example and tested it out and found that the same exact thing was happening. I am trying to figure out what exactly is causing the parent scrolling to stop when the mouse is over the popover element even when the popover element is inside the scrollable parent.

![popper-issue](https://cloud.githubusercontent.com/assets/444206/23509345/66004fd0-ff23-11e6-87de-17e87939f5e1.gif) 

### CodePen demo

http://codepen.io/ryanzec/pen/ryxYEe

### Steps to reproduce the problem

1.  Move your mouse above or under the popout element and then scroll towards the popout element

### What is the expected behavior?

The scroll should continue through when the mouse enters the popout element

### What went wrong?

The scrolling stops (unless you scroll really fast) when the mouse enters the popout element

**Comment by FezVrasta** [comment]
I think it's just the way HTML and CSS work. You may set `pointer-events: none` on the element if you don't need it to be clickable, or set it only during the scrolling if you need it to be clickable.

By the way the React code you are using seems pretty hacky, have a look at https://github.com/souporserious/react-popper (master branch) for a good implementation.

**Comment by FezVrasta** [comment]
Edit, actually in our demo we don't use `pointer-events`.. I'm not sure why it works there 🤔

**Comment by FezVrasta** [comment]
Closing because of lack of interest from the OP.

**Comment by ryanzec** [comment]
Oh, sorry about not responding, meant to but just forgot. Yea, I forgot about the `pointer-events` property that could be used and that does fix the issue in this case for me.

Thanks for the help.

**Comment by brandondurham** [comment]
This is an old issue, but I’m experiencing this problem. I have a Popper inside of a scrollable container. When the mouse is over the Popper, scrolling is disabled. I can’t set `pointer-events: none;` on this Popper because it contains interactive elements. Buttons, dropdowns, links, etc.

Is there another way out of this?
