### ISSUE TITLE
parameter 1 is not of type 'Element'

### ISSUE THREAD

**Issue by thierryskoda** [FezVrasta/popper.js#19]
Hi, I'm trying to use Popper.js with my angular project and I receive the error : "Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'. " 

Here is my code

```
var test1 = document.getElementById("test");
var test2 = angular.element("#test");
var test3 = angular.element(document.querySelector('test'));
var test4 = $document.find('#prize__title');

var thePopper = new Popper(test4,
    {
        content: 'My awesome popper!'
    },
    {
        // popper options here
    }
  );
```

Thank you very much!

**Comment by jbiron** [comment]
I think that $document.find return JQuery-like element for chaining purpose and not an HTMLElement...

**Comment by FezVrasta** [comment]
You are passing a jQuery element as reference element, Popper.js accepts only DOM Node Elements.
