### ISSUE TITLE
Incorrect positioning when margin is applied to HTML

### ISSUE THREAD

**Issue by miljan-aleksic** [FezVrasta/popper.js#191]
### CodePen demo

https://codepen.io/miljan/pen/VpBMPv

### Steps to reproduce the problem

1.  Open the pen and check the positions

### What is the expected behavior?

#pop to be positioned below #ref 

### What went wrong?

The #pop gets positioned as if there was no margin applied to HTML, to where the #ref would be in that case.

### Any other comments?

Many offcanvas animations apply margin to html which brakes all popper positions.

**Comment by FezVrasta** [comment]
I'm on a plane right now, testing from Safari mobile it works as expected. I'm going to investigate more once I turn on my Mac

**Comment by miljan-aleksic** [comment]
Indeed in Safari works well, even in desktop. The issue can be reproduced in Mac OS Chrome and Firefox.

**Comment by FezVrasta** [comment]
If you can, please, create a PR with a new falling test that reproduces the bug. It will be very helpful, I count to work on it this week.

**Comment by miljan-aleksic** [comment]
I'm not familiar with the project code or this kind of testing. Anyway I looked up the existing tests and it could look like:

```js
it('inits a bottom popper inside a document with margins', () => {
  const doc = document.documentElement
  doc.style.marginLeft = '300px';
  doc.style.marginTop = '300px';

  const reference = appendNewRef(1);
  const popper    = appendNewPopper(2);

  const pop = new Popper(reference, popper);

  // check positions
  
  pop.destroy();
});
```

If that's of any help :)

**Comment by FezVrasta** [comment]
Thank you, the PR should look like this:
https://github.com/FezVrasta/popper.js/pull/192

If you can send the PR, awesome, otherwise thank you anyway for the snippet you posted, I'll use it.
