### ISSUE TITLE
Add documentation to use reference object as replacement to DOM node

### ISSUE THREAD

**Issue by maxkfranz** [FezVrasta/popper.js#193]
It would be nice if a function could be passed instead of an html element for `reference` at init.  The function would return a bounding box that could be used for positioning.

The function is necessary --- rather than just a plain object --- to allow for cases where the bounding box would change over time.  This would allow updates with `popper.update()`.

Having this feature would make support for [libs like Cytoscape](https://github.com/nrnb/GoogleSummerOfCode/issues/84) much better.

Thanks for your consideration.

**Comment by FezVrasta** [comment]
That's something I'd like to add but I haven't time at the moment. There's some work needed to make this idea work.

**Comment by FezVrasta** [comment]
More context on the feature's requirements.

It should provide all the informations needed by Popper.js to be able to compute the position of the popper, for instance:

- Context of the fake element (where "is" it located in the DOM?) to make it possible to properly position the popper;
- All its sizes (everything outputted by `getBoundingClientRect()`)
- Popper.js must be changed to properly handle a function instead of an element.

**Comment by maxkfranz** [comment]
@FezVrasta Would it be possible to pass in a DOM-like object (or have the function return such an object)?  For example:

```js
let makeFakeDiv () => {
  return {
    getBoundingClientRect: function(){ /* ... */ },
    parentElement: document.body
  };
};

let popper1 = new Popper( makeFakeDiv() );

// or 

let popper2 = new Popper( makeFakeDiv );
```

This would probably not require as invasive changes, but the list of fields expected for the fake DOM object would have to be documented.  Even `popper1` can still be dynamic by changing what `getBoundingClientRect()` returns, so it would suffice for the Cytoscape.js usecase.

**Comment by FezVrasta** [comment]
As long your custom object "looks" like a DOM node I think Popper.js shouldn't complain about it.

**Comment by bedeoverend** [comment]
+1 for this. IMO the "DOM-like" object would be best. After some digging, it looks like the following interface would be needed:

```
getBoundingClientRect() : DOMRect
clientWidth : Integer
clientHeight : Integer
offsetParent : HTMLElement? = window.document.documentElement
```

Is there anything I'm missing? Obviously DOMRect you'd just need the interface, as constructing a literal DOMRect isn't supported in most browsers and isn't needed I assume, just so long as it has the same properties.

**Comment by FezVrasta** [comment]
I guess something needs to change in Popper.js to tell it to call the "DOM-like-object-factory-function-wahtever" and update `clientWidth`, `clientHeight` and `offsetParent` if you don't want to use `get`ters

**Comment by bedeoverend** [comment]
I'd be pro getters and no factory function - it would mean this would be a smaller PR, without closing the door on a function in future? 

But if not, what about an `onBeforeUpdate` callback? People could hook into that and update their "DOM-like" object's props? Though I guess that essentially comes to the same thing as getters anyway.

**Comment by FezVrasta** [comment]
Do you need a PR if you use getters? 🤔

I'm not against them, I'm not updated about the browser support and I think that a change like this would be quite minimal:

```
if(typeof reference === 'function') reference = reference() // I mean, with an actual type checking that works, lol
```

**Comment by FezVrasta** [comment]
Ok, updated my informations:
![image](https://cloud.githubusercontent.com/assets/5382443/24683485/a5e19230-199f-11e7-86aa-3119fb6d8b5d.png)

![img](http://img.pandawhale.com/post-38723-Neo-I-know-kung-fu-gif-Imgur-bUjp.gif)

**Comment by bedeoverend** [comment]
Hahaha - well down to IE9 is enough for popper yeah?

Ah yeah, can start using it straight away 😉 I guess just documenting that it `reference` needs to match this interface, rather than an `HTMLElement`?

Well, I know my use case would be covered purely by getters, but @maxkfranz does it cover your needs?

**Comment by FezVrasta** [comment]
Please do let me know if it works for you and share some working code if you can.

**Comment by bedeoverend** [comment]
Will do - I'll try get something together in the next few days

**Comment by FezVrasta** [comment]
I put together this:
http://codepen.io/FezVrasta/pen/evoMrR?editors=1010

I'm not sure if everything works, we should add a set of tests to make sure everything works properly.

**Comment by bedeoverend** [comment]
+1 for tests. I created [a fork](http://codepen.io/bedeoverend/pen/KWYjNp?editors=0010) of that codepen and it looks to be playing pretty nicely with a range - which is my use case, essentially having a toolbar object hover over text selection.

**Comment by FezVrasta** [comment]
Damn that's really cool! Great work

**Comment by FezVrasta** [comment]
I referenced #9 because seems like a natural step to support @bedeoverend use case.

I'm not sure how to proceed with it, basically we need to support a "non rectangular" reference element/area...

**Comment by Justineo** [comment]
@FezVrasta I tried to implement #9 earlier but when I dug into the code a little bit I feel uncertain about how should that fit into current calculations.

**Comment by maxkfranz** [comment]
As long as some kind of dom-like object is officially supported/documented as `reference`, that works for me.

**Comment by maxkfranz** [comment]
@FezVrasta Perfect, thanks.  I agree that the generator is just a nice-to-have.

**Comment by bedeoverend** [comment]
Awesome! Thanks @FezVrasta.

Personally, I'd prefer if it were documented that `reference` just had to match a certain interface i.e. be an object which has `getBoundingClientRect()` function and `clientWidth` / `clientHeight` properties (and maybe `offsetParent`). That way I'm not limited to just using `HTMLElement` or the new `Reference` class. But I'm not sure if that's shared by anyone or just me. I also understand that that could be annoying as it means you have to have backwards compatibility for it going forward.

**Comment by FezVrasta** [comment]
actually I'd like to avoid to add more code to the library since it's growing too much for my tastes in the past months.. Maybe I could simply document as you suggested and put the sample ReferenceClass in the docs folder (or a gist link) for reference?

**Comment by bedeoverend** [comment]
Yeah I think that sounds good. A `gist` or a guide on how to use it would be good 👍

**Comment by maxkfranz** [comment]
I agree it's better / more flexible to just have documentation.

**Comment by FezVrasta** [comment]
Looks like the recent changes introduced in 1.5.1 broken the possibility to use an object as reference element.

We should update the code to fix it.
