### ISSUE TITLE
Would you use this for a dropdown menu?

### ISSUE THREAD

**Issue by ericdfields** [FezVrasta/popper.js#2]
Seems like you'd want most of the same functionality to manage something like [Bootstrap's dropdown menu](http://getbootstrap.com/components/#dropdowns). Any reason not to use Popper for this? I like the idea of having one lib to manage my "boxes that need to appear positioned somehow relative to other boxes" needs.

**Comment by FezVrasta** [comment]
Popper.js is perfectly suited to manage dropdowns. I recently started using it for this purpose and it works flawlessly.

I'm not sure if I completely get what you are asking tho...

**Comment by ericdfields** [comment]
That's it!

**Comment by FezVrasta** [comment]
You're welcome!

**Comment by FezVrasta** [comment]
I can't think of any code me, or others, written to do this, but it's definitely something feasible.
