### ISSUE TITLE
Sticky Popper

### ISSUE THREAD

**Issue by kyleknighted** [FezVrasta/popper.js#20]
Would love to have the ability to set a specific tooltip to be "sticky" so that the user needs to click on either a (X) or clicking outside of the tooltip area. Being able to choose one or both options would be great as well.

**Comment by FezVrasta** [comment]
Seems like what you're asking is not something related to the position of the tooltip, right?

If so, everything not related to the position of the poppers should not be managed by Popper.js but by some 3rd party modifier or library.

Let me know if it does make sense to you.

**Comment by kyleknighted** [comment]
The more I'm playing with this lib, I'm understanding better what it's accomplishing. Sorry I made the issue before fully understanding your lib. Working great so far.

**Comment by FezVrasta** [comment]
Thank you! I plan to write some simple "tooltip/popover" management utility on top of Popper.js in the future. But for now my focus is to stabilize Popper.js to be sure it covers all the edge cases.

Cheers.
