### ISSUE TITLE
Popper on a fixed element

### ISSUE THREAD

**Issue by Webarkitekt** [FezVrasta/popper.js#21]
It seems that popper doesn't work well when the trigger is a fixed element.

**Comment by FezVrasta** [comment]
Please may you provide a demo using the template provided in CONTRIBUTING.md?

**Comment by Webarkitekt** [comment]
You can see the bug here : http://codepen.io/Webarkitekt/pen/Yqegjw. 
BTW your rawgit link seems to be broken i generate an other one.

**Comment by FezVrasta** [comment]
Thanks, I've fixed the URL of the CodePen template.

I'm trying to spot where is the problem in your case, I'll keep you updated.

**Comment by Webarkitekt** [comment]
Ok, thanks.

**Comment by FezVrasta** [comment]
May you check if 1782c39 fixed your problem?

**Comment by Webarkitekt** [comment]
Nice, seems to be ok. I'm going to try to add the fix on my project and will let you know. Thanks

**Comment by FezVrasta** [comment]
You're welcome :)

**Comment by Webarkitekt** [comment]
It works nicely on my project, you can release the fix ;)
