### ISSUE TITLE
Popper on iOS devices

### ISSUE THREAD

**Issue by Johann-S** [FezVrasta/popper.js#210]
Hi @FezVrasta just a question

I would like to know if you are compatible with iOS ? 
Because my tests failed on iOS (see https://travis-ci.org/twbs/bootstrap/jobs/222423221#L411) 

More precisely : 
Browser  : Safari
Device : iPhone Simulator
iOS Version : 9.3
Plateform : iOS

**Comment by FezVrasta** [comment]
I never ran my test suite on iOS, there's a ticket open for it (#138).

If you want to send a PR to enable testing on iOS we'll know how many tests pass and I'll be able to work on the failing ones.

I just opened popper.js.org on my iPhone and the examples on the page work just fine tho.

**Comment by FezVrasta** [comment]
I just ran the tests on iOS 7 simulator and this is the result:

![image](https://cloud.githubusercontent.com/assets/5382443/25066870/df95c7d0-2232-11e7-91de-a1c8cdc7b955.png)

I'm quite sure the 2 failing tests are failing because the test assumes a larger browser window.

**Comment by FezVrasta** [comment]
Update: Looks like some tests are failing because they make use of `vh`, which on iOS isn't so reliable (because it has the wrong value when the address bar is visible). ¯\_(ツ)_/¯ 

Popper.js seems to work fine tho.

**Comment by FezVrasta** [comment]
I'm closing this in favor of #138
