### ISSUE TITLE
[IE10] Wrong viewport boundaries computation

### ISSUE THREAD

**Issue by atomiks** [FezVrasta/popper.js#211]
I believe this is an issue on Popper's end, and although IE10 doesn't really matter anymore (works fine on IE11), just checking:

----------------

### Demo

https://codepen.io/FezVrasta/full/QvyNvY/

### Steps to reproduce the problem

Scroll down on IE10

### What is the expected behavior?

Tooltips should be positioned correctly, sticking to the element

### What went wrong?

Tooltip instead scrolls with the scrollbar

**Comment by FezVrasta** [comment]
I need a test case based on the template provided in the issues. Or even better, a PR that introduces a failing test for your problem.

**Comment by atomiks** [comment]
I'll test the previous popper version with the new standalone tippy

**Comment by FezVrasta** [comment]
I would suggest to add an automated test suite to Tippy if you want to avoid lot of problems in future. Automated tests are invaluable.

**Comment by atomiks** [comment]
The old version works with tippy.standalone, so...

**Comment by FezVrasta** [comment]
Ok then please provide the test case as required and I'll take a look

**Comment by atomiks** [comment]
I'll definitely set up tests tomorrow for the library

What kind of test case do you need? I haven't written one in this type of scenario before

**Comment by FezVrasta** [comment]
It's enough to edit the bug report template:
https://github.com/FezVrasta/popper.js/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by FezVrasta** [comment]
Any updates on this @atomiks ?

**Comment by atomiks** [comment]
Sorry, not sure what you mean by edit the report template. Edit it with the test case? Can you give an example of what you need?

**Comment by FezVrasta** [comment]
Take this:
https://codepen.io/FezVrasta/pen/wGqJEz

Update the code to make it reproduce the problem (particular markup, css, anything?)

I need a way to see the bug just opening the codepen without having to debug 3rd party code.

**Comment by atomiks** [comment]
Ah okay, that makes it clear. I'll try to make a failing test

**Comment by atomiks** [comment]
Okay here we go: https://codepen.io/anon/pen/QvbejQ

On IE10, it will scroll down with it rather than stick to the element.

Gif: https://i.gyazo.com/77cb6a3c82b7535f079d9fedd5895c94.mp4

**Comment by FezVrasta** [comment]
How's that on Chrome I see the tooltip above the button? Is it expected? 😕

**Comment by atomiks** [comment]
Updated

**Comment by FezVrasta** [comment]
Ok, so... we have problems with margins applied to `html`, nice... The tests we have seems useless in this case 😓 And we have a `scrollTop` problem in IE10... 

Thank you

**Comment by FezVrasta** [comment]
This (#217) should fix the problems with the positioning on all browsers.

Tomorrow I'll take a look at the IE10 specific bug.

**Comment by atomiks** [comment]
Any idea when this will be fixed?

**Comment by FezVrasta** [comment]
I think within today, but I have other things scheduled that needs my attention.

**Comment by FezVrasta** [comment]
It's trickier than I thought, I added a failing test but I can't find a way to fix the problem without breaking other stuff.

**Comment by atomiks** [comment]
Tippy seems to work in IE10 properly now with 1.9.1, has it been fixed?

**Comment by atomiks** [comment]
Closing this because the codepen and Tippy work in IE10 now, guess you fixed it somehow...
