### ISSUE TITLE
Examples are not working on popper.js.org

### ISSUE THREAD

**Issue by sammkj** [FezVrasta/popper.js#216]
### Screenshot

![image](https://cloud.githubusercontent.com/assets/9153498/25098643/58de5c66-2377-11e7-8e8b-45827ed55b64.png)

### Steps to reproduce the problem

1.  Go to https://popper.js.org
2.  ???
3.  Check console log.

### What is the expected behavior?

To see some cool Popper demos

### What went wrong?

Demos are not working.

Tested on Chrome v57, Firefox v52

**Comment by FezVrasta** [comment]
Thank you, I fixed it in cee39b0000d334ceb373e8cd937ed2bea2bc960a

**Comment by sammkj** [comment]
Is the fix published? I'm still seeing the same errors

**Comment by FezVrasta** [comment]
You probably have to clean the cache (or let it expire).

**Comment by sammkj** [comment]
You're right! Checking it out now. Thank you!
