### ISSUE TITLE
popper alignment

### ISSUE THREAD

**Issue by Webarkitekt** [FezVrasta/popper.js#22]
It would be cool to be able to align the popper along one of the corner of the trigger (top-left, top-right, bottom-left, bottom-right).
This is an example case : 
![image](https://cloud.githubusercontent.com/assets/1436385/14468188/e319d836-00de-11e6-9dd0-08b3488a53c1.png)

The trigger is the arrow.

**Comment by FezVrasta** [comment]
have you tried with `bottom-start` ?

**Comment by Webarkitekt** [comment]
top-end as placement option ?

**Comment by FezVrasta** [comment]
yes

http://popper.js.org/#example4

**Comment by Webarkitekt** [comment]
Ok thanks ;)
