### ISSUE TITLE
Placement option for both popper and target element?

### ISSUE THREAD

**Issue by shmax** [FezVrasta/popper.js#226]
Hi guys, I'm considering migrating my project to Popper from Tether (because Popper doesn't change the DOM the way Tether does, which has been causing me problems), but it doesn't seem to provide some of the basic functionality that Tether (and jqueryui's position plugin) does, which is to allow for alignment information for both the source and the target elements.

Let's say, for example, that I want my source element's top left corner to meet the bottom right corner of the target. It's easy with Tether:

http://jsfiddle.net/nngLr41a/25/

With popper, it doesn't seem possible:
https://codepen.io/shmax71/pen/pPbadO

With Tether (and jqueryui), there are 81 different arrangement possibilities between the two operands, but with Popper there are only ~~9~~ 12.

Do I have that right? Or am I missing something in the documentation?

Thanks for your time.

**Comment by FezVrasta** [comment]
You may use the offset modifier providing a value of `100%p`.

I'm from my smartphone now and I'm not able to give you a working example. I'll follow up tomorrow morning.

**Comment by shmax** [comment]
But that's not really the same thing at all, is it? Yes, the end result is the same with these particular conditions, but that's not really addressing the spirit of the thing. With your approach I would have to manually twiddle the offset every time I wanted to change the height of one of my operands, but with the other libraries it's not necessary (though they support offsets as well).

**Comment by shmax** [comment]
Hmm, I had another look at your offset documentation--I didn't notice that it supports percentage offsets to both the element and the target. I'll await your sample, thanks.

**Comment by FezVrasta** [comment]
That's it:
https://codepen.io/FezVrasta/pen/XRKPOY

**Comment by shmax** [comment]
Thanks, that's helpful. I'll work with this a bit and see if I can achieve the same kind of effects I was getting with Tether. Closing for now...

**Comment by shmax** [comment]
One more thing: how would I add a little constant spacing between the two shapes? With Tether, it looks like this:

http://jsfiddle.net/nngLr41a/26/

**Comment by FezVrasta** [comment]
Offset modifier can take x and y offsets, use them

**Comment by shmax** [comment]
Right, but according to the documentation:

```
It accepts the following units:

unitless, interpreted as pixels
% or %r, percentage relative to the length of the reference element
%p, percentage relative to the length of the popper element
vw, CSS viewport width unit
vh, CSS viewport height unit
```

Whereas in my use case what I would need is a combination of the offset percentage AND a pixel amount, which doesn't seem to be supported. Do I have that right?

**Comment by FezVrasta** [comment]
You can define a combination of measurements. It's written in the documentation

**Comment by shmax** [comment]
Is it? Can you direct me to the section you're talking about? I don't see anything in there about a "combination of measurements". No arrays, no compound strings, etc.  What exactly is your suggestion?

**Comment by FezVrasta** [comment]
> You can provide a single value (as Number or String), or a pair of values as String divided by one white space.
>
> Valid examples are:
>
> offset: 10
> offset: ‘10%’
> offset: ‘10 10’
> offset: ‘10% 10’

**Comment by shmax** [comment]
Look at my Tether example again:

http://jsfiddle.net/nngLr41a/26/

It's aligned such that the two corners are touching, and then beyond that, I've added a constant pixel offset of 20px. This is something that comes in useful for tooltip widgets that go beyond the most basic vanilla alignment scenarios. The two values you are talking about would be the vertical and horizontal offsets, which is fine, but it still doesn't allow for the kind of alignment scenario I'm demonstrating with Tether (and jqueryui). Using your percentage offset model, I would need to ALSO add a constant pixel offset. It's apparently not possible with Popper, but it would, in theory, look something like this:

```
new Popper(ref, pop, {
  placement: 'left',
  modifiers: {
    offset: { offset: '100%r20px' }
  }
});
```

But really that only takes care of one axis.  In my Tether example, I'm offsetting on both axes. 

With Popper, even with my imaginary syntax it starts to get a little awkward, as I have to provide a completely different offset for the horizontal component:

```
new Popper(ref, pop, {
  placement: 'left',
  modifiers: {
    offset: { offset: '100%r20px 20px' }
  }
});
```

Consider again how easy this is with Tether (and jqueryui):
```js
var tether = new Tether({
	element: $('#popup'),
  	target: $('#target'),
  	attachment: 'top left',
  	targetAttachment: 'bottom right',
    offset: '-20px -20px'
});
```

**Comment by shmax** [comment]
By the way, it's not clear to me why '100%r' is the correct offset value in your original example. I would expect 100% of the reference value to put the popper element floating off in space below the reference element. 50% puts the popper's left middle right at the reference element's lower right. which *is* expected, but a value of 100% or greater seems to cap the popper's position such that it's top won't go below the reference element's bottom, which feels like a bug to me:

https://codepen.io/shmax71/pen/WjxqPV

 Any thoughts?

**Comment by FezVrasta** [comment]
I wonder why you can't simply apply a padding with CSS.

By the way, you can define a custom modifier and apply any kind of offset you desire.

**Comment by shmax** [comment]
> I wonder why you can't simply apply a padding with CSS.

I assume you mean 'margin'. I'll experiment with it a bit and get back to you, thanks...

> By the way, you can define a custom modifier and apply any kind of offset you desire.

Well, yes, but the reason I use a library is to minimize the amount of custom code I have to write.

**Comment by FezVrasta** [comment]
You have to understand that the goal of this library is to outsidel provide a solid foundation to position your elements. It can't support all the possible use cases out of the box but it does provide a powerful way to integrate additional features writing a minimal amount of code.

This said, if you think your use case could be shared by others, you may write a modifier to achieve what you need and publish it on npm.
Doing so other users will be able to add your modifier to Popper and take advantage of the features it provides.

**Comment by shmax** [comment]
> You have to understand that the goal of this library is to outsidel provide a solid foundation to position your elements. 

It doesn't, though. :( Even though it's new and shiny it doesn't provide the same foundational basics that jqueryui and Tether do.

> It can't support all the possible use cases out of the box but it does provide a powerful way to integrate additional features writing a minimal amount of code.

Well, no, it apparently requires me to write plugins just to bring it up to the same basic level as Tether and jquerui, which seem to be your "competition".

> It can't support all the possible use cases out of the box but it does provide a powerful way to integrate additional features writing a minimal amount of code.

No one's asking for all the possible use cases, but the basics that the two other major libraries provide would be lovely.

> it does provide a powerful way to integrate additional features writing a minimal amount of code.

But I don't have to write any code if I use one of the other libraries. :(

Sorry, I know I probably sound a bit antagonistic, but I don't have time at the moment to get involved with bug fixing or writing add-ons for another project; I need something that just works.

I don't feel that my use case is unusual or exotic or unreasonable--I would expect a library such as yours to handle it well out of the box, especially when it has so many other nice features and is designed to be a good foundation for things like tooltips.

At this point jqueryui is looking like my best option--it's been around longer, and is the result of the collaboration of hundreds of talented developers. This is not to slam Popper, you've done a great job with it!

Thanks for your time.

**Comment by FezVrasta** [comment]
You are welcome. I think you miss what actually this library does since you are still comparing it to libraries that support just very basic situations. Popper.js aims to position the elements no matter where they are in the DOM. Tether and others can work only if the popper is a direct child of the body element.

At the moment I'm replying from my smartphone because I'm not working (I'm with my girlfriend on the sofa) and I'm the only maintainer of this project. But I'll be happy to code for you a codepen that shows you what you need to achieve with just few lines of code tomorrow morning as soon I get on my PC.

**Comment by FezVrasta** [comment]
Sorry I didn't read your concern about a possible bug.
That behaviour is the result of the keepTogether modifier. You can disable it to allow the popper to detach from the reference on its main axis.

**Comment by shmax** [comment]
> Tether and others can work only if the popper is a direct child of the body element.

You can't mean that. Both libraries do just fine with any amount of nesting:

http://jsfiddle.net/nngLr41a/27/

It's really why they exist in the first place--their main purpose is to walk the ancestral DOM tree and sort out all the `position: absolute` and `position: relative` and god-knows-what-else sort of situations and do the positioning you want, anyway.

I'll await your further samples with interest, thanks.

**Comment by FezVrasta** [comment]
Tether moves the popper to make it live as direct child of the body, you can check it for yourself. I can't talk for the other plugin you mention because I never used it, but I'm quite sure it does the same.

**Comment by shmax** [comment]
Oh, and just to bring it full circle, I have two reasons to want to move away from Tether:

1. It reparents the 'popper'. While it doesn't require it to be a direct child of body, it does move it there for the purpose of solving z-index sorting issues (neither Popper or JqueryUi take on the problem of z-index sorting), but this 'feature' of theirs causes all sorts of subtle issues related to the fact that they compute the height of the popper while it's still in its original home, which can differ from the computed height once it's
been moved to the tail of body. Groan.

2. It has a bug with collision detection and offset. If a popper has an offset applied, and it hits the edge of the window and needs to flip around, it does not invert the offset amount, which causes it to appear in the wrong position.

I know your library doesn't have the first problem, not sure about the second.

**Comment by shmax** [comment]
> Tether moves the popper to make it live as direct child of the body, you can check it for yourself. I can't talk for the other plugin you mention because I never used it, but I'm quite sure it does the same.

Yes, it moves it to body after the fact (which is not the same as saying that it requires your popper to be a direct child of body--it may or may not--it moves it there for z-sorting reasons). jqueryui does not do any reparenting.

**Comment by FezVrasta** [comment]
No, it moves it there because the position computation is much easier in this case.

The z-index reason is a no sense, z-index is very delicate and specific problem that must be handled carefully case by case.

**Comment by shmax** [comment]
Well, rather than get in an argument over it let's make it easy and remove Tether from this part of the discussion, then. jqueryui's position add-on most definitely does not do any re-parenting (which is why I'm leaning towards using it).

**Comment by FezVrasta** [comment]
Please read my edit.

**Comment by FezVrasta** [comment]
Also, I think you edited your previous JSfiddle because I can't see the same result I was seeing from my smartphone?

**Comment by FezVrasta** [comment]
I remember it was something like this maybe?
https://codepen.io/FezVrasta/pen/bWeXaE

**Comment by shmax** [comment]
Sorry, was on the phone with the bank. I looked at your jqueryui sample, but it wasn't clear to me what you were trying to prove. Here's one of my own that shows some sem-complex nesting:

https://codepen.io/shmax71/pen/ZKOgvJ/

Everything looks fine to me, and there is no re-parenting.

**Comment by shmax** [comment]
```
new Popper(ref, pop, {
  modifiers: {
    keepTogether: { enabled: false },
    offset: { offset: '100%' },
    addMargin: {
      order: 890,
      enabled: true,
      function: function(data) {
        data.offsets.popper.top += 10;
        data.offsets.popper.left += 10;
        return data;
      }
    }
  }
});
```

Sure, that works, but basically you're telling me to just "write your own code", and if I wanted to do that then why am I using a library? Compare that to the jqueryui solution: 

```
$( "#pop" ).position({
  my: 'left top',
  at: 'right+20px bottom+20px',
  of: '#ref'
});
```

Can you guess which option looks better to me?

**Comment by shmax** [comment]
Oh, regarding using margins:

On this point, your library has a different behavior: it respects the margins when doing the alignment, whereas jquery ignores them:

jqueryui:
https://codepen.io/shmax71/pen/ZKOgvJ/

Popper:
https://codepen.io/shmax71/pen/WjxqPV

Which is interesting. I have to say I prefer the idea of controlling the offset via CSS much better than using configurable offsets, so I'll give you points on this one.

**Comment by FezVrasta** [comment]
Sorry, it's midnight here, a bit tired 🙃

https://codepen.io/FezVrasta/pen/qmNeVM

scroll the purple container and you'll notice that the popper doesn't follow the reference element.

I'm not saying my library is perfect, but it handles (almost) all the positioning issues that can be encountered. What you are asking is just sugar on top, which, at the moment, can be achieved writing few lines of code (or using some CSS to make it easier?).

jQuery UI (with only the position module) is a 8KB library, with the jQuery dependency (87KB). With almost ~100KB you get some basic positioning functionality that breaks in any medium to complex case. (but also some basic case like a simple scrolling element).
jQuery is sponsored by big companies like Microsoft (that, nonetheless, uses Popper.js in its WebClipper project), while Popper.js is supported by... umh.. me?

This is the first time someone asks for this very specific behavior, and I provided a solution that requires you to simply disable a built-in modifier, define an offset, and add a line of CSS.

Do you want better support for it? I'm super happy to review PRs and give you any information you need to write a modifier to add this behavior.

My point is, with Popper.js, you have a strong foundation you can use to write anything you need without worrying about all the mess that happens under the hood to give you the initial basic positions. I'm happy to see new contributors willing to add new features to the library, both via PRs or via external modifiers.

**Comment by FezVrasta** [comment]
I forgot to add that, while you are here talking about these missing functionalities, I released a version to fix a problem that affected your use case.
Tether developers have abandoned their library and point here (I don't blame them, it's hard to maintain such libraries).
jQuery doesn't usually give a fuck about bug reports (I have some that have been open for more than 3 years without a solution).

**Comment by shmax** [comment]
> scroll the purple container and you'll notice that the popper doesn't follow the reference element.

Ah, okay, so now we're talking about binding during scrolling (and presumable animations?). Great, that's a nice feature, and I could certainly make use of it.

>jQuery UI (with only the position module) is a 8KB library, with the jQuery dependency (87KB). With almost ~100KB 

Ah, not in my case. I'm working in an Ember app, so we already have jquery, anyway. It's not necessary to include jqueryui to use the position plugin. It's standalone, and weights in at around 2.7KB, minified. popper.min.js seems to be around 6.4KB.

> you get some basic positioning functionality that breaks in any medium to complex case. (but also some basic case like a simple scrolling element).

I haven't seen any evidence of that. You may have a point about the scrolling, though. 

> jQuery is sponsored by big companies like Microsoft (that, nonetheless, uses Popper.js in its WebClipper project), while Popper.js is supported by... umh.. me?

Is that supposed to be an argument for or against using it? And I wasn't aware that Microsoft was a sponsor of jquery. Not sure what you mean by that.

> This is the first time someone asks for this very specific behavior, and I provided a solution that requires you to simply disable a built-in modifier, define an offset, and add a line of CSS.

Your "simply" requires 10 more lines of code and knowledge of around half a dozen API properties and concepts. Sure, it works but it's not exactly intuitive or easy to use.  You and I had to argue about it for half a day to arrive at some semblance of a solution.

> Do you want better support for it? I'm super happy to review PRs and give you any information you need to write a modifier to add this behavior.

What, you mean to make an API similar to jqueryui and Tether? I'll think about it--I may do that. I was sort of sold on using jqueryui, but I do like the way your library handles margins and scrolling/animation binding. If it had a friendly API similar to Tether/jqueryui I think you would have a clear winner. I'll think it over.

**Comment by shmax** [comment]
> I forgot to add that, while you are here talking about these missing functionalities, I released a version to fix a problem that affected your use case.

Did you? I see a commit from 6 hours ago, but it has something to do with documentation?

> Tether developers have abandoned their library and point here (I don't blame them, it's hard to maintain such libraries).

True! I found that very frustrating, and if they had bothered to make that clear somewhere I wouldn't have used their library. I am super pissed about that.

> jQuery doesn't usually give a fuck about bug reports (I have some that have been open for more than 3 years without a solution).

I can't speak for jquery, but jqueryui has a very active and agressive devb cycle. I opened a bug report myself last night and they've already closed it. Amazingly, the position plugin only has one open issue:

https://bugs.jqueryui.com/report/10?P=position

But I totally know what you mean, in general. It breaks my heart when maintainers lose interest in their own projects and can't be arsed to hand them over or come up with an exit strategy.

**Comment by FezVrasta** [comment]
You should run my whole test suite against jQuery UI Position to see how many edge cases aren't covered by it. Right now I'm really tired and I haven't a way to provide you additional pens with broken cases.

About the point of Microsoft, feel free to use whatever fits your needs. I'm maintaining this project using my free time because I think it can be valuable to many. If you think other projects are better you should use them or, if you think it makes sense, invest time in Popper.js and help improving it.

About the fact that it took so much to reach to a conclusion is because it's Sunday and I replied to you with my smartphone almost all the time. I'm sorry for that.

I don't I'd like to see the same placement configuration provided by Tether and jQuery because most of the times it's really overkill.

But I think it would be valuable to add a way to perform basic operations in the offset modifier using the available units. Such as `10% + 5px`.

**Comment by shmax** [comment]
> But I think it would be valuable to add a way to perform basic operations in the offset modifier using the available units. Such as 10% + 5px.

That sounds good to me. 👍

**Comment by FezVrasta** [comment]
1.8.3 was released after I replied to you and noticed the bug while I was playing with the pen I provided.

**Comment by shmax** [comment]
Ah, very nice.

**Comment by shmax** [comment]
Anyway, thanks for all the feedback. Good night, and I'll probably be in touch about some API improvements along the lines of what you suggested.

**Comment by FezVrasta** [comment]
Thank you. Check out ember-popper, you may find it useful.

**Comment by shmax** [comment]
Hah, it's got the same problems that ember-tether did (namely, it assumes that your component is not tagless). Thank you, though.

**Comment by FezVrasta** [comment]
Maybe open an issue to let them know, they could fix it.

**Comment by shmax** [comment]
Naw, there's not enough code there to warrant getting involved. I've already got all the foundational work done in my own component--all I really need to do is swap out Tether for something else.

**Comment by FezVrasta** [comment]
Open source it then 😋

**Comment by shmax** [comment]
I'm trying, but I have to convince my employer, first.

**Comment by FezVrasta** [comment]
>> But I think it would be valuable to add a way to perform basic operations in the offset modifier using the available units. Such as 10% + 5px.
>
> That sounds good to me. 👍

https://github.com/FezVrasta/popper.js/pull/229 implements this feature.

**Comment by FezVrasta** [comment]
@jackson-sandland 	I already answered your question on the other issue, please don't repost questions/concerns everywhere.

Thank you.
