### ISSUE TITLE
Responsive threshold switches to modal presentation

### ISSUE THREAD

**Issue by rosskevin** [FezVrasta/popper.js#23]
**Scenario**
 [Material design date/time picker](https://www.google.com/design/spec/components/pickers.html#pickers-date-pickers)

**Idea**
Allow responsive configuration so that when size dips below a threshold such as a mobile (e.g. `md` from bootstrap nomenclature), or switching from ipad landscape to portrait ([example drawer does something similar](http://rosskevin.github.io/bootstrap-material-design/examples/dashboard/)), turn the popper into a modal with overlay.

**Comment by FezVrasta** [comment]
You could add a modifier like:

````
var switchToModal = function(data) {
  var width = Math.max( body.scrollWidth, body.offsetWidth, html.clientWidth, html.scrollWidth, html.offsetWidth );
  if (width < 1000) {
    this._popper.classList.add('popper--modal');
  } else {
    this._popper.classList.remove('popper--modal');
  }
  return data;
}

// usage
new Popper(a, b, { modifiers: [ 'shift', 'offset', 'preventOverflow', 'keepTogether', 'arrow', 'flip', 'applyStyle', switchToModal ] });
```

Could it work?

**Comment by rosskevin** [comment]
I'll try this and let you know.  Since there are so many other things involved, it may need to stay a modifier i.e. I'd want a backdrop when it switches, and that would have to click/hide it etc.

**Comment by FezVrasta** [comment]
Seems like something very specific which can be easily addressed with a custom modifier. Closing.
