### ISSUE TITLE
Add support for poppers child of their (positioned) reference element

### ISSUE THREAD

**Issue by kybishop** [FezVrasta/popper.js#233]
### CodePen demo

http://codepen.io/kybishop/pen/zwKmyX

### Steps to reproduce the problem

1.  Add `position: relative` to any of the popper's parent elements
2. Note how the popper's offsets are greater than expected

### What is the expected behavior?

The popper adjusts its position relative to the relatively positioned parent.

### What went wrong?

The popper adjusts itself as if it were positioned on the document body

**Comment by FezVrasta** [comment]
Am I missing something or your popper is child I of the reference element?

**Comment by kybishop** [comment]
@FezVrasta re child of the reference element: that is correct! The use case is for single page apps, where child components are auto-destroyed if their parent is destroyed. Otherwise we have to move the popper component's element to the document body; work it would be awesome to avoid.

With child support, we can keep the popper in place, taking advantage of w/e rendering engine is used

**Comment by FezVrasta** [comment]
I think I'm a bit too used to React and it's been a while since the last time I used Ember but... Can't you render two adjacent elements?

In React we have:

```
<Manager>
  <Reference />
  <Popper />
</Manager>
```

**Comment by kybishop** [comment]
Assuming `<Manager>` is also just an element, the same problem occurs if `<Manager>` has `position: relative`, or if any of its parents do:

```
<div>
  <div style="position: relative">
    <some-container>
      <div class="ref"></div>
      <div class="popper"></div>
    </some-container>
  </div
</div>
```

**Comment by FezVrasta** [comment]
Why you say so?
https://codepen.io/FezVrasta/pen/vmymYw

**Comment by kybishop** [comment]
@FezVrasta very interesting. I'm seeing the issue in a real-world app, but I guess I haven't boild down the problem as much as I thought.

I will come up with a working example where a parent far up the stack borks the popper's position.
