### ISSUE TITLE
Position calculation broken in modals

### ISSUE THREAD

**Issue by donnysim** [FezVrasta/popper.js#234]
So I just ran yarn upgrade and the popperjs package got updated from 1.0.8 to 1.8.4 and the dropdowns now are completely broken when in modal when the document body is scrolled down.

This is how it looks on 1.0.8
http://i.imgur.com/Otz9D75.png

This is how it looks on 1.8.4
http://i.imgur.com/lLlfxJg.png

the dropdown is positioned on the body. If I make the dropdown not on the body but in the parent element, then it breaks event more by going sideways off screen regardless of being in modal or not. I can try and make fiddle for it but it'll only be on the weekend, sorry.

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
