### ISSUE TITLE
Update TypeScript definitions for V1 API

### ISSUE THREAD

**Issue by mattrcarter** [FezVrasta/popper.js#239]
The latest TypeScript definitions available on https://github.com/DefinitelyTyped/DefinitelyTyped are for popper.js v0.4.x. Would you be willing to update the definitions to reflect the breaking changes in the v1 API?

### Steps to reproduce the problem

1. Install popper.js latest version (v1.8.4 at time of this issue)
2. Install latest TypeScript definitions from https://github.com/DefinitelyTyped/DefinitelyTyped (for v0.4.x at time of this issue)
3. Add a custom modifier as described here: https://github.com/FezVrasta/popper.js/issues/62 

### What is the expected behavior?

Custom modifiers would be definable.

### What went wrong?

The wrong types for modifiers in the TS definitions prevent compilation of TypeScript code.

### Any other comments?

If you'd like help updating the definitions let me know and I'll see what I can do to help out.

**Comment by FezVrasta** [comment]
I never used TypeScript. The whole API is described in the documentation. I use JSDoc to describe the types so maybe there's a tool to automatically generate them from jsdoc?

**Comment by FezVrasta** [comment]
I tried https://www.npmjs.com/package/tsd-jsdoc but it throws a lot of warnings because of invalid types like `Object` `Array`, `HTMLElement`, `Boolean`, `String`...

**Comment by FezVrasta** [comment]
I'm going to close this since there's already a PR to update the definitions in the DefinitelyTyped repo.
