### ISSUE TITLE
Enhancement: Need APIs and callbacks regarding current state

### ISSUE THREAD

**Issue by rosskevin** [FezVrasta/popper.js#24]
Scenario: datepicker

I need to know if the state of the popper, and perhaps gather data from it when hidden and before being destroyed.  I could track `showing` myself, but it would be nice to have.  These could be callbacks or events, either way.

Ideally, I think these would be good additions:
- `onHidden`
- `onShow`
- `onDestroy`

`isShowing` is nice to have but with the above, I could easily track this myself.

**Comment by FezVrasta** [comment]
`isShowing` is not something provided by Popper.js.

This library takes care only of the position of your element, it doesn't show/hide elements.
