### ISSUE TITLE
[Safari] Doesn't init when ran in CodePen

### ISSUE THREAD

**Issue by emrosenf** [FezVrasta/popper.js#247]
Popper does not seem to work correctly when the reference is absolutely positioned. Is this known behavior?

### CodePen demo

http://codepen.io/anon/pen/ZKyEgM

### Steps to reproduce the problem

1.  Reference element CSS is position: absolute

### What is the expected behavior?

Popper is positioned near the reference element

### What went wrong?

Popper is positioned as if reference element did not have "position:absolute"

### Any other comments?

Any additional information.

**Comment by FezVrasta** [comment]
This is the result I see, what's wrong with this?

![image](https://cloud.githubusercontent.com/assets/5382443/25612740/142804c6-2f2c-11e7-9812-758e04bc6299.png)

**Comment by emrosenf** [comment]
Update: example works on Chrome and Firefox.

Fails on Safari and mobile Safari:

![screen shot 2017-05-02 at 7 54 53 am](https://cloud.githubusercontent.com/assets/425523/25624325/db08862a-2f0d-11e7-9660-794838524923.png)

**Comment by FezVrasta** [comment]
I'm not sure what's happening in CodePen, but when I open the page in "debug view" and run `new Popper(ref, pop)` in the console, everything works properly 🤔

**Comment by FezVrasta** [comment]
I updated the template, it should work now.

Here your pen fixed:
https://codepen.io/FezVrasta/pen/GmExLp
