### ISSUE TITLE
Overflow: auto issue

### ISSUE THREAD

**Issue by kerf007** [FezVrasta/popper.js#248]
Hello, I'm trying to use popper and when I set for my `div.wrapper` `overflow: auto` the popper takes the wrong position: http://codepen.io/kerf/pen/oWwMxP

Sorry, if I stupid) I'm just starting to use it.

**Comment by FezVrasta** [comment]
Hi, that's because `preventOverflow` by default will keep the popper between its scroll parent boundaries.

http://codepen.io/anon/pen/eWRjry

**Comment by kerf007** [comment]
Thanks!

**Comment by FezVrasta** [comment]
You are welcome
