### ISSUE TITLE
A little confused how to use the Tooltip references

### ISSUE THREAD

**Issue by mykone** [FezVrasta/popper.js#249]
Hello, i'm a little confused how to use the `Tooltip` constructor as it relates to using references.

Whenever I use:
 ```
new Tooltip(positionReference, {
  title: "Hello there",
  placement: "top"
})
``` 

it works well. However, I am trying to set the template, which means I am using all four parameters:
`new Tooltip(reference, options, reference, options)`, but when I use this method, it doesn't create the tooltip and add it to the Dom. I guess maybe I don't know how to use the second reference. Can I get a little help on how to use this? Thanks.

**Comment by FezVrasta** [comment]
Hi, sorry, the documentation seems buggy/broken.

It's simply:

```
new Tooltip(referenceElement, {
  title: ...,
  placement: ...,
  template: ...,
});
```

**Comment by mykone** [comment]
Hi @FezVrasta that's amazing your reply so quickly.. Ok.. I will show the code I am using. I actually did exactly what you wrote, let me paste what I am using and show more about my situation.

This works
```
        const toolTip = new Tooltip(
            positionReferenceElement,
            {
                placement: options.position,
                container: $('body')[0],
                html: true,
                title: content,
                trigger: 'click', //options.trigger || 'hover',
            }
        );
```

this does not work:
```
        const toolTip = new Tooltip(
            positionReferenceElement,
            {
                placement: options.position,
                container: $('body')[0],
                html: true,
                title: content,
                trigger: 'click', //options.trigger || 'hover',
                template: `
                    <div class="tooltip" role=”tooltip”>
                        <div class="tooltip-arrow"></div>
                        <div class="tooltip-inner"></div>
                    </div>
                `
            }
        );
```

**Comment by FezVrasta** [comment]
https://codepen.io/FezVrasta/pen/mmMRyQ

**Comment by mykone** [comment]
Ok. @FezVrasta so it seems like there's a bug in your template parsing routing. If I don't add the .trim() function here's the error I get.

```

tooltip.js:199 Uncaught TypeError: tooltipNode.setAttribute is not a function
    at Tooltip._create (tooltip.js:199)
    at Tooltip._show (tooltip.js:244)
    at tooltip.js:392
```

But when I add the trim() it works fine. Thanks for helping to find the issue.
Your awesome.

**Comment by FezVrasta** [comment]
Yup it doesn't expect any extra space, you may send a PR to automatically `trim` it if you want.

**Comment by mykone** [comment]
Sorry for my ignorance, what's a PR? hehe.

**Comment by FezVrasta** [comment]
https://help.github.com/articles/about-pull-requests/

You fork my code, apply a change and propose it to me, if it's good, I merge the change in my own code.

**Comment by mykone** [comment]
Thanks for the explanation. Now I know PR = Pull Request. Hehe. Silly me.

**Comment by FezVrasta** [comment]
Fixed docs
