### ISSUE TITLE
Hello World - popper text overwrites reference until resize

### ISSUE THREAD

**Issue by rosskevin** [FezVrasta/popper.js#25]
I feel foolish like I'm missing something essential.

[Codepen test case](http://codepen.io/rosskevin/pen/XdERKN?editors=1010)

![generic_popper_overwrites_text](https://cloud.githubusercontent.com/assets/136564/14505848/993d41b0-0180-11e6-90b7-218db209a6b5.png)

```html
<span class="myReference">Hello</span>
```

```javascript
var reference = document.querySelector('.myReference');
new Popper(reference, {content: 'World'}, {placement: 'right'})
```

**Comment by rosskevin** [comment]
Is there a recommended baseline css to use with this for placement?  I'm [threw in the popper.css](http://codepen.io/rosskevin/pen/KzomZV) from the popper.js.org site and it's closer.

**Comment by rosskevin** [comment]
It looks like minimally, if you don't have the following, you'll see this behavior:

```css
.popper {
  position: absolute;
}
```

**Comment by FezVrasta** [comment]
Seems like a problem with the first update, if you then scroll or resize the window, it works properly.

**Comment by Webarkitekt** [comment]
Still no solution about this issue ?

**Comment by FezVrasta** [comment]
I need a free weekend to work on it, still had no time :/

A PR is welcome tho

**Comment by FezVrasta** [comment]
Fixed the problem.

The `position` of the popper element wasn't set before the computations performed by the first `.update()`. Now I set the position before everything else, so we are sure the update works properly.
