### ISSUE TITLE
Popper does not update its position to fit entirely in viewport/document if it is overflowing

### ISSUE THREAD

**Issue by atomiks** [FezVrasta/popper.js#251]
### CodePen demo

https://codepen.io/FezVrasta/pen/QvQQgv

### Steps to reproduce the problem

1. Simply resize the browser window and you'll notice part of the Popper begins to overflow the document edge at the boundaries.

### What is the expected behavior?

That it is fully visible in the viewport with no overflow on a single update (i.e., it fits within the content of the document excluding itself).

### What went wrong?

It overflows.

**Comment by FezVrasta** [comment]
Have you tried with sheduleUpdate?

**Comment by atomiks** [comment]
Well if you change the codepen to use `scheduleUpdate`, the same problem occurs

**Comment by FezVrasta** [comment]
Why are you disabling the event listeners?

**Comment by atomiks** [comment]
Event listeners are disabled when a popper is hidden (in Tippy)

**Comment by FezVrasta** [comment]
Ok, but what I don't get is why you need to update the position of a disabled tooltip?

**Comment by atomiks** [comment]
Well it needs to recalculate the position of the tooltip when it is shown again, if the browser window was resized it will be at the wrong position..

**Comment by FezVrasta** [comment]
I see

**Comment by atomiks** [comment]
Also I should note that it has no trouble positining it correctly when the instance is first created. If you keep the browser window resized and refresh the page, the initial position is correct

**Comment by atomiks** [comment]
I don't think the title change is right -- what I said initially is what I meant.

I think the debounce function prevents it from properly being moved into the viewport?

Even with events enabled, it doesn't shift enough:
https://i.gyazo.com/551a5a563769d233b8fc45d1d4336c7d.mp4

**Comment by FezVrasta** [comment]
Ok that's why I say that the codepens should provide the **minimum** amount of code needed to reproduce the bug.

If the `disbleEventListeners` isn't needed, why it was there? It generates confusion.

**Comment by atomiks** [comment]
Sorry for the confusion! I didn't mean for it to be that way... hope you can sort the problem out

**Comment by atomiks** [comment]
The changes you made works, will this be released as 1.9.4?

**Comment by FezVrasta** [comment]
I have to fix the tests on IE10 before I can merge theb fix

**Comment by FezVrasta** [comment]
1.9.4

**Comment by FezVrasta** [comment]
The problem with this bug is that we can't know the document size, excluded the space it's taking the popper before it gets re-positioned...

Any attempt to fix it is going to obviously break other parts of the code, because we are using the wrong approach.

Any idea to get the document size - the space took by the popper (in case it's stretching the document after a resize)?

**Comment by atomiks** [comment]
Have you gotten any closer to solving this (without breaking 302)?

**Comment by FezVrasta** [comment]
Nope sorry. It's very tricky

**Comment by atomiks** [comment]
Which functions are relevant to this problem?

I can try and see if I can work it out.

**Comment by FezVrasta** [comment]
I think it's just the `getWindowSizes`. It should be able to detect the document width/height excluding the potential overflow caused by the popper element.

**Comment by atomiks** [comment]
Hmm... given that the majority of sites don't have a horizontally-scrolling documentElement, why not just use `window.innerWidth` instead of the document width?

**Comment by FezVrasta** [comment]
I'd like to make the library work in all the edge cases, without any manual setting.

**Comment by atomiks** [comment]
Yeah that's the ideal, but if an option fixes the issue for the majority of cases (at least temporarily until you can work out a full solution), I'd say it's worthwhile to add in.

**Comment by FezVrasta** [comment]
That would break the API, I would have to release a major version just to get rid of an hack we introduced. Not ideal at all.

**Comment by FezVrasta** [comment]
Also, I think the problem can be reproduced on both axis, so that would be a fix only for one of them

**Comment by atomiks** [comment]
How about calculating the document width and height before the popper is added to the DOM?

**Comment by FezVrasta** [comment]
What if the document width changes for a reason unrelated to popper?

**Comment by atomiks** [comment]
Then you'd need to listen to height/width changes of the document/body elements, so that whenever it's updated, Popper can know the new sizes.

**Comment by FezVrasta** [comment]
But if the document width changes because some content is added to the page we don't have any event to know it, and even if we did, we couldn't know what's the size of the document excluded the popper

**Comment by atomiks** [comment]
How about very briefly removing the popper from the document, calculating the document width/height, then appending it back?

**Comment by FezVrasta** [comment]
We should do that for each update loop.. That would be terrible

**Comment by atomiks** [comment]
It does sound quite terrible on paper, but I wonder how severe it would be in general use. And you could have an option to turn it on only when necessary... (so keep the behavior off by default), or maybe there's a way to "batch"/optimize it somehow, who knows.

**Comment by FezVrasta** [comment]
Feel free to experiment with it, if you end up with a good solution I'll be happy to merge it. I just don't want any extra option.

**Comment by kybishop** [comment]
@atomiks here is how I'm getting around this in my own tooltip library: https://github.com/kybishop/ember-attacher/blob/master/addon/components/attach-popover.js#L252

The above line positions the popper in the top left of the screen on creation. We then manually call `update()` when the tooltip will be shown, which correctly positions the element.

**Comment by FezVrasta** [comment]
But how do you handle the window resize?

**Comment by kybishop** [comment]
Assuming the popover is not larger than the window itself, positioning it in the top left of the screen means the window shrinks to fit its content. Since the popper is all the way to the left, the window shouldn't grow any larger than the popper.

**Comment by atomiks** [comment]
The window resize isn't a big a deal as the initial update positioning, so I'll see if that solution works well. Thanks!

**Comment by alexander-morozov** [comment]
I also stuck with the same issue and for me removing html.scrollWidth from getSize method fixes it. Probably something like that https://github.com/FezVrasta/popper.js/commit/1b3a82d77a11ce84d767da0f1ac4982774a64979
should fix it. 

Maybe we can move includeScroll with default `true` as external option?

**Comment by victorting** [comment]
I also stuck with the same issue too. Hoping ace to fixes it. Thanks a lot!

**Comment by FezVrasta** [comment]
1.14.2 includes the fix for this bug

**Comment by jan-wilhelm** [comment]
I've just spent about an hour on this after Google led me to this GitHub issue.
For anybody using Popper with a **`@headlessui/react`** `Transition`, be aware: The Transition component internally handles mounting / unmounting. Due to that, Popper does not seem to be able to calculate the Tranistion's dimensions "up-front" (before the Transition renders). To fix that, make sure to add the following code:

```jsx
<Transition
  beforeEnter={() => popper.forceUpdate?.()}
  // ...
/>
```
this way, you can force Popper to recalculate once the DOM element actually comes into appearance.
