### ISSUE TITLE
What happened with the ES5 Version of popperjs

### ISSUE THREAD

**Issue by janwidmer** [FezVrasta/popper.js#252]
I tried to update to the newest version of popper today. My old version was 1.0.6. In the newest version of popper, the compiled es5 Version of Popper seems to be gone (With Ticket https://github.com/FezVrasta/popper.js/pull/220) and replaced by an umd and an esm build.

When I use the esm version of popperjs in my build, my gulp-uglify breaks.

### CodePen demo
Build Stack issues cannot be showcased on codepen.

### Steps to reproduce the problem

1.  Setup an FE Build Stack with Gulp and Popper.js
2.  Add popper.js (vs.) to your build with the esm version
3.  use gulp-uglify

### What is the expected behavior?
There is a compiled es5 version of popperjs next to the esm / umd / es6 versions

### What went wrong?
The current behaviour is, that popper.js does not get included because of the above problem.

### Any other comments?

**Comment by FezVrasta** [comment]
The old ES5 version is now called UMD (since now both UMD and ESM are transpiled to ES5).

If you want the ES6 version, it's in `/dist/index.js`

**Comment by janwidmer** [comment]
Ah yeah, now it works.. thanks for that blazing fast anwer..
