### ISSUE TITLE
Dist not donwload with bower

### ISSUE THREAD

**Issue by Ginwu** [FezVrasta/popper.js#254]
Hello,

I want to install Popper.js in es5 and version 1.9.1 with bower in my project, and I followed your recommandation with the command:

`bower install popper.js=https://unpkg.com/popper.js --save`

I tried to add a version to the url but can't find any solution here because bower doesn't like version target on url package. So I tried to install it with that command:

`bower install popper.js@1.9.1`

But the "dist/" folder is not present in the bower package donwloaded and I need the es5 version. I think it's because the folder isn't present on the master branch on github. Is that possible to add it?

Thanks for your work and your help!

**Comment by FezVrasta** [comment]
Bower is (almost) deprecated and their own maintainers suggest to move to Yarn.

I opened an issue for you here:
https://github.com/unpkg/unpkg.com/issues/33

I can't do anything else.

**Comment by Ginwu** [comment]
Ok, thank you.

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/popper.js/issues/390
