### ISSUE TITLE
Uncaught TypeError: Cannot read property 'offsetParent' of undefined | Salesforce Lightning framework

### ISSUE THREAD

**Issue by aravindxz** [FezVrasta/popper.js#257]
Hi @FezVrasta ,

I'm getting the following error when using PopperJS in my Salesforce Lightning Component.

> **Uncaught TypeError: Cannot read property 'offsetParent' of undefined**

This issue is not present in PopperJS version 1.0.8 and it's present only in versions above that, starting from 1.5.0 to 1.9.1.
Salesforce Lightning is using [Aura framework](https://github.com/forcedotcom/aura). Also, it should be [Locker Service](https://developer.salesforce.com/blogs/developer-relations/2017/02/lockerservice-lightning-container-third-party-libraries-lightning-components.html) compliant. As per the Aura [Locker Service API documentation](http://documentation.auraframework.org/lockerApiTest/secureElement.app?aura.mode=DEV), I was able to find that offsetParent is undefined!
I'm unable to reproduce the issue in codepen. 

**Is there any workaround to make this work in Salesforce Lightning framework with Locker Service on?**

### Steps to reproduce the problem

1.  Create a Lightning Component in your Salesforce instance.
2.  Add Popper JS (version greater than 1.0.8) in your static resource.
3.  Initialise Popper and you can see the error in the console.

### What went wrong?

Cannot read property 'offsetParent' of undefined.

### Any other comments?

This issue is not present in PopperJS version 1.0.8 and it's present only in versions above that, starting from 1.5.0 to 1.9.1.

**Comment by FezVrasta** [comment]
Hi, I don't have salesforce thus I can't reproduce the problem. You should provide a codepen example to help reproduce the problem.

**Comment by aravindxz** [comment]
Hi @FezVrasta Thanks for taking time to reply. 

Unfortunately this cannot be reproduced in codepen. That's why I gave you details regarding the offsetParent and all.

Oh you don't have Salesforce instance too. Then let me see how I can show you the issue (The thing is this is present in Lightning framework, in which all the external libraries which can be used should be Locker Service compliant.).

**Comment by aravindxz** [comment]
Hi @FezVrasta 

Here you go!
Please visit **https://login.salesforce.com/**
Login as **popperjs@lightning.com**
Password:- **testing1**

_After logging in, just click on the Home tab, an error pops up saying:-_

> Uncaught TypeError: Cannot read property 'offsetParent' of undefined

You might be asked to enter a verification code (It's set by default), I can provide you the code.

Or else, if you can provide me your **email id**, I can create a separate profile for you or another option is that if you provide me your public **IP address**, I can whitelist the same so that you can **skip** the two step authentication!

Thank you!

**Comment by FezVrasta** [comment]
You can contact me at federico.zivolo at gmail dot com

**Comment by aravindxz** [comment]
Thank you for providing the email. I've created a separate user profile for you. 
Hope you've got the email/
Just create the password and login and navigate to the Home tab. You'll get the error pop up (Since I'm initialising the Popper JS version 1.9.2 initially).
Thanks once again!

**Comment by FezVrasta** [comment]
This is the only error I see:

![image](https://cloud.githubusercontent.com/assets/5382443/25947662/b0168b70-3650-11e7-95dc-ed58fe01a0a2.png)

**Comment by FezVrasta** [comment]
I don't know what's happening in that page, but the behavior of `getElementsByClassName` (and also `querySelector`) aren't correct. Seems like they are getting overridden by some other script in the page.

![image](https://cloud.githubusercontent.com/assets/5382443/25947952/ec2a83e0-3651-11e7-805f-933841b0845c.png)

This is how they should look like:
![image](https://cloud.githubusercontent.com/assets/5382443/25947982/00b6992a-3652-11e7-8923-d39c5f3fbc78.png)

**Comment by aravindxz** [comment]
Hi @FezVrasta ,

Thanks a lot for looking into this. 

There are no external scripts running in the background. As I have clearly mentioned in the start of this thread, the plugin should be Locker Service compliant. 
And also, popper JS 1.0.8 version is working fine too.
And it's because of the SecureDOMaccess, you're getting like that.

**_Already, HighCharts, DataTable, D3,Underscore.js, Select2 etc. are made Locker Service compliant so that they could be used in the Salesforce Lightning framework._**

**I'm once again reiterating the fact that, this issue is there for the major release version of PopperJS starting from 1.5.0 to the latest one 1.9.2 .** 

I'm just adding some Locker Service related links below:

[LockerService and Lightning Container Component: Securely Using Third-Party Libraries in Lightning Components](https://developer.salesforce.com/blogs/developer-relations/2017/02/lockerservice-lightning-container-third-party-libraries-lightning-components.html)

[LockerService SecureElement vs HTMLElement Compatibility Table](http://documentation.auraframework.org/lockerApiTest/secureElement.app?aura.mode=DEV)

Also, #INVALID tag is NOT appropriate here, as this IS DEFINITELY A VALID ISSUE. :)

I've also added a working PopperJS (version 1.0.8) in a new tab on the right side of Home tab called "Working PopperJS" for your reference.

Thank you.

**Comment by FezVrasta** [comment]
The internal logic of Popper.js changed, it had different requirements in the previous versions.

If you run `document.querySelector('.reference').offsetParent` you'll notice that it returns `null`, while if you inspect the reference element (thus making it available in the `$0` variable), you get a valid DOM node.

The way the app is overriding the DOM selectors is simply broken, I can't do anything to fix it.

![image](https://cloud.githubusercontent.com/assets/5382443/25949084/a2f1d980-3656-11e7-8fab-3ecaaaa051e5.png)

**Comment by FezVrasta** [comment]
To give more context, this is where it fails exactly:

![image](https://cloud.githubusercontent.com/assets/5382443/25949291/4cbf67fc-3657-11e7-8f36-d5677f0d9e31.png)

Looks like the alternative implementation of the DOM nodes provided by SalesForce doesn't support `firstElementChild` and breaks Popper.js

![image](https://cloud.githubusercontent.com/assets/5382443/25949285/4666f910-3657-11e7-9c77-16b409b53114.png)
