### ISSUE TITLE
Positioning broken when container has overflow-x: hidden

### ISSUE THREAD

**Issue by methyl** [FezVrasta/popper.js#262]
When container of the reference node has `overflow-x: hidden`, the popper element scrolls with the page instead of staying where it's supposed to. What's the possible workaround?

### CodePen demo

https://codepen.io/anon/pen/QvmeqR

**Comment by FezVrasta** [comment]
This is the expected behavior, the scrolling parent is being used as `boundariesElement` by the preventOverflow modifier.

https://codepen.io/FezVrasta/pen/eWrYzL

**Comment by methyl** [comment]
How to prevent this? Should I set boundariesElement in preventOverflow modifier to document.body?

**Comment by FezVrasta** [comment]
It should be `window`, but I think currently there are problems addressing `overflow-*: hidden`. #263

**Comment by methyl** [comment]
👍
