### ISSUE TITLE
Popper with flip: false wrong position

### ISSUE THREAD

**Issue by wojtask9** [FezVrasta/popper.js#265]
### CodePen demo

https://jsfiddle.net/nq3p61n6/2/

### Steps to reproduce the problem

1.  Depending on screen resolution popper height must be higher than space below 'reference element'
2.  Then on fiddle you can see that popper overlaps 'referenced element'
3.  Scroll mouse wheel
4.  popper overlaps 'referenced element' even more

### What is the expected behavior?

Popper should be below 'referenced element'

### What went wrong?

Popper overlaps 'referenced element'

### Any other comments?

With
` modifiers : {
        flip :{
          enabled:false
        }
      }`
popper should be below.
Strange thing happens when we scroll mouse wheel. I can't explain why :)

**Comment by FezVrasta** [comment]
1. `flip` and `preventOverflow` are two different things, one "flips" the `placement`, the other avoids that the popper element overflows from its boundaries.
2. You are not using the provided codepen

**Comment by wojtask9** [comment]
Yeah. Sorry about noise. Of course everything works correct with `preventOverflow`

**Comment by FezVrasta** [comment]
About the weirdness during scroll, #266 should fix it. If you have time please test that version.

**Comment by wojtask9** [comment]
Yes it works correctly. Thank you very much :)
