### ISSUE TITLE
Missing util exports?

### ISSUE THREAD

**Issue by aar0nr** [FezVrasta/popper.js#267]
There are 41 utility functions, yet only 31 are being exported. Are some of these meant to be private?

For example ```getOppositePlacement```, ```clockwise```, ```getOppositeVariation```, etc. are missing from:

https://github.com/FezVrasta/popper.js/blob/v1.9.3/src/popper/utils/index.js

The docs list 31 utility functions, but the ones being exported don't match.

**Comment by FezVrasta** [comment]
The list is manually managed so it's possible that I forgot to add some of the util functions.

Unfortunately these utils change all the time very often while I progress with the development of the library so I don't consider them stable enough to be used by consumers... I'm considering to remove them all together to avoid additional problems

**Comment by FezVrasta** [comment]
Yesterday I removed the Utils documentation from the website, and added a notice in the internal documentation warning about the instability of these utilities.

Unless someone finds a good way to expose them in a stable way, I plan to mark them as private in the next major release.

**Comment by aar0nr** [comment]
Sounds good, thanks for the update. 👍
