### ISSUE TITLE
Use with detached (fabricated) DOM node fails

### ISSUE THREAD

**Issue by rosskevin** [FezVrasta/popper.js#27]
[Codepen test case](http://codepen.io/rosskevin/pen/zqWwmP?editors=1010)

**Scenario:**
I'm fabricating content then want to pop it up.  It appears since this content is not attached to the document that popper fails with:

```
VM2242 popper.js:1017 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'
....
Popper._getBoundaries	@	VM2242 popper.js:481
Popper.update	@	VM2242 popper.js:216
Popper	@	VM2242 popper.js:175
```

1. Is this a bug?
2. If not, what is the recommended way to pop dynamic content?

**Comment by FezVrasta** [comment]
Popper.js needs to know the context of your element to properly position it, I don't think it's a bug.

The easiest way would be to spawn your element in the DOM and then instantly call Popper.js to position it.
Let me know if it can work for you.

**Comment by rosskevin** [comment]
Works, I'm a little concerned it might flash, but I can probably work around that if it does (i.e. off page).

Here's a [working Codepen sample](http://codepen.io/rosskevin/pen/KzomLN?editors=1010)

**Comment by rosskevin** [comment]
I'm thinking about PR'ing a change to the constructor.  Now that I'm using it a bit more, I'd like to get the functionality of the `#parse` function, but with a detached node.  I think it makes sense to allow the node, since the `#parse` creates the nice container with classes and appends.

I'll go ahead, let me know if you think this is a bad idea.  I'm thinking similar to `allowHtml`.  Perhaps `allowHtml` should be `allow` with `html | node`?

**Comment by FezVrasta** [comment]
I don't think it could work for your purpose. If the detached node is larger than the generated container, once you append the node, the container will change its size and the position will probably be wrong.

**Comment by rosskevin** [comment]
This works:
http://codepen.io/rosskevin/pen/PNRjOz?editors=0110

You want me to test with a large element?

**Comment by rosskevin** [comment]
[Large node test case](http://codepen.io/rosskevin/pen/ONvgzR?editors=0110)

**Comment by rosskevin** [comment]
PR available, I think it's a good change.  `#parse` is a handy method and I want all it's goodness applied to my generic content.

**Comment by FezVrasta** [comment]
Closing in favor of the PR
