### ISSUE TITLE
z-index / overflow when in absolute positioned div and popper does not fit

### ISSUE THREAD

**Issue by cnanders** [FezVrasta/popper.js#270]
### CodePen demo

https://codepen.io/cnanders/pen/EmRBxQ

### Steps to reproduce the problem

1.  Create an absolute-positioned div whose height is too short to fit the popper when it is visible
2. Place the `referenceObject` and the `popperNode` inside this div

### What is the expected behavior?

IMO, the default is the expected behavior - the `popperNode` stays confined to the parent that contains the `referenceObject`. However, I'm wondering if it is possible to have it do this: https://codepen.io/cnanders/pen/ZKRgMd where the `popperNode` behaves more like a dropdown with a large z-index and it can flow outside of the parent div? I achieved the behavior in this code pen by placing the popper div outside of the parent "position: absolute" div, but I would like to encapsulate the `referenceObject` + `popperNode` in the absolute positioned parent div for readability.  I imagine there is probably a setting to achieve this but I can't figure it out. 

Thank you so much for this awesome library!

**Comment by FezVrasta** [comment]
You have to change the markup a bit and tweak a Popper.js option.

https://codepen.io/FezVrasta/pen/MmBjKq

**Comment by cnanders** [comment]
Thank you!
