### ISSUE TITLE
Fix documentation - OnCreateCallback and OnUpdateCallback

### ISSUE THREAD

**Issue by bmfteixeira** [FezVrasta/popper.js#271]
Documentation: https://popper.js.org/popper-documentation.html#onCreateCallback

On documentation we can find the callback identified as 'OnCreateCallback' and 'OnUpdateCallback'. But when coding, we need to declare them as `onCreate` and `onUpdate` to work. This is a minor issue that can waste tons of time!

Upgrade documentation with some code examples or, on this specific topics, create a 'How to apply' section

**Comment by FezVrasta** [comment]
The ones you refer to are the type definitions of the two callbacks.

When you read the documentation you find the available options here:
https://popper.js.org/popper-documentation.html#popper

Not discussing on the clarity of the documentation, it could use some improvements, but it's unrelated.
