### ISSUE TITLE
Apply style onCreate

### ISSUE THREAD

**Issue by Johann-S** [FezVrasta/popper.js#273]
Hi @FezVrasta 

I try to apply style to my `pop` element when the `onCreate` event is triggered but it seems my style isn't applied.

See : http://codepen.io/Johann-S/pen/EmeYxj

### Steps to reproduce the problem

1.  Just look 

### What is the expected behavior?

pop background should be blue

### What went wrong?

The style isn't appied

**Comment by FezVrasta** [comment]
Hey, you can't edit `data` on `onUpdate` and `onCreate`. You can do that inside a modifier tho.

**Comment by Johann-S** [comment]
I'm sorry @FezVrasta but I don't understand how to do that 😟 
I updated my CodePen but as you can see I cannot do what I want : http://codepen.io/Johann-S/pen/EmeYxj

**Comment by FezVrasta** [comment]
http://codepen.io/anon/pen/ybxeWZ?editors=1010
