### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by ndmax** [FezVrasta/popper.js#275]
### Steps to reproduce the problem

1.  git clone https://github.com/FezVrasta/popper.js.git ./popper-test-repo
2.  cd popper-test-repo && npm install
3.  npm run build:popper

### What is the expected behavior?

Build process produces "dist" folder with popper.js

### What went wrong?

```
> popper.js@1.9.4 build:popper /path/to/popper-test-repo
> node ./scripts/bundle.js --build=popper

/path/to/popper-test-repo/scripts/bundle.js:1
(function (exports, require, module, __filename, __dirname) { const { exec, execSync } = require('child_process');
                                                                    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3

npm ERR! Linux 4.10.0-20-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:popper"
npm ERR! node v4.7.2
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! popper.js@1.9.4 build:popper: `node ./scripts/bundle.js --build=popper`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the popper.js@1.9.4 build:popper script 'node ./scripts/bundle.js --build=popper'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the popper.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/bundle.js --build=popper
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs popper.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls popper.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /path/to/popper-test-repo/npm-debug.log
```

### Any other comments?

Ubuntu-Gnome 17.04 64-bit
/usr/bin/nodejs --version // v.4.7.2
/usr/bin/npm --version // 3.5.2
[npm-debug.log](https://github.com/FezVrasta/popper.js/files/1008582/npm-debug.txt)

**Comment by FezVrasta** [comment]
Your node version is quite outdated, try with a newer one.

**Comment by ndmax** [comment]
Thanks @FezVrasta that fixed it (and a few other things in my build pipeline).

I'm not sure why Ubuntu 17.04 ships with such an [old version of nodejs](http://packages.ubuntu.com/zesty/nodejs).  Anyway, I updated to 7.X and all is well.

**Comment by FredBesterwitch** [comment]
Getting this error again

VM2444:4 Uncaught SyntaxError: Unexpected token export
    at eval (<anonymous>)
    at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:9)
    at Object.../../../../script-loader/index.js!../../../../popper.js/dist/popper.min.js (popper.min.js?6c59:1)
    at __webpack_require__ (bootstrap 878fda2ac15b165d6cee:54)
    at Object.2 (scripts.bundle.js:66)
    at __webpack_require__ (bootstrap 878fda2ac15b165d6cee:54)
    at webpackJsonpCallback (bootstrap 878fda2ac15b165d6cee:25)
    at scripts.bundle.js:1


@angular/cli: 1.3.0
node: 6.10.0
os: win32 x64
@angular/animations: 4.3.4
@angular/common: 4.3.4
@angular/compiler: 4.3.4
@angular/compiler-cli: 4.3.4
@angular/core: 4.3.4
@angular/forms: 4.3.4
@angular/http: 4.3.4
@angular/platform-browser: 4.3.4
@angular/platform-browser-dynamic: 4.3.4
@angular/platform-server: 4.3.4
@angular/router: 4.3.4
@angular/cli: 1.3.0

**Comment by alaaelsm** [comment]
I am getting the same as well. 
I am  using popper v1.11.0

**Comment by FezVrasta** [comment]
What do you expect me to say? Have you done what I said is needed to fix the problem?

Really guys, use your brain

**Comment by alaaelsm** [comment]
I was using it as part of bootstrap@4 beta dependencies, so this reference helps for me 
https://stackoverflow.com/questions/45646101/bootstrap4-dependency-popperjs-throws-error-on-angular
