### ISSUE TITLE
Arrow is off by 0.5px (1px rendered) when popper is an odd number of pixels wide

### ISSUE THREAD

**Issue by atomiks** [FezVrasta/popper.js#277]
### CodePen demo

https://codepen.io/anon/pen/eWPMRd

### Steps to reproduce the problem

1.  Closely look at the arrow
2.  Notice when inspecting the element it is 43.5px left

### What is the expected behavior?

The arrow should be 43px left not 43.5px

### Any other comments?

Demonstration:

![Image](https://i.gyazo.com/7f6d47855cb55bb595a8ed9c38cfa93b.png)

Can you simply apply Math.floor() to the positioning of the arrow to round it down?

I'm on a retina display so I think it renders things differently, is this reproducible on a low DPI screen?

**Comment by FezVrasta** [comment]
I don't have any low DPI screen to reproduce, I'll check it out ASAP to understand what's happening.

**Comment by atomiks** [comment]
The codepen automatically used the latest unpkg version 1.9.6 and it's been fixed. Works fine for both even and odd number of pixels now.

**Comment by atomiks** [comment]
Sadly there's still an issue... if it's vertical it's not correct.

However it's an easy fix:

```javascript 
data.offsets.arrow[side] = isVertical ? Math.round(sideValue) : Math.floor(sideValue);
```

**Comment by FezVrasta** [comment]
Why `round` in one case and `floor` in the other? Wouldn't make sense to use `ceil` and `floor`?

**Comment by atomiks** [comment]
I suppose... it's usually `x.5` so it rounds up to the next integer anyway?

Are there tests for this so you can calculate the midpoint of the reference and test if the arrow is properly positioned? That way it doesn't have to be guessing by eye.

**Comment by FezVrasta** [comment]
I don't have such kind of tests ATM, if you are interested in this I'd love a PR to introduce them.

**Comment by atomiks** [comment]
It seems it's not consistent. Sometimes rounding down is better, other times rounding up is better (in terms of properly centering it). I'm not sure what you can do. Perhaps just leave it as `round` for now... not sure

**Comment by FezVrasta** [comment]
I forked your pen to better show the problem and hack on it.

https://codepen.io/FezVrasta/pen/mmojyP

**Comment by atomiks** [comment]
The latest version still uses `floor()` right? I'm changing values and it seems to be perfectly centered each time. Maybe the CSS triangle's point is the problem?

**Comment by FezVrasta** [comment]
I notice that if you zoom it gets decentered sometimes.

**Comment by FezVrasta** [comment]
I investigated a bit about this problem.

The problem is that the reference element has an odd width, which isn't divisible by 2. This means that, to properly center it, we should use half pixels.

We avoid to use half pixels because on some browsers/screens/hardware it causes the poppers to get rendered blurred.

The arrow is positioned relatively to the popper, if the popper isn't properly centered (0.5px off), the arrow won't be able to be centered as well.

The picture below should explain the problem clearly:
![image](https://cloud.githubusercontent.com/assets/5382443/26776337/04ba34c4-49d9-11e7-8801-922dfd1dc206.png)

**Comment by atomiks** [comment]
To be honest, I think you're better off going with `Math.round`. I'm going into your source and changing it to that myself (and shipping tippy with it) since it positions the arrow better in most cases (particularly in the vertical case).

**Comment by FezVrasta** [comment]
May you submit a PR to show me what you changed and how it works pls?

**Comment by atomiks** [comment]
It's just `Math.floor(sideValue)` to `Math.round(sideValue)`

`Math.round`
![img](https://i.gyazo.com/d51e1409901df1555403911191fe9deb.png)

`Math.floor`
![img](https://i.gyazo.com/7487353aa10d053a0428ad111fd8bfb5.png)

**Comment by FezVrasta** [comment]
Ok I'm cool with this, but I don't think it will fix the problem I described few post above.

**Comment by atomiks** [comment]
It seems to be "good enough" for most cases so far that I've tested, even circle elements where it's obvious when the arrow is off by a bit. It's at least more reliable than `floor` from what I'm seeing

**Comment by FezVrasta** [comment]
Mind to send a PR with the fix please? I'm quite busy right now.

**Comment by atomiks** [comment]
So it seems like the actual popper is moved too far (relative to its reference el), but the arrow with Math.round is correctly positioned relative to the popper. So maybe a Math.floor on the pop and Math.round on the arrow?

In `computeStyle`:
```javascript
  // round sides to avoid blurry text
  var offsets = {
    left: Math.floor(popper.left),
    top: Math.floor(popper.top),
    bottom: Math.floor(popper.bottom),
    right: Math.floor(popper.right)
  };
```

This seems to better position tooltips with tippy...

**Comment by atomiks** [comment]
After doing some testing the best possible positioning is achieved when you:

- Use Math.floor on the popper (relative to its ref el)
- Use Math.round on the arrow (relative to the popper)

```javascript
  // in function computeStyle()
  var offsets = {
    left: Math.floor(popper.left),
    top: Math.floor(popper.top),
    bottom: Math.floor(popper.bottom),
    right: Math.floor(popper.right)
  };

  // in function arrow()
  data.offsets.arrow[side] = Math.round(sideValue);
```
Above:
![img](https://i.gyazo.com/212b554ba498533b6121f804c506aad3.png)

Current:
![img](https://i.gyazo.com/bc483499ac4ab703eeda9accf88f72b1.png)

**Comment by atomiks** [comment]
https://codepen.io/anon/pen/wedwpd

I think this covers the 8 different cases: 4 horiz, 4 vert, with each combination of odd/even pixels for the reference and popper widths.

Proposed above
![img](https://i.gyazo.com/c1f04dd587147217b98b5752b7834080.png)

Current
![img](https://i.gyazo.com/e315a45c65bf095da5bffc781899b789.png)

**Comment by fatfisz** [comment]
Ha! It turns out that changing `Math.round` to `Math.floor` is the cause of an off-by-1px problem for me 😉

Would a good solution be to add a built-in "fixer" modifier or would that be too much? The only job of that modifier would be to round `data.offsets.popper` values before `computeStyle`, and it would be disabled by default. Right now I had to implement it on my own, but this might be a problem for others too.

**Comment by FezVrasta** [comment]
Wouldn't make sense to just fix the logic that rounds the value we already have?

**Comment by fatfisz** [comment]
I'm not sure, since apparently `Math.floor` works better in some cases and `Math.round` in others and it would make sense to have the choice. Or are you referring to something else?

**Comment by FezVrasta** [comment]
I don't think the rounding strategy should be left to the user, there must be a magic recipe to have it always work correctly

**Comment by fatfisz** [comment]
That would be nice, indeed. I don't have time to take care of this now, but maybe I'd look into this in more detail after some time. My exact case is a select-style component that needs to have the options popup which is perfectly aligned with the value display. Unfortunately, the offset for the display is `488.5px`, which is displayed by the browser as `489px`, and the popper is at `488px`.

**Comment by atomiks** [comment]
@fatfisz have you tried using hardcoded even-numbered `px` values? I found that odd numbers and using `rem` caused it to be off sometimes because popper uses `px`, but generally the current one works better than previously.

**Comment by goyney** [comment]
If this was closed, what was the outcome? It is not clear from this thread and I'm seeing the issue in latest.

Base element: (x positioning of 183.625)
![screen shot 2018-05-13 at 4 13 11 pm](https://user-images.githubusercontent.com/1015040/39971417-8f790c1e-56c8-11e8-8a82-25884cf5cc6f.png)

Popped element: (x positioning of 183)
![screen shot 2018-05-13 at 4 12 48 pm](https://user-images.githubusercontent.com/1015040/39971418-8f8e1578-56c8-11e8-830e-732a8994f630.png)

Rendered popup: (1px off)
![screen shot 2018-05-13 at 4 14 25 pm](https://user-images.githubusercontent.com/1015040/39971429-bda1fe16-56c8-11e8-94e3-8568f3b57516.png)

How can I resolve this?
