### ISSUE TITLE
Tooltip.js arrow lacks x-arrow

### ISSUE THREAD

**Issue by aristidesfl** [FezVrasta/popper.js#278]
### CodePen demo

https://codepen.io/aristidesfl/pen/eWPKJX

### Steps to reproduce the problem

1.  Use Tootip.js to create a tooltip
2. Scroll horizontally to make the tooltip out of bound

### What is the expected behavior?

The tooltip arrow should move to follow the reference element.

### What went wrong?

The tooltip arrow stays centered in the tooltip

### Any other comments?

Adding the attribute `x-arrow` to the arrow solves the problem

**Comment by FezVrasta** [comment]
Good catch! Feel free to send a PR, I'll be able to get to it only in 2 days
