### ISSUE TITLE
Specify positioning behavior (absolute / fixed) using reference element

### ISSUE THREAD

**Issue by bedeoverend** [FezVrasta/popper.js#282]
Not sure if I'm missing something in how to use Popper, but when using a reference element is there a way to manually specify whether popper should treat it as absolute or fixed?

My use case is a reference element which mimics the current selection on the page - providing the size and position of the current range to popper. When scrolling, popper takes the size and position and assumes the reference element is the window (I think?) so jumps while you scroll, even though the selection hasn't changed and therefore popper shouldn't have moved.

Not sure if this is a feature request, bug, or I'm missing something in the documentation.

### CodePen demo

http://codepen.io/bedeoverend/pen/KWYjNp

### What is the expected behavior?

Popper should stay in same place while scrolling

### What went wrong?

Popper attempts jumps with page scroll

**Comment by FezVrasta** [comment]
I think this is somewhat related to #224 but I need to investigate on it.

**Comment by FezVrasta** [comment]
That was a bug with your implementation.

https://codepen.io/FezVrasta/pen/VbqLXa

**Comment by bedeoverend** [comment]
@FezVrasta thanks for the prompt response, and fixing my implementation! Didn't realise had to keep the rect live.
