### ISSUE TITLE
Not correct position of popper when it is located inside of body tag and body scrolled afterwards

### ISSUE THREAD

**Issue by vladferix** [FezVrasta/popper.js#286]
It is related to #224 and happening then some scroller is somewhere between reference and scrolled body parent.

**Comment by FezVrasta** [comment]
Please update the issue to follow the [issue template](https://github.com/FezVrasta/popper.js/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by vladferix** [comment]
Actually found that my described case above was not true, will investigate and describe it later

**Comment by vladferix** [comment]
It is breaking only then reference is put into container with `position: fixed`, which is more related #264 and #253 , everything else works for me, so close this bug for now.
