### ISSUE TITLE
Use of Object.assign disallows deep merge e.g. changing the arrow classNames only

### ISSUE THREAD

**Issue by rosskevin** [FezVrasta/popper.js#29]
This is a trivial issue but I'd rather not duplicate any default config externally.

Using [Object.assign](https://github.com/FezVrasta/popper.js/blob/master/src/popper.js#L268) makes use of the defaults for `arrow` impossible if you want to customize.

[Codepen test case](http://codepen.io/rosskevin/pen/EKEXGM?editors=0110)

I don't think it is a big piece of code to add, I have used [node-extend](https://github.com/justmoon/node-extend) for this and it works well (and you don't need to add jquery)

**Comment by rosskevin** [comment]
BTW - this I ran into this because of a [common SCSS lint rule](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#selectorformat):
`SelectorFormat: Selector `popper__arrow` should be written in lowercase with hyphens`

Perhaps a default class change to `popper-arrow` wouldn't hurt?

**Comment by FezVrasta** [comment]
I'm flowing the BEM convention for the class names.

I think we should find a better polyfill which supports deep merging.

**Comment by FezVrasta** [comment]
@rosskevin please may you try the `object-deep-assign` branch and let me know if it fixes the problem?

**Comment by rosskevin** [comment]
@FezVrasta this [test case](http://codepen.io/rosskevin/pen/xVWJeN?editors=0110) was updated with your branch and still doesn't work.

**Comment by FezVrasta** [comment]
Ok I'm sure now it works :)

I've changed `arrow.classNames` with `arrowClassNames` so there's not an additional level of deepness and everything works fine.
All the "deep merge" functions I have found was buggy and very big.
