### ISSUE TITLE
Chrome and blurry text due to transform3d

### ISSUE THREAD

**Issue by petetnt** [FezVrasta/popper.js#3]
There was an comment on HN about examples looking like images

> Perhaps I'm an idiot, but it wasn't immediately clear to me that the examples were actually examples. They looked like images...

When I first looked at the examples I thought so too but it wasn't quite obvious to me why. After looking at the examples again, it wasn't due to missing scrollbars or anything, it was the blurriness of the text for me, which made the poppers look like low quality JPEGs

Chrome on the left, Firefox on the right:

![image](https://cloud.githubusercontent.com/assets/7641760/14327329/6ec768f2-fc3a-11e5-963e-3355c180141f.png)

As you can see the Chrome one is extremely blurry. There are [some[1]](http://stackoverflow.com/questions/6411361/webkit-based-blurry-distorted-text-post-animation-via-translate3d) workarounds [workarounds[2]](http://stackoverflow.com/questions/8024061/webkit-blurry-text-with-css-scale-translate3d) to combat this, but quickly going through them with Devtools didn't bring much results. Most likely they are something that need to be applied every time [translate3d is applied](https://github.com/FezVrasta/popper.js/blob/master/src/popper.js#L237).

**Comment by FezVrasta** [comment]
I think the easiest solution would be to round the number of the coordinates, it's quite easy.

**Comment by petetnt** [comment]
Yeah, that might work (should work).

**Comment by FezVrasta** [comment]
77677f0333e6efa02be96bbba4398e89e16b6208

I think this should be enough, let's wait a bit before releasing a new version.
