### ISSUE TITLE
Use named exports in popper-utils instead of default export

### ISSUE THREAD

**Issue by sqal** [FezVrasta/popper.js#303]
Hi Popper team :) I have a request for popper-utils module. So currently this module uses only one - default export which is an object containing all the utility functions. My request to you is to consider changing the default export to named exports because using default export we lose very important benefit which is tree-shaking. For example in my project in just one place I use `getOffsetRectRelativeToArbitraryNode` function, so I need to import it like this:

```
import PopperUtils from 'popper.js/dist/esm/popper-utils';
PopperUtils.getOffsetRectRelativeToArbitraryNode()
```

This will result in including all functions in our bundle file, even if we use just one. 

What i would like to do is to import just one function that I need:

`import { getOffsetRectRelativeToArbitraryNode } from 'popper.js/dist/esm/popper-utils'`

This time however webpack will mark all the exports that aren't used:

```
/* unused harmony export getStyleComputedProperty */
/* unused harmony export getParentNode */
/* unused harmony export getScrollParent */
/* unused harmony export isOffsetContainer */
...
```

and then these functions will be dropped by uglifyJS. Much better, right ? So that's it. I would be very , very grateful if you would consider implementing this change for this module. Thank you :)

**Comment by FezVrasta** [comment]
Hi,

tree shaking wouldn't be of any use in this case I guess, because Popper.js already uses internally all the utils.

The change is surely something good so I'm not against it tho.
