### ISSUE TITLE
DOM listeners are not released when Popper is destroyed?

### ISSUE THREAD

**Issue by slavafomin** [FezVrasta/popper.js#304]
Hello!

Thank you for this great library!

However, I'm experiencing a situation when number of DOM listeners increases every time my custom popup is opened.

I'm calling: `this.popper = new Popper(trigger, popup);` when showing my pop-up and `this.popper.destroy()` when hiding it.

I'm experiencing this in Google Chrome: I'm just opening the Performance tab and hitting the record button, then I'm trying to open and close the popup several times. When recording is stopped, I see a ladder-like graphic with increasing number of DOM listeners:

![screenshot_2017-06-10_03-07-54](https://user-images.githubusercontent.com/1702725/26998230-04acf43a-4d8a-11e7-9736-a31c5656f38e.png)

However, if I remove both calls to Popper, then the problem disappears.

What could be causing this? I'm I freeing the resources correctly?

Thanks!

**Comment by FezVrasta** [comment]
Event listeners are removed on destroy.
https://github.com/FezVrasta/popper.js/blob/master/src/popper/methods/destroy.js#L21

**Comment by slavafomin** [comment]
I'm not sure why Google Chrome is showing increasing number of listeners in the performance report, but `getEventListeners(window)` shows me only one listener at each given moment, so probably, everything is fine. I haven't been able to find any issues with the code either. Sorry for the false alarm.
