### ISSUE TITLE
Including from bower guidance...

### ISSUE THREAD

**Issue by shmax** [FezVrasta/popper.js#308]
Hello again, I know you're probably tired of fielding questions like this, but I just can't wrap my head around how to consume this component via bower. Yes, I know Bower is on the decline, but I'm working on an Ember project and switching to npm or yarn is out of scope for the feature I'm developing.

So, how do you do it? 

If I do something like 

```json
// bower.json
{
"dependencies": {
  "popper.js":"1.10.1"
}
```

Then I wind up with the direct source from git, and there is no `/dist` folder (I know you don't want to have a dist folder).

If I follow the recommendation in your documentation and point to the unpkg CDN, like this:

```
// bower.json
{
"dependencies": {
  "popper.js":"https://unpkg.com/popper.js"
}
```

Then everything works, but then I don't seem to have the ability to do any kind of semver limiting.

If I try appending a version number, like this:

```
// bower.json
{
"dependencies": {
  "popper.js":"https://unpkg.com/popper.js@1.10.1"
}
```

Then I wind up with this in `bower_components`:
```
/bower_components
    /popper.js
       .bower.json
       index.1
```

I wouldn't mind, but for some reason I can't convince Ember to consume the oddly-named `index.1` file.

Any advice? Thanks much!

**Comment by FezVrasta** [comment]
I don't think there's a way to achieve what you are looking for, sorry.

Anyways, Bower is not deterministic so specifying a version doesn't help that much.

**Comment by shmax** [comment]
> I don't think there's a way to achieve what you are looking for, sorry.

You make it sound like I'm trying something exotic, but your approach is the one I haven't seen before. Every entry in my bower.json file has a version number next to it; only yours doesn't. Are people really expected to roll the dice with that `unpkg` endpoint and just trust that the version that comes out the other end doesn't break anything? What am I not understanding, here?

**Comment by FezVrasta** [comment]
I don't plan to support Bower because it's a deprecated technology and, generally, it's a bad practice to use it to manage your dependencies.

Bower could support version numbers in URLs, but it doesn't. And they can't pretend that I'm willing to put a bunch of compiled files in the place where the **source** is meant to be stored.

**Comment by shmax** [comment]
Okay, fair enough. I spent the day learning about npm and bower, and I think your position is this (correct me if I'm wrong):

1. Bower doesn't actually host anything, so if you wanted to have something like a `/dist` folder it would have to exist in your repo
2. You don't want to have a `/dist` folder in your repo because you only want your repo to contain source, not knowledge of how to consume it
3. you don't mind providing `/dist` via npm because it can be prepared in a CI step before deploying to npm.

Do I have all that right? If so, then I agree with you. I was able to successfully include popper via `ember-browserify` (with some difficulty). 

I guess my suggestion for you would to either be a little more explicit about the limitations of the bower approach you are using (it doesn't handle semver) you have on your main README, or drop references to it altogether. Also, I don't know if I would endorse the usage of `ember-popper`; nobody seems to be maintaining it, and it hasn't reached a `1.0` release yet.

Finally, since you have integration help for various frameworks, here's how I was able to add it to Ember:

step 1: install ember-browserify
```sh
npm install --save-dev ember-browserify
```

step 2: install popper.js
```
npm install popper.js --save
```

At this point there are a few tricky bits. I'll finish this comment up once I get to the office and can refer to my code...

**Comment by FezVrasta** [comment]
Why is ember-browserify needed? I do provide bundles in umd, esm and even in full es2015... What format expects ember?

**Comment by shmax** [comment]
ember-browserify is needed because it's not currently possible to directly include packages from node_modules into an Ember application. There are a variety of different methodologies for shoehorning that kind of functionality into the pipeline, but they all require external packages (`ember-cli-node-assets` is another one I tried), and not all of them can cope with the extra intricacies involved with developing an add-on. I don't know exactly how ember-browserify works, but evidently it is smart enough to traverse the directory structure for a package and identify a file in the right format with the right amd/umd/es6 hooks. Judging by what I see happening with the sourcemaps in the debugger, in the case of popper.js it finds its way into the "dist/umd" folder, and extracts `popper.js`. This is all without any configuration or prompting from me of any kind, which is nice.

To answer your question, you typically write your conventional Ember code in es6.

**Comment by kybishop** [comment]
@shmax have you taken a look at https://github.com/kybishop/ember-popper

Even you can't npm install that, it may be able to provide guidance

**Comment by kybishop** [comment]
More inspiration: https://github.com/kybishop/ember-popper/pull/15/files

Shows how to import popperjs without ember-cli-node-assets

**Comment by shmax** [comment]
@kybishop Yes, I examined your project closely. It has a dependency on `ember-cli-node-assets`, which didn't seem to work well in an add-on context, And thanks for the broccoli-stew idea; if I hadn't already gotten this all working well with `ember-browserify` I might have given it a look, but from what I see in the code you posted it doesn't really look any simpler, and I don't know that it works with add-ons. I'm all set with ember-browserify, but thanks for the advice.

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/popper.js/issues/390
