### ISSUE TITLE
aria-describedby is placed on tooltip instead of reference element

### ISSUE THREAD

**Issue by apdrsn** [FezVrasta/popper.js#317]
### CodePen demo

Haven't created a codepen – as it is on your demo as well. See this screenshot
![image](https://user-images.githubusercontent.com/6361772/27330470-cd919996-55b9-11e7-8d24-e9b954fd6e32.png)

### Steps to reproduce the problem

1.  Inspect tooltip after it is initialised
2.  Tooltip has both aria-describedby and an id
3.  Nothing gets added to the reference element (the button) 

### What is the expected behavior?
I would expect that the button had the aria-describedby, and the tooltip the id – and thereby tie them together

### What went wrong?

I think that on line 194 in ```/src/tooltip/index.js``` should be changed from

``` js
// Add `aria-describedby` to our reference element for accessibility reasons
tooltipNode.setAttribute('aria-describedby', tooltipNode.id);
```

to

``` js
// Add `aria-describedby` to our reference element for accessibility reasons
reference.setAttribute('aria-describedby', tooltipNode.id);
```

**Comment by FezVrasta** [comment]
Thank you, feel free to send a PR if you'd like to help.

**Comment by apdrsn** [comment]
Cool – I'll give it a try :)

And thanks for the great work on this!
