### ISSUE TITLE
Cannot find module 'popper-utils'

### ISSUE THREAD

**Issue by InterAl** [FezVrasta/popper.js#323]
Getting a runtime exception upon importing popper.js.

This started occurring an hour ago, since you published version 1.10.3.

I believe the problem lies here:

https://github.com/FezVrasta/popper.js/blob/dd850c2908ed97f5bd38b3011c494bb9ef835aae/packages/popper/src/index.js#L2

**Comment by FezVrasta** [comment]
on it, thank you for the report

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/popper.js/releases/tag/v1.10.5
