### ISSUE TITLE
DOMElement of type <form> cause issues : Popper consider it an array (because of `length` present)

### ISSUE THREAD

**Issue by cnicodeme** [FezVrasta/popper.js#33]
Well I think everything is in the title :p 

When using {parent: document.querySelector('form')}, Popper.js display a warning about having an array of Nodes instead of just one (which is truly just one) because a form element has a `length` key in it's object, making Popper believe it's an array.

It may be better to check for an existing element from a dom (like parentElement) to know if it's an array or not ?

**Comment by cnicodeme** [comment]
Moreover, it fails with a "console.warning is not a function".

Here's the appropriate codepen : http://codepen.io/anon/pen/mPLXPX

**Comment by cnicodeme** [comment]
Awesome ! :)

**Comment by FezVrasta** [comment]
You're welcome :)
