### ISSUE TITLE
Wrong positioning if popper is child of positioned parent

### ISSUE THREAD

**Issue by Egorvoz** [FezVrasta/popper.js#331]
### CodePen demo

https://codepen.io/anon/pen/EXQeKp

### Steps to reproduce the problem

1.  Open `https://popper.js.org/`
2.  Open devtools.
3.  Find in tab *Elements* this element `id="page-wrapper"`
4.  Set CSS props `position: absolute`
5. A lot of tooltips don't work (especially tooltips with top & bottom position)  

### What is the expected behavior?

The expected behaviour - all works good and the position of parent element won't crash the tooltips position.

### What went wrong?

![chrome_2017-06-30_09-43-16](https://user-images.githubusercontent.com/6547453/27724065-b74eca70-5d78-11e7-8d6c-03d7fcaae7cc.png)

### Any other comments?

Also in this cool lib - https://github.com/atomiks/tippyjs/issues/70

P.S. Your lib also f*cking awesome

**Comment by FezVrasta** [comment]
I need a reproducible codepen as requested by the issue template you ignored.

**Comment by Egorvoz** [comment]
@FezVrasta Okay. I will create Codepen demo. Sorry man.

**Comment by Egorvoz** [comment]
@FezVrasta I add CodePen demo. Please recheck and if all good, reopen the issue. Thanks.

**Comment by FezVrasta** [comment]
I can't see anything wrong in the codepen demo. The tooltip has more left offset because the `absolute` `body` is considered the boundaries element (rather than the default `document`) and then it adds some extra margin.

**Comment by atomiks** [comment]
https://codepen.io/anon/pen/EXQeKp

**Comment by Egorvoz** [comment]
@atomiks thks :)

**Comment by tobega** [comment]
Found that there is also a problem if the popper element is contained in a relatively positioned element. Don't know if it is the same bug or a different bug. Repro here: https://codepen.io/anon/pen/BdLPxw

**Comment by maxpaj** [comment]
Is there any neat workaround for this at the moment?

**Comment by tobega** [comment]
Yes, make all your poppers a child of a "normal" hidden div that is a child
of body.

Den 29 aug. 2017 14:55 skrev "maxpaj" <notifications@github.com>:

**Comment by JosephusPaye** [comment]
Hi,

I can still reproduce the bug using the provided Codepen (https://codepen.io/anon/pen/EXQeKp). Same results in Chrome beta 63, Firefox 56, and Edge 40 (all on Windows 10).

After the page loads, the text is added which pushes the reference element down, but the popper stays in the old location. The location is not changed after scroll or resize.

Here's a gif showing the issue: https://i.imgur.com/squuhji.gif

**Comment by atomiks** [comment]
@JosephusPaye  that is 1.12.4 which has that problem. Change the package in the CodePen settings to 1.12.7, and it's fixed

**Comment by JosephusPaye** [comment]
Cool, thanks!

**Comment by atomiks** [comment]
Unfortunately the latest Popper (1.12.5+) has a bug when updating a popper's position usually when it's near the viewport edges. If the bug is not an issue for you, you can use `tippy.standalone.js` + the latest Popper.js instead. 

Currently, Tippy uses 1.12.4 because of that issue. I'm hoping he is able to fix it soon so it can be updated...

**Comment by FezVrasta** [comment]
For reference, we are talking about #251
