### ISSUE TITLE
✨ v2 Whishlist ✨

### ISSUE THREAD

**Issue by FezVrasta** [FezVrasta/popper.js#332]
Please post here anything you'd like to see in Poper.js v2.

Specifically, I'm still trying to figure out how to improve the API to make it more useable... But any suggestion is more than welcome.
The only requirement, I guess, is the suggestion to be a breaking change (otherwise it can just be implemented in the current version)

And, no, I don't have any ETA on where and if a V2 will be released.
It's just to see how many of you think it is actually needed.

**Comment by hekigan** [comment]
What about an easy, direct way to update the tooltip content when we have something dynamic?

`tooltipInstance.content(htmlNode | String);`

**Comment by FezVrasta** [comment]
Feel free to open an issue. That would not need a breaking change to get implemented

**Comment by hekigan** [comment]
I will just go ahead and do that then  :)

**Comment by FezVrasta** [comment]
I'll simply mark issues as `v2` if I see they need some breaking change.
