### ISSUE TITLE
CSS margin not being accounted when positioning arrow

### ISSUE THREAD

**Issue by aristidesfl** [FezVrasta/popper.js#333]
### CodePen demo

https://codepen.io/aristidesfl/pen/dRdLXr

### Steps to reproduce the problem

1. Make a popper with an arrow
2. Add a CSS margin to the popper

### What is the expected behavior?

Arrow should be centered with ref

### What went wrong?

Arrow is not centered.

**Comment by FezVrasta** [comment]
Wondering why does it work on popper.js.org... 🤔

**Comment by aristidesfl** [comment]
Which one of the examples has a CSS margin?

**Comment by FezVrasta** [comment]
Oh sorry now I see what you mean! Yeah that's definitely a bug.

**Comment by aristidesfl** [comment]
Is there another way to configure the margin relative to the viewport?

**Comment by FezVrasta** [comment]
I don't think so
