### ISSUE TITLE
Attributes are getting overwrited

### ISSUE THREAD

**Issue by kedwin** [FezVrasta/popper.js#338]
in computeStyle function

  var attributes = {
    'x-placement': data.placement
  };

data.attributes = attributes;

if this runs every other modifier which changed the data.attributes object will be overwritten
at the end data.attributes will only contain x-placement nothing more

this makes example "hide" not working since that attribute won't be reflected to html element

**Comment by FezVrasta** [comment]
This is definitely a regression introduced when I created this new modifier. I'll be able to work on it tomorrow if nobody wants to send a PR before.

**Comment by FezVrasta** [comment]
Fixed in 1.10.7

**Comment by kedwin** [comment]
please update dist/esm

**Comment by FezVrasta** [comment]
It's already updated from what I see.

![image](https://user-images.githubusercontent.com/5382443/27793439-54306f42-5ffe-11e7-9380-20e88d71f01b.png)

This is from https://unpkg.com/popper.js@1.10.8/dist/esm/popper.js
