### ISSUE TITLE
Troubles with new "arrow" attributes ?

### ISSUE THREAD

**Issue by wtfred** [FezVrasta/popper.js#34]
Hello,

I just update from 0.3.1 to 0.3.5, and i loose all my arrows.

You seems to have change the configuration from popper.arrow.tagName to popper.arrowTagName and so on but forget to change the parsing of the configuration, or am i missing something ?

Line 288
```javascript
if (config.arrow) {
        var arrow = d.createElement(config.arrow.tagName);
        addClassNames(arrow, config.arrow.classNames);
        addAttributes(arrow, config.arrow.attributes);
        popper.appendChild(arrow);
}
```

**Comment by rosskevin** [comment]
Check the docs,  some nesting was removed so it should be arrowClassNames now.

**Comment by wtfred** [comment]
Yeah, and it will never be parsed because in the code i quoted the test is made on config.arrow and it doesn't exist anymore because the new configuration for arrow is in config.arrowTagName, config.arrowClassNames, and config.arrowAttributes

Did you read too fast or am i missing something really obvious here ?

**Comment by rosskevin** [comment]
I read on mobile, sorry.  A link to the source is helpful:
https://github.com/FezVrasta/popper.js/blob/master/src/popper.js#L289

Looks like a refactoring bug.  You're right, usage of the config wasn't changed.  I'm sure @FezVrasta will accept a PR on it.

**Comment by wtfred** [comment]
Well, i will gladly do it but i'm not sure how to "rebuild" properly so here is the code

Replace at https://github.com/FezVrasta/popper.js/blob/master/src/popper.js#L288

```javascript
        if (config.arrowTagName) {
            var arrow = d.createElement(config.arrowTagName);
            addClassNames(arrow, config.arrowClassNames);
            addAttributes(arrow, config.arrowAttributes);
            popper.appendChild(arrow);
        }
```
Anyway, thanks a lot @FezVrasta for this library ! :)
