### ISSUE TITLE
Ability to change content dynamically

### ISSUE THREAD

**Issue by hekigan** [FezVrasta/popper.js#342]
What about an easy, direct way to update the tooltip content when we have something dynamic?

```
tooltipInstance.content(htmlNode | String);
```

1. In case of String: we just need to switch with `textContent` and not `innerText`.
ref: https://kellegous.com/j/2013/02/27/innertext-vs-textcontent/

2. In case of htmlNode, use `.appendChild()` and not `.innerHTML` for security purposes.
https://coderwall.com/p/o9ws2g/why-you-should-always-append-dom-elements-using-documentfragments

Opinion?

**Comment by FezVrasta** [comment]
I have to check if the Bootstrap tooltips allow this already so that I can copy the API.

Otherwise we'll have to invent our own one.

**Comment by victor-cordova** [comment]
Hello. I'm currently working on this issue. PR on the way.

**Comment by hekigan** [comment]
Since the modification got merged, I am going to close this issue.
Thanks @victor-cordova for your work.

**Comment by Amantel** [comment]
Hi! Can we do the same for popper?
