### ISSUE TITLE
Arrow lacks padding between itself and edge of popper

### ISSUE THREAD

**Issue by atomiks** [FezVrasta/popper.js#343]
As mentioned here: https://github.com/atomiks/tippyjs/issues/69

### CodePen demo

https://codepen.io/anon/pen/jwvxMd

### Steps to reproduce the problem

1.  Self-explanatory

### What is the expected behavior?

Arrow should have some padding (customizable?) so it isn't on the same level as the curved border

### What went wrong?

The arrow sits at the very edge which causes the buggy problem

### Any other comments

Not sure if it's set up correctly or if there's an option to fix it.

**Comment by FezVrasta** [comment]
That's actually by design, you have to apply a margin to the popper manually. Refer to the popper.js.org demos to see how it works.

**Comment by atomiks** [comment]
Oh you're right.. why didn't you mention that in the tippy issue? That's a super easy fix. Thanks.

**Comment by FezVrasta** [comment]
Sorry I didn't notice that was the problem
