### ISSUE TITLE
preventedOverflow data flag, like flipped

### ISSUE THREAD

**Issue by giladgray** [FezVrasta/popper.js#346]
### Steps to reproduce the problem

1. enable `flip` modifier, make popper flip, note data contains `flipped: true`
2.  enable `preventOverflow` modifier, make popper prevent overflow, note no obvious change in data

### What is the expected behavior?

Would be so awesome if it were trivial to know that overflow was prevented. 
`preventedOverflow: true`

### Any other comments?

I looked through the modifier implementation and it seems non-trivial to add a notion of "yes overflow was prevented" to the modifier -- lots of `Math.max` logic to implicitly handle overflowing.

**Comment by FezVrasta** [comment]
The `flipped` boolean is there because the `flip` modifier actually needs it to work.

I have nothing against an additional flag for this modifier as well.

**Comment by FezVrasta** [comment]
Going to close this for lack of interest from the community. If anyone wants this just open a PR to implement the feature please.
