### ISSUE TITLE
compute styles object for arrow in computeStyles

### ISSUE THREAD

**Issue by giladgray** [FezVrasta/popper.js#347]
per https://github.com/souporserious/react-popper/issues/34#issuecomment-314149702, it would seem that a `data.styles.arrow` object would be helpful to provide a consistent rendering experience. 

currently, `data.styles` contains CSS properties for the popper element, and there is no equivalent for pre-computed CSS properties for the arrow.

**Comment by giladgray** [comment]
@FezVrasta filed this to follow up on our discussion linked above, feel free to update it as you see fit!

**Comment by FezVrasta** [comment]
I think we can add an `arrowStyle` property to the data object and use it in the `applyStyle` modifier. This shouldn't introduce any breaking change.
