### ISSUE TITLE
How to access Popper methods in Tooltip instance?

### ISSUE THREAD

**Issue by websirnik** [FezVrasta/popper.js#348]
I can't figure out how to access `destroy()` method that Popper has from a Tooltip instance. I need to completely destroy a Tooltip instance. `dispose()` just removes from DOM, but does not remove the instance.

**Comment by FezVrasta** [comment]
`dispose` is going to call `destroy` on the Popper instance.

https://github.com/FezVrasta/popper.js/blob/master/packages/tooltip/src/index.js#L253
