### ISSUE TITLE
onCreate does not return popper instance

### ISSUE THREAD

**Issue by JSteunou** [FezVrasta/popper.js#36]
Tried to follow the documentation with `onCreate` `onUpdate` but it cannot be chained. `onCreate` return `undefined`

**Comment by FezVrasta** [comment]
May you test the new `fix-36` branch and let me know if it fixed your problem?

**Comment by JSteunou** [comment]
weird PR looks ok

**Comment by FezVrasta** [comment]
I know :(

**Comment by JSteunou** [comment]
I applied your patch directly in the node_modules src and it works fine. If it's just your test going wrong, check you're actually run them on src and not build.

**Comment by FezVrasta** [comment]
Yup the tests run on src...

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/popper.js/commit/80aa0dfc7753e293f3cef7b526474d41a2beb94b should have fixed the problem once for all.

The test was failing because `onUpdate()` is not getting called on initialization, this mean that you should manually trigger it if you want it to run.

```js
new Popper()
.onUpdate(function(data) {
  console.log(data);
})
.onCreate(function(instance) {
  instance.update();
})
```
