### ISSUE TITLE
IE11: Object doesn't support property or method 'contains'

### ISSUE THREAD

**Issue by whitecolor** [FezVrasta/popper.js#361]
This line: https://github.com/FezVrasta/popper.js/blob/08c5d6010346bf9df06e9f81a54fa6c2c51e3639/packages/popper/src/utils/findCommonOffsetParent.js#L36

```js
element1 !== commonAncestorContainer && element2 !== commonAncestorContainer || start.contains(end)
```

causes error in IE11: `Object doesn't support property or method 'contains'`

![image](https://user-images.githubusercontent.com/736697/28499795-b4a9c146-6fd7-11e7-8c23-1c024bd4f695.png)

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.

**Comment by whitecolor** [comment]
This is not my problem but the problem of this library, you are using API that is not supported by IE.

This probably due to trying use `contain` method of `document` object which is not supported in IE. You know your code best, so you can understand what is potentially wrong.

**Comment by FezVrasta** [comment]
`contains` is supported by IE11.
