### ISSUE TITLE
IE11: Object doesn't support property or method 'contains'

### ISSUE THREAD

**Issue by whitecolor** [FezVrasta/popper.js#362]
https://github.com/FezVrasta/popper.js/issues/361

> contains is supported by IE11.

It is not supported on `document` itself, but on `document.body`

![image](https://user-images.githubusercontent.com/736697/28500129-038ec43c-6fdd-11e7-99d6-9a33cdeee1cc.png)

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
