### ISSUE TITLE
Package breaks TypeScript 2.4.2 project with broken .d.ts validation

### ISSUE THREAD

**Issue by AviVahl** [FezVrasta/popper.js#369]
Assuming latest TypeScript (2.4.2 atm) is globally installed (meaning, `tsc` command is available):
1.  `mkdir test` // create empty dir
2.  `cd test` // enter the dir
3.  `yarn init -y` // initialize `package.json` file
4. `yarn add popper.js` // add popper.js
5. `tsc  --init` // initialize tsconfig.json file
6. Create index.ts with:
```ts
import {BaseModifier} from 'popper.js';
```
7. `tsc` // compile files

### What is the expected behavior?
No errors should be reported.

### What went wrong?
```
node_modules/popper.js/index.d.ts(38,5): error TS2411: Property 'shift' of type 'BaseModifier | undefined' is not assignable to string index type 'BaseModifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(39,5): error TS2411: Property 'offset' of type '(BaseModifier & { offset?: string | number | undefined; }) | undefined' is not assignable to string index type 'BaseModifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(42,5): error TS2411: Property 'preventOverflow' of type '(BaseModifier & { priority?: Position[] | undefined; padding?: number | undefined; boundariesElem...' is not assignable to string index type 'BaseModifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(47,5): error TS2411: Property 'keepTogether' of type 'BaseModifier | undefined' is not assignable to string index type 'BaseModifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(48,5): error TS2411: Property 'arrow' of type '(BaseModifier & { element?: string | Element | undefined; }) | undefined' is not assignable to string index type 'BaseModifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(51,5): error TS2411: Property 'flip' of type '(BaseModifier & { behavior?: Position[] | "flip" | "clockwise" | "counterclockwise" | undefined; ...' is not assignable to string index type 'BaseModifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(56,5): error TS2411: Property 'inner' of type 'BaseModifier | undefined' is not assignable to string index type 'BaseModifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(57,5): error TS2411: Property 'hide' of type 'BaseModifier | undefined' is not assignable to string index type 'BaseModifier & Record<string, any>'.
node_modules/popper.js/index.d.ts(58,5): error TS2411: Property 'applyStyle' of type '(BaseModifier & { onLoad?: Function | undefined; gpuAcceleration?: boolean | undefined; }) | unde...' is not assignable to string index type 'BaseModifier & Record<string, any>'.
```

### Any other comments?

Will open a PR to fix

**Comment by FezVrasta** [comment]
Related?
https://github.com/FezVrasta/popper.js/pull/367

**Comment by FezVrasta** [comment]
v1.11.1 fixed this

**Comment by AviVahl** [comment]
yay. I barely got to comment and you already released a new version! 👍

**Comment by AviVahl** [comment]
@FezVrasta 
It appears validation passes, and requires me to:
`import Popper from 'popper.js';`

which was fine if the `main` in package.json was the non-bundled transpile commonjs target.
that's not the case.
`main` is pointing to the umd bundle, where no `.default` key is available.
I guess the import would work with the esm module, but not with the umd one.

**Comment by FezVrasta** [comment]
Don't you use `module`?

**Comment by AviVahl** [comment]
We run isomorphic tests in Node.js, where our ts to transpiled to js+commonjs, without any bundling.
Node just uses `main`.
Also, the `module` "pattern" is fairly new, with recent rollup/webpack versions supporting them. If someone is using browserify, he won't be able to use your package (via `require`).

imo, `main` should point to the commonjs code, `module` to the esm code, and umd should be available for explicit/direct/unpkg consumption.

**Comment by FezVrasta** [comment]
UMD is compatible with CommonJS, why should I export a CJS-only version of the lib?

**Comment by AviVahl** [comment]
The UMD bundle does not match the exported `.d.ts`. That's all I'm saying.
```
$ node
> require('popper.js).default === undefined
```

**Comment by FezVrasta** [comment]
I see.

ping @edcarroll

**Comment by edcarroll** [comment]
Tricky, as the previous DT typings didn't account for this scenario either... Unfortunately I don't _think_ it's possible to get both possibilities into a single type definition file, and `package.json` doesn't allow multiple type definitions.

Slightly stuck on what to do in this situation, will report back when I know more.
