### ISSUE TITLE
New tooltip.js npm release?

### ISSUE THREAD

**Issue by jspath** [FezVrasta/popper.js#371]
Can you please issue a new tooltip.js release to npm?

I'm running into this issue:
https://github.com/FezVrasta/popper.js/issues/290

And it doesn't seem to be in the latest npm tooltip.js release 1.1.4:
https://www.npmjs.com/package/tooltip.js

I realize a github issue may not be the right place to make this request.

**Comment by FezVrasta** [comment]
Oh right, thanks for the heads up, gonna publish one ASAP

**Comment by jspath** [comment]
Awesome, thanks!

**Comment by FezVrasta** [comment]
released

**Comment by fbring** [comment]
Would you be so nice and release the newest version to npm?

I´m running into this (#450) and the latest npm release was published 3 weeks ago to v1.1.6.

**Comment by FezVrasta** [comment]
Releases 1.1.7 with the fix, sorry for the delay

**Comment by fbring** [comment]
No problem!
I'm the one who's grateful
