### ISSUE TITLE
Ability to control the behavior of attaching scroll parents

### ISSUE THREAD

**Issue by tyscorp** [FezVrasta/popper.js#374]
This is a bit of a complex issue and I've not been able to create a simple CodePen demo.

I have a React component that acts as a Popper reference that is usable in multiple locations, including in portals. Popper is not able to find the correct element to attach scroll handlers to because the element with overflow scroll is not a parent of the reference element.

Currently I have a hacky way of dealing with this by adding matching DOM attributes at the portal mount point and where the portal is created and then linking them up by patching `getParentNode` to look for elements with those attributes and then treating the element with the corresponding ID as parent of that node.

```
function getParentNode(element) {
  if (element.nodeName === 'HTML') {
    return element;
  }
  if (element.hasAttribute('x-popper-element-id')) {
    return document.querySelector(`[x-popper-target-id=${element.getAttribute('x-popper-element-id')}]`);
  }
  return element.parentNode || element.host;
}
```

Because there's no API to modify this behavior I have to also copy `getScrollParent`, `attachToScrollParents` and `setupEventListeners`.

It would be nice if there was a way to do this without patching a bunch of internal code. I'm not sure what the API would look like.

I can look more into creating a CodePen to reproduce this issue if needed.

**Comment by FezVrasta** [comment]
A CodePen demo would help a lot to understand what's exactly happening, it would be cool if you could provide it.

**Comment by FezVrasta** [comment]
Also. Aren't these methods exposed by Popper.Utils by chance?

**Comment by tyscorp** [comment]
I'm still working on narrowing this down to the minimal reproducible example.

Those functions are provided by Popper.Utils but since I need to modify the last function in the chain I need to copy+paste all of them and update the reference in `getScrollParent` to my modified function.

**Comment by tyscorp** [comment]
I have 3 CodePens:

[Demonstrating the issue](https://codepen.io/anon/pen/gxLBmq)

[Fixing the issue by rearranging HTML](https://codepen.io/anon/pen/BdQqby) (not possible in my case)

[Fixing the issue by adding extra yucky plumbing](https://codepen.io/anon/pen/brBmJE)

**Comment by FezVrasta** [comment]
You can fix your problem doing this:
https://codepen.io/FezVrasta/pen/zdzQQG
