### ISSUE TITLE
Missing popper.js

### ISSUE THREAD

**Issue by cixonline** [FezVrasta/popper.js#379]
After downloading the latest popper.js from https://github.com/FezVrasta/popper.js/releases, it appears that the resulting zip file has no popper.js file in it to include in the script tag.

    <script src="~/lib/popper.js/XXXX"></script>

what needs to go in the XXXX? There are various .js files but no popper.js nor any min version. What am I missing?

**Comment by FezVrasta** [comment]
In the releases page you can download only the source code, follow the [installation](https://github.com/FezVrasta/popper.js#installation) instructions to install it.

**Comment by cixonline** [comment]
Ah, thanks. I was originally trying to install it from the Manage Bower Packages in Visual Studio 2017 Community but that also only appears to install the source code rather than the popper.js or popper.min.js files. Not sure if that's a bug but I ended up just downloading the actual popper.js file from unpkg and including that in the project.

**Comment by shvydky** [comment]
@FezVrasta,

As for me it is reasonable to include dist version of library into repository. In most cases, when users install the package using bower they just want to use it, not develop it. Look at the bootstrap repository, for example.

Tnx.

**Comment by FezVrasta** [comment]
This library doesn't support Bower, you can use it with Bower only if you install it using the unpkg.com URL.

Bower is deprecated, switch to npm

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/popper.js/issues/390
