### ISSUE TITLE
popper offset to big until resize

### ISSUE THREAD

**Issue by JSteunou** [FezVrasta/popper.js#38]
Linked to #25 I think

**Comment by JSteunou** [comment]
Fixed by doing 

```js
popper.onCreate(function(popper) {
  popper.state.updateBound();
});
```

Maybe `updateBound` should be called by popper on creation.

**Comment by JSteunou** [comment]
Ok, after reading, I see that `update` is already called, but the weirdest is to come, actually `update` as to be called twice to get the popper properly initialize. I think there is some missing computed value at first, but here at the second pass.

**Comment by JSteunou** [comment]
Should have read #25 more carefully, fixed by adding `position: absolute`.

**Comment by FezVrasta** [comment]
Yup there's something wrong with the first initialization of dynamically generated elements...

I would suggest to create the elements manually and then call popper on them untill this problem is fixed.
