### ISSUE TITLE
Tooltip title not updated after title attribute change

### ISSUE THREAD

**Issue by kutu** [FezVrasta/popper.js#381]
### Steps to reproduce the problem

1.  create title to element
2. set title attribute from js
3.  hover mouse over to see title
4.  change title attribute from js
5. hover mouse over again, and i see old title

### What is the expected behavior?

expected to see updated title

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.

**Comment by kutu** [comment]
why do my issue need follow "template" but others issues accepted without following "issues template"?

**Comment by FezVrasta** [comment]
Probably because other's issues provided enough information. And anyway I don't think it's a valid reason to don't follow the requirements I set to give **you** help for free.
