### ISSUE TITLE
Suggestion: include a dist folder

### ISSUE THREAD

**Issue by cixonline** [FezVrasta/popper.js#382]
Following on from an earlier issue with not locating the popper.js distribution files, I'd like to suggest that the source also include a dist folder with the compiled version of popper.js and a minimised version too. This is in keeping with how many other js libraries are packaged and would generally be the first thing most consumers would look for when they use the library for the first time.

**Comment by FezVrasta** [comment]
This has already been discussed here:
https://github.com/FezVrasta/popper.js/issues/308#issuecomment-308664696
