### ISSUE TITLE
Can't Find the popper Java Script file 

### ISSUE THREAD

**Issue by JakubGawel** [FezVrasta/popper.js#385]
I can't find the java script file in the file. I don't get where it is. Can someone please tell me where it is. I need it for my bootstrap website. The dropdowns don't work unless you have the popper.js. This is new to me because before you didn't need this. I am very new to popper, I have never used this library before and for some reason, I just can't find it. I sat here for an hour trying to find it.

**Comment by Johann-S** [comment]
See our Bootstrap documentation here : https://getbootstrap.com/docs/4.0/components/dropdowns/#overview
if you click on `popper.min.js` you'll be able to download Popper.js 😉

**Comment by FezVrasta** [comment]
Gonna create a dist/README.md file to explain (again) how to install the library since the instructions in the README are simply ignored

**Comment by FezVrasta** [comment]
Added:
https://github.com/FezVrasta/popper.js/blob/master/dist/README.md
