### ISSUE TITLE
syntaxError with bootstrap4 and gulp

### ISSUE THREAD

**Issue by Carlosxell** [FezVrasta/popper.js#386]
when use popper and bootstrap 4 from NPM and make a concat with gulp give me an error:

Popper.Utils=('undefined'==typeof window?global:window).PopperUtils,Popper.placements=placements,Popper.Defaults=Defaults;export default Popper;

**Comment by FezVrasta** [comment]
Please provide a reproducible example of the problem.

**Comment by Carlosxell** [comment]
https://github.com/twbs/bootstrap/issues/23381
