### ISSUE TITLE
NuGet package throwing error

### ISSUE THREAD

**Issue by OLTrustNo1** [FezVrasta/popper.js#387]
When installing popper.js via NuGet manager in VS2015 or VS2017, I get an error message:

> Could not install package 'popper.js 1.11.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Is it my machine? Or is it general? Anybody knows a workaround?

Given the dependency of Bootstrap 4 on this package, many issues might be raised in the future.

**Comment by FezVrasta** [comment]
I have zero experience with NuGet unfortunately.

ping @Johann-S

**Comment by FezVrasta** [comment]
If I run `nuget install popper.js` I see a new folder called `popper.js.1.1.1` and inside it I find all the sources I expect...

**Comment by OLTrustNo1** [comment]
Could it be related?

[could-not-install-nuget-package-with-the-correct-net-
version](https://stackoverflow.com/questions/37294538/could-not-install-nuget-package-with-the-correct-net-version?rq=1)

**Comment by FezVrasta** [comment]
I don't think I sign anything with keys

**Comment by OLTrustNo1** [comment]
I get the files in the "packages" folder outside my project (in the solution folder), but it does not add them to the project as it should.

**Comment by FezVrasta** [comment]
Maybe there's some missing setting in the package config

**Comment by OLTrustNo1** [comment]
I tried to open the NuGet package using [NuGet Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) and I can see an error coming up:

![image](https://user-images.githubusercontent.com/23658727/29274517-11393138-8100-11e7-9b11-993f30136984.png)
Does it ring a bell?

**Comment by OLTrustNo1** [comment]
Noob question: do you have a .nuspec file?

**Comment by FezVrasta** [comment]
umh nope, just package.nuspec

**Comment by OLTrustNo1** [comment]
Where is it? I can't find it in here

**Comment by FezVrasta** [comment]
It's generated on the fly by `nuget-publish`

**Comment by OLTrustNo1** [comment]
Do you have any way to "capture" it?

**Comment by FezVrasta** [comment]
¯\\\_(ツ)_/¯

Comment the line that deletes the file

**Comment by OLTrustNo1** [comment]
😳 

You'd speak Chinese, would be the same :stuck_out_tongue_closed_eyes:

I think I will leave it there as clearly I am not comfortable helping out... I still have much to learn!

**Comment by GearTheWorld** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'popper.js 1.11.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

Is that me or this popper.js doesn't support 4.6.2 ? Either I try to install popper.jsfrom nuget or bootstrap 4 beta I get this error so nothing is intalled.

**Comment by aflegel** [comment]
Same error for me.  I cannot install any version of popper from 1.9.9 on any version of .net 4.x.

**Comment by OLTrustNo1** [comment]
For testing purposes, i also tried on .net 3.5 and .net 2.0 projects => still the same issue

**Comment by Neo-NMO** [comment]
I think the main problem here is that it's not creating the folders to put the scripts into. Looking at bootstrap and others it looks like there should be a contents folder, and a Scripts folder in that where the scripts actually go.
They could clean up the message a bit, but I think it's basically saying "There's nothing here for me to do anything with"

**Comment by FezVrasta** [comment]
This is what I get when I install Popper.js from NuGet:

```
❯ nuget install popper.js
[...]
Adding package 'popper.js.1.12.1' to folder '/private/tmp'
Added package 'popper.js.1.12.1' to folder '/private/tmp'
Successfully installed 'popper.js 1.12.1' to /private/tmp
Executing nuget actions took 1.66 sec

❯ ls popper.js.1.12.1
index.d.ts              popper-utils.js.map     popper-utils.min.js.map popper.js.1.12.1.nupkg  popper.min.js
popper-utils.js         popper-utils.min.js     popper.js               popper.js.map           popper.min.js.map
```

It does miss folders, specifically the `umd` and `esm` ones, and the stuff is put directly inside the root directory of the package.

How should I tell NuGet to create the right structure of folders?

**Comment by FezVrasta** [comment]
I just published 1.12.2 that _should_ fix the problem with the NuGet package...

I'm still waiting for the whole thing to update so I can try to install it and see if the folders are properly formed.

**Comment by FezVrasta** [comment]
Ok, even installing it form CLI, the result is the expected:

```
❯ ls popper.js.1.12.2/content/Scripts/
esm                     popper-utils.js         popper-utils.min.js     popper.js               popper.min.js           umd
index.d.ts              popper-utils.js.map     popper-utils.min.js.map popper.js.map           popper.min.js.map

```

Please @OLTrustNo1 @aflegel @GearTheWorld may you confirm 1.12.2 works?

**Comment by OLTrustNo1** [comment]
Yes it works BUT it generates too many files and folders...

![image](https://user-images.githubusercontent.com/23658727/29382314-1968a06c-82c4-11e7-83c8-e2c991baa4ce.png)

**Comment by FezVrasta** [comment]
This is expected. Popper.js is shipped with several targets in mind

**Comment by najmeiranpour** [comment]
1-Install-Package popper.js -Version 1.12.5
2-Install-Package bootstrap -Pre

**Comment by Sm1le291** [comment]
Hi! Why was you close this issue? it still does not work via Nuget.

**Comment by FezVrasta** [comment]
What do you mean? Others reported that is working properly now.
