### ISSUE TITLE
Popper has `x-arrow="undefined"` as attribute (instead of just `x-arrow`)

### ISSUE THREAD

**Issue by JSteunou** [FezVrasta/popper.js#39]
Do not see any negative impact, but the attribute ~~is here is~~ value set to `undefined`

**Comment by FezVrasta** [comment]
Sorry I don't get what are you talking about...

**Comment by JSteunou** [comment]
Can see why, it's barely correct English :D 

Was saying I have `x-arrow="undefined"` when look at the DOM. Do not know what's the impact, but it might be a symptom have a bug, isnt it?

**Comment by FezVrasta** [comment]
I see, it's just the way I add the attributes... It's not nice to see but nothing bad happens.
