### ISSUE TITLE
Syntax errors in IE11

### ISSUE THREAD

**Issue by psuplat** [FezVrasta/popper.js#393]
Hi,

I am getting the syntax error from popper.js file when using IE11 (it work fine in Edge though).

```
Syntax error: (34,21)
var isNative = (fn => nativeHints.some(hint => (fn || '').toString().indexOf(hint) > -1));
```

Works perfectly fine in Chrome,FF, Opera and Edge. Normally I wouldn't bother, but sadly in corporate environments IE is a standard whether you like it or not :(

**Comment by FezVrasta** [comment]
You are using the wrong build. You should use the UMD or ESM.

**Comment by kudorgyozo** [comment]
Hi, how do you change the build? Thanks

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/popper.js#dist-targets
