### ISSUE TITLE
js error when title attribut is empty

### ISSUE THREAD

**Issue by jipexu** [FezVrasta/popper.js#397]
Hi
for info 
last version of popper.js 1.12.3 in BS 4 beta context
in html if we have empty title attribut :  title="" data-toggle="tooltip"
we get the js error in console

TypeError: undefined is not an object (evaluating 'e.indexOf')
v — popper.min.js:4:4370
onLoad — popper.min.js:4:19018
(fonction anonyme) — popper.min.js:4:12843
forEach
t — popper.min.js:4:12798
show — bootstrap.min.js:6:42233
_enter — bootstrap.min.js:6:46163
(fonction anonyme) — bootstrap.min.js:6:45123
handle — jquery.min.js:3:13783
dispatch — jquery.min.js:3:10321
10

Thanks

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
