### ISSUE TITLE
js error when title attribut is empty

### ISSUE THREAD

**Issue by jipexu** [FezVrasta/popper.js#398]
for info
last version of popper.js 1.12.3 in BS 4 beta context
in html if we have empty title attribut : title="" data-toggle="tooltip"
we get the js error in console

### CodePen demo

https://codepen.io/pen?template=wGqJEz

### Steps to reproduce the problem

1. in html any title attribut empty with data-toggle="tooltip"
2.  
3.  

### What is the expected behavior?
dont have js error in the console

we get the js error in console

TypeError: undefined is not an object (evaluating 'e.indexOf')
v — popper.min.js:4:4370
onLoad — popper.min.js:4:19018
(fonction anonyme) — popper.min.js:4:12843
forEach
t — popper.min.js:4:12798
show — bootstrap.min.js:6:42233
_enter — bootstrap.min.js:6:46163
(fonction anonyme) — bootstrap.min.js:6:45123
handle — jquery.min.js:3:13783
dispatch — jquery.min.js:3:10321
10

### Any other comments?
sorry to not use the template  :  https://codepen.io/pen?template=wGqJEz

**Comment by FezVrasta** [comment]
Sorry without the template I can't help you.

**Comment by jipexu** [comment]
^this template is not usefull i need to make a new one ..

**Comment by FezVrasta** [comment]
if the error can't be reproduced with the provided template it means the error is not in Popper.js code, but in others code.

Please open the issue in the right repository.

**Comment by jipexu** [comment]
in bootstrap ?

**Comment by FezVrasta** [comment]
yes probably

**Comment by jipexu** [comment]
thanks i will retry the template ... and if i can not get will submit on BS ...

**Comment by jipexu** [comment]
@FezVrasta   many sorry i was wrong i used data-placement="top-start" (who is not implemented in BS) so i got this error :-(
