### ISSUE TITLE
Css property transform: translate cause Tooltip to be misplaced

### ISSUE THREAD

**Issue by cnicodeme** [FezVrasta/popper.js#40]
Hey :)

When animating elements using the CSS property transform: translate(), and once the animation is done, trying to show the tooltip cause the calculation of the position of the tooltip to be (way) wrong.

Here's a fiddle to show the issue : https://jsfiddle.net/wtb6rzo5/

It's worse when placing it on "top" (try, it won't show the tooltip because it's placed behind the "javascript" code part of jsfiddle).

I'll try to see if I find the reason, but maybe you'll be faster than me!

**Comment by FezVrasta** [comment]
Adding `position: relative` to the `fade-in` element seems to fix the problem.
Logically you have to manually trigger an update once the animation is finished, otherwise the popper will not update its position.

Can it be a solution?

**Comment by cnicodeme** [comment]
I call `Popper.update()` just before creating the new Popper but it does fix the issue (on my code, I call Popper to display errors in a form after a submission, so the form did not move from once it was display : When Popper is called, the form is already in place, like in the fiddle).

But maybe there is something else to do than calling `update()` ?
(see: https://jsfiddle.net/wtb6rzo5/1/ )

**Comment by cnicodeme** [comment]
With `position: relative` on .fade, the tooltip is placed on top of the input (on my screen) : https://jsfiddle.net/wtb6rzo5/2/

And if I add `position: relative` AND `popper.update()`, everything seems to work fine : https://jsfiddle.net/wtb6rzo5/3/

**Comment by FezVrasta** [comment]
yup that's exactly what I meant, you have to trigger an update on an existing instance of Popper.js.

`Popper.update()` does nothing, `var popper = new Popper(); popper.update()` updates the popper.
