### ISSUE TITLE
Popper position update does not position itself entirely in viewport 

### ISSUE THREAD

**Issue by atomiks** [FezVrasta/popper.js#401]
### CodePen demo

https://codepen.io/anon/pen/YxvXRe

### Steps to reproduce the problem

1.  Resize the browser window to make it smaller (with sufficient speed)

### What is the expected behavior?

The popper's position should update to the correct position (entirely inside the viewport) instantly

### What went wrong?

It 'lags' and part of the popper is left outside the viewport as the window is resized

### Any other comments?

This seems to be a regression which was fixed by this issue: https://github.com/FezVrasta/popper.js/issues/251

**Comment by FezVrasta** [comment]
Yes it #251 again... Fixing #302 reintroduced this one, damn it.
