### ISSUE TITLE
Popper break swipper

### ISSUE THREAD

**Issue by lucasthibau** [FezVrasta/popper.js#403]
I'm starting to try bootstrap 4, that requires popper. In my project I'm trying to use the swipper to, but when I include the popper, my swipper stop working. If i remove popper, the bootstrap give-me an error.

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.

**Comment by lucasthibau** [comment]
Sorry for the trouble, you can keep this closed, I changed to the CDN version of everithing and it worked like a charm... Dont know what was happening...
