### ISSUE TITLE
attachToScrollParents causes "too much recursion"

### ISSUE THREAD

**Issue by Apollo3zehn** [FezVrasta/popper.js#404]
I am using asp.net core in combination with Bootstrap 4.0.0-beta and Knockoutjs. When a popup tries to open, I get the error "too much recursion". I tracked that bug down to line 977 in umd\popper.js where the nodeName is checked:

```
function attachToScrollParents(scrollParent, event, callback, scrollParents) {
  var isbody = scrollParent.nodeName === 'body';
  var target = isbody ? window : scrollParent;
  target.addEventListener(event, callback, { passive: true });

  if (!isbody) {
    attachToScrollParents(getScrollParent(target.parentNode), event, callback, scrollParents);
  }

  scrollParents.push(target);
}

```

My body node name is actually "BODY" and therefore the check fails. If I modify the line to:

` var isbody = scrollParent.nodeName === 'body' || scrollParent.nodeName === 'BODY';`

everything is working fine. I don't know why "BODY" is returned but this happens with newest Firefox and Chrome.

**Comment by FezVrasta** [comment]
Please fill out the issue template as required, I'll reopen it once done.

**Comment by Apollo3zehn** [comment]
Sorry, for ignoring that template. I did not read it carefully. 
Regarding the issue: I think I caused it by myself. Today in my project I accidentially replaced all occurrences of "body" with another string. After I realized my mistake I changed it back ... not considering the capitalization.
