### ISSUE TITLE
SyntaxError: export declarations may only appear at top level of a module-version 1.12.5- bootstrap v4

### ISSUE THREAD

**Issue by danuddara** [FezVrasta/popper.js#409]
### Steps to reproduce the problem
1.   create a HTML5 template with the normal syntax
2.   download and attach jquery and bootstrap v4
3.   try to use the new version popper.js 1.12.5.
4.   it gives this error " SyntaxError: export declarations may only appear at top level of a module" in the console.

### What went wrong?

bootstrap won't load because it requires the popper.js file.  I used the cdn version for version 1.12.5 and it worked https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.5/umd/popper.min.js

**Comment by FezVrasta** [comment]
Please provide more details to reproduce the problem. Otherwise I can't help you

**Comment by danuddara** [comment]
https://getbootstrap.com/docs/4.0/getting-started/introduction/ 

copy the 'starter template' and create a html page.
 in the ' script tag' there and try to use the new version of popper.js without using the CDN in the template.
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  </head>
  <body>
    <h1>Hello, world!</h1>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="js/popper.min.js"></script> <!--download and use the new version-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </body>
</html>
```

Hope that is enough to reproduce this problem and go to web developer console in firefox. and in there you will see the error.  download the new version of popper.js and link it as in the script.

**Comment by bayangan** [comment]
The error from chrome is: popper.min.js:276 Uncaught SyntaxError: Unexpected token export
when followed is from this line
export default Popper

Do we need to use transpiler for this? Is there any commonJS solution?

**Comment by bayangan** [comment]
I solved this add 1 more script, popper-utils before popper js. the transpiler is in the utils file. I use UMD version.

**Comment by FezVrasta** [comment]
Popper-utils is not required. But you have to use the UMD build if you an want to import it from HTML like you are doing. This is clearly explained in the README

**Comment by mcny** [comment]
Sorry for the necromancy but I thought we can revisit it now that bootstrap 4 is live. 

I downloaded popper from https://codeload.github.com/FezVrasta/popper.js/zip/v1.12.9 

![screenshot from 2018-01-18 14-39-45](https://user-images.githubusercontent.com/26206142/35117723-807d4542-fc5d-11e7-84b2-0d93205d49c2.png)


```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Hello, New York!</title>
	<link rel="stylesheet" href="css/style.css">
  <link rel="stylesheet" href="vendor/bootstrap-4.0.0-dist/css/bootstrap.min.css">
  <script src="vendor/jquery-3.2.1.slim.min.js"></script>
  <script src="vendor/popper.js-1.12.9/dist/popper.min.js"></script>
  <script src="vendor/bootstrap-4.0.0-dist/js/bootstrap.min.js"></script>
	<!--[if IE]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>

<body id="home">

	<h1>Welcome</h1>

</body>
</html>
``` 

https://github.com/mcny/mcny.github.io/  

Thank you

**Comment by edwinirausquin** [comment]
is easy to solver, change the the bootstrap o bootstrap.min to bootstrap.bundle or bootstrap.bundle.min becouse this files have content the popper, popper is witch cause the problem
