### ISSUE TITLE
positioned element is misplaced inside scrollable element

### ISSUE THREAD

**Issue by sqal** [FezVrasta/popper.js#41]
Demo with my issue: https://jsfiddle.net/0kL5r8t2/

Basically on my site i have fullscreen chat with position fixed and inside is scrollable area with chat messages. The problem is what you can see in the demo. Tooltip is not sticket to the reference element, but is positioned somewhere outside document body. Position fixed seems to be key issue here, without it tooltips are are positioned correctly. Am I missing some option in Popper initialization? i would appreciate help, tips, how to fix this thing :) Thanks.

**Comment by FezVrasta** [comment]
I think it's fault of some optimization... I'll dig into it

**Comment by sqal** [comment]
@FezVrasta wow I am an idiot! Actually everything works fine https://jsfiddle.net/0kL5r8t2/ in previous fiddle i did not initialize Popper for every element :( But i still have this issue on my site though. I think i need to dig into my CSS. Sorry for false alarm. You can close it for now if you want to.

**Comment by sqal** [comment]
Ok turns out the bug still exists, just is not reproducible on jsfiddle, so I prepared some demo you can take a look at -  https://www.dropbox.com/sh/r6ulun2dxdjavqz/AABnOhD-clSB0OuFACtxhlgMa?dl=0

### steps to reproduce

1. When you open the demo and hover over 'show tooltip' you can see that tooltip is positioned correctly
2. Refresh page and click on 'toggle fixed' button that will apply position fixed to the chat element. Now when you hover over 'show tooltip', tooltip won't show up until you scroll the list up and down and hover over text once again. But even then position of some tooltips is screw up and not every tooltip is showing up.
3. Now go to main.css and remove `position: relative` from `.chat-msg` (note: position: relative could be applied to any child element of .`.chat` or parent element of `.tooltip-trigger` and bug will still occur). Refresh page, click on toggle fixed button and play with the tooltips. Everything is fine now.

So, seems like position: relative is causing the issue, but why? I am looking and can't find fix for this, maybe you have some ideas? i would appreciate if you could take a look this. Thank you.

**Comment by FezVrasta** [comment]
Please provide a codepen/jsfiddle.

**Comment by sqal** [comment]
https://jsfiddle.net/cq4xkcfn/

**Comment by FezVrasta** [comment]
Converted to CodePen, including Popper.js as dependency.
Then, I've changed the position of the tooltip class from `absolute` to `fixed` and everything seems to work fine.

http://codepen.io/FezVrasta/pen/QNJWvJ

I think it's the same issue of #25.

**Comment by sqal** [comment]
Ok position fixed indeed helped, but i also need to trigger `update()` after tooltip is shown. Thank you for your time and help ;)

**Comment by sqal** [comment]
@FezVrasta I just updated to 0.3.7 and something has broken:

```Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined```

in line: https://github.com/FezVrasta/popper.js/blob/master/src/popper.js#L1123

**Comment by FezVrasta** [comment]
Update to 0.3.8, I published the wrong version on NPM
