### ISSUE TITLE
Where to find live example code?  

### ISSUE THREAD

**Issue by oshihirii** [FezVrasta/popper.js#410]
Hello,

Do you have any codepens that have examples of `tooltip.js` and/or `popper.js` usage?

I have added this resource to codepen:

https://cdnjs.com/libraries/popper.js

**JS panel**

```js
var instance = new Tooltip(".my_tooltip", {
    title: "Hey there",
    trigger: "click",
});

instance.show(); 
```

**HTML panel**

```html
<div class="my_tooltip">

</div>
```

And nothing is showing, on click or otherwise.  

Thank You.  

(The above code is the second example here:  https://popper.js.org/tooltip-examples.html)

**Comment by NateWr** [comment]
You also need to load `tooltip.js`. The example page you link loads the following:

```
<script src="https://unpkg.com/popper.js@^1"></script>
<script src="https://unpkg.com/tooltip.js@^1"></script>
```

**Comment by oshihirii** [comment]
I have included the following JS links:

https://unpkg.com/popper.js@%5E1
https://unpkg.com/tooltip.js@%5E1

in this codepen:

https://codepen.io/oshihirii/pen/NabOxd

**HTML**
```html
<div class="my_element">test1</div>
<br><br><br>
<div class="my_element">test2</div>
````

**JS**
```js
new Tooltip(".my_element", {
    placement: 'top', // or bottom, left, right, and variations
    title: "Top",
    html: "<p>hello world!</p>",
    trigger: "hover"
}); 
```

Just get error:

    Uncaught TypeError: reference.addEventListener is not a function
