### ISSUE TITLE
Do you want a lighter Popper.js version?

### ISSUE THREAD

**Issue by FezVrasta** [FezVrasta/popper.js#411]
So, I want to understand if you guys are okay with the current library size (~7KB) or you want a lighter version.

The idea would be to release a popper.slim.js or something similar, with less built-in modifiers (so, less features) or with alternative modifiers that do less stuff.

- 👍 if you'd like a lighter Popper.js
- 👎 if you are fine with the current size or you prefer me to focus on other priorities first (bugs, features)

**Comment by mechanicious** [comment]
_...focus on other priorities first (bugs, features)_ 👍

**Comment by FezVrasta** [comment]
Hi @mechanicious, I already tried to cover all the edge cases I could think of.

If you find uncovered cases feel free to open a issue or directly send a PR

**Comment by aristidesfl** [comment]
> Hi @mechanicious, I already tried to cover all the edge cases I could think of.

+1 for open issues

**Comment by simon1tan** [comment]
How about one that works...

**Comment by FezVrasta** [comment]
I just found out that enabling an option in the minifier I managed to reduce the minified size by 3KB and the compressed size by .3KB (out of the initial 6.3).

A little win at least 😊
