### ISSUE TITLE
Add callback as param to instance.update() / scheduleUpdate() to run once position is updated

### ISSUE THREAD

**Issue by atomiks** [FezVrasta/popper.js#412]
Since updating is async, I'm having trouble implementing what I'd like with the current `onUpdate()` method inside the options which also runs on scroll/resize. I want something to run once on update when it's manually invoked.

Something like:

```javascript
const instance = new Popper(ref, popper)

// Callback runs once the position is updated.
instance.update(() => {
  ...
})
```

Would be quite helpful -- unless you can point me in a better direction here

**Comment by FezVrasta** [comment]
nice idea, if it doesn't take too many LOCs I'm fine with it if someone wants to send a PR

**Comment by FezVrasta** [comment]
The OP closed it. I'm still fine if someone wants to implement it. I already implemented something similar on the `next` branch
