### ISSUE TITLE
tooltip displays at a wrong offset for elements with display set to none

### ISSUE THREAD

**Issue by mechanicious** [FezVrasta/popper.js#413]
### CodePen demo

Note: this pen will not demonstrate the issue when the element is hovered when Tooltip initializes. You might want to reload the frame after the pen loads.

https://codepen.io/anon/pen/NvJeRy?editors=1111

### Steps to reproduce the problem

1.  Set element's style to `display: none` 
2. Instantiate a Tooltip on that element
3. Set element's style to `display: inline-block`

### What is the expected behavior?

At step 3. Tooltip should display at a correct offset i.e. as it would display when the element was set to `display: inline-block` at step 1. to begin with.

### What went wrong?

At step 3. Tooltip displays at a wrong offset.

### Any other comments?
How it is after hover (see codepen):
![image](https://user-images.githubusercontent.com/8450319/30030070-f0bc261c-918b-11e7-8003-5254ac45db6b.png)

How it should be after hover (see codepen)::
![image](https://user-images.githubusercontent.com/8450319/30030104-1339517e-918c-11e7-8c12-f54ab1f702e1.png)

**Comment by FezVrasta** [comment]
Popper.js can't know the position of a `display: none` element, it must be positioned in the DOM to work, and `display: none` removes the element completely from the rendering three.

There aren't solutions, it's a web platform limitation.

**Comment by mechanicious** [comment]
This issue penetrates to Tooltip.js only. Have you considered delaying the positioning of the Tooltip.js to when it becomes available in the rendering tree? Sounds to me like a better solution than placing the element somewhere randomly on the screen. Depending on the neighboring content current solution can lead to awkward issues as you might imagine.

**Comment by FezVrasta** [comment]
I can't know _when_ the element will be visible

**Comment by mechanicious** [comment]
You can do it like this https://jsfiddle.net/z4zeg74w/

**Comment by mechanicious** [comment]
Either way, it seems to me that the simplest solution is to just throw an error–still better than placing the tooltip somewhere randomly on the screen. That way you at least make it clear that you don't support elements with display set to none.

**Comment by FezVrasta** [comment]
Regarding your jsfiddle, it looks like a very specific solution for a very specific context, it couldn't be generalized enough to work in a reliable manner for most of the cases.

I prefer have the consumer properly handle the state of its app to be sure the target element is properly rendered in the page before he tries to use it as reference for a tooltip.

**Comment by mechanicious** [comment]
Although I am not sure what generalization are you referring to, without details I can confirm that this issue is handled by Tippy.js which is also Popper.js-based.

**Comment by FezVrasta** [comment]
use it then, cool

**Comment by mike-robertson** [comment]
I'm also running into this issue where we have a tooltip inside of an accordion which is defaulted to closed (`display: none;`) on page load. Wouldn't it be possible to do a recalculation of the position on a mouse enter or focus or something of the context element? 

One example solution: if at the time the offset is calculated the reference element is not visible, set some sort of state variable like `defaultOffsetPosition = true`. You could check if the reference element is not visible by seeing if the `ClientRect` is set to 0 for everything. Then listen to mouseEnter or something on the reference element. If your state `defaultOffsetPosition` is truthy when that event fires, then you could recalculate the offset.

**Comment by FezVrasta** [comment]
This is all cool stuff and cool ideas. But they are too specific and you can implement them manually
