### ISSUE TITLE
Version 0.3.7 in the npm package uses ```this._trigger``` on line 237

### ISSUE THREAD

**Issue by tiagoengel** [FezVrasta/popper.js#42]
I just update to v0.3.7 and I started to get some errors because in the line 237 of the file ```src/popper.js``` the variable ```this._trigger``` is used,  this variable was removed in v0.3.4. 

The code here is ok, just this file in the NPM package has this problem, the files in the ```build``` folder are ok too.

I tried deleting the node_modules folder and installing again, but it's seems that the problem is realy in the NPM package.

**Comment by FezVrasta** [comment]
Right, I did something wrong during the `npm publish`... I was in the wrong branch.
