### ISSUE TITLE
Download popper.js with composer

### ISSUE THREAD

**Issue by Yukaor** [FezVrasta/popper.js#420]
Hi,

I work on a new project using bootstrap 4 and they recommand to use popper.js with it.

In this project, I only use Composer to manage my dependencies.

So, can you please find a way to upload popper.js on composer ?

Thank's

**Comment by FezVrasta** [comment]
I never used it, can it work with monorepos? `composer.json` will not be in the root directory of the repository.

**Comment by Yukaor** [comment]
I think that you have to create a composer.json in the root directory...
Here is the bootstrap composer.json file : https://github.com/twbs/bootstrap/blob/v4-dev/composer.json (for inspiration lol)
And here is a website to upload it : https://packagist.org/packages/submit

**Comment by FezVrasta** [comment]
In this case it's a no go, I don't intend to support package managers that rely on git to work. I'm even going to get rid of Bower anytime soon in the next major version, so I definitely don't want to add more garbage.
