### ISSUE TITLE
NPM Package: Unexpected token export

### ISSUE THREAD

**Issue by washingtonphp** [FezVrasta/popper.js#424]
### CodePen demo

https://codepen.io/pen?template=wGqJEz

### Steps to reproduce the problem

1.  Download the package via npm (`npm install popper.js --save`)
2.  Import the library into your project `/node_modules/popper.js/dist/popper.js`
3.  See the error in console

### What is the expected behavior?

Library works without errors

### What went wrong?

I suspect that the version builded in npm is wrong

### Any other comments?

Nope

**Comment by FezVrasta** [comment]
Read the usage instructions in the README.

Also. If you use npm you don't have to manually specify the path. Just use the package name and the right file will be picked from package.json
