### ISSUE TITLE
Avoid loading popper.js.map

### ISSUE THREAD

**Issue by tillkruss** [FezVrasta/popper.js#426]
I'm importing Popper and compiling it using Webpack (Laravel Mix):

```js
import Popper from 'popper.js';
window.Popper = Popper;
```

Sadly I see browsers trying to download `popper.js.map` which isn't present on the server. How can I include popper without the reference to the map?

**Comment by FezVrasta** [comment]
This is probably a question for webpack or laravel.

The source maps are provided together with the builds. So they should get included automatically.

**Comment by HarlemSquirrel** [comment]
@tillkruss 
It's been a while but I was finally able to fix this issue myself by excluding source maps for Popper.js. 

https://stackoverflow.com/a/49946403/3446655

I wanted to share this for anyone else who might land here looking for a solution.
