### ISSUE TITLE
Using Tooltip with Bootstrap 2

### ISSUE THREAD

**Issue by ktodyruik-ipl** [FezVrasta/popper.js#427]
Hi,

I have an older project that uses Bootstrap 2 and I'd like to drop Popper/Tooltip into this project.

It appears that the classes conflict with Bootstrap tooltip css classes. Basically, my popper tooltips don't appear.

What canI do to make the popper tooltips (using Tooltip.js), co-exist with the Bootstrap 2 tooltips?

Thanks,

**Comment by FezVrasta** [comment]
You can change the classes used by the library changing the template option and defining your own template
