### ISSUE TITLE
Tooltip closes prematurely in Firefox

### ISSUE THREAD

**Issue by keithws** [FezVrasta/popper.js#431]
### CodePen demo

https://codepen.io/anon/pen/veXEZq

### Steps to reproduce the problem

1.  Use tooltip.js to add a popup element to the reference element
2. Hover over the reference element
3.  Move mouse over the popup element

### What is the expected behavior?

The popup element should remain open and visible as long as the mouse is over the popup element.

### What went wrong?

The popup element closes and disappears as soon as the mouse moves over the popup element.

### Any other comments?

I saw this issue Firefox, but I am unable to reproduce this issue in Chrome nor Safari. This makes it impossible to click links inside a Tooltip in Firefox. Please help.

**Comment by 79229788** [comment]
+1
