### ISSUE TITLE
What is the convention recommended for applying tooltip to multiple instances of a class?

### ISSUE THREAD

**Issue by oshihirii** [FezVrasta/popper.js#432]
### CodePen demo

https://codepen.io/oshihirii/pen/NabOxd

### Steps to reproduce the problem

1.  `var test = $(".frequency")` does not work when passing to `var myToolTip = new Tooltip(test, { ...`
2.  `var test = $(".frequency").eq(0)` does work
3.  What is the convention recommended for applying tooltip to multiple instances of a class?  (in a jQuery environment)

### What is the expected behavior?

That tooltip is applied to each instance of the class.  

### What went wrong?

Tooltip is not applied to each instance of the class.

**Comment by FezVrasta** [comment]
both Popper.js and Tooltip.js don't rely on jQuery, the most they do is to convert the jQuery element wrappers into native JS element references.

If you need to create multiple tooltips you will have to iterate through all of them:

```
$('.frequency').forEach(el => new Tooltip(el));
```
