### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by pkkid** [FezVrasta/popper.js#433]
Just tried to use Popper with bootstrap by including latest popper.js to my page:
```html
<script type="text/javascript" src="/static/popper.js"></script>
```

And got this error in the browser console:
```
Uncaught SyntaxError: Unexpected token export popper.js:2297
```

Other people have opened this bug, and those bug reports all say the same thing, "read the usage section of the README". However, the usage section only shows the code snippet pasted below. **I honestly don't understand how this helps us solve the problem mentioned above.**

> Given an existing popper DOM node, ask Popper.js to position it near its button
> 
> var reference = document.querySelector('.my-button');
> var popper = document.querySelector('.my-popper');
> var anotherPopper = new Popper(reference, popper, {<options_here>});

**Comment by Johann-S** [comment]
please use the UMD dist file of Popper.js

**Comment by pkkid** [comment]
Got it thanks, and sorry for not understanding.

It's on the help page under the "Dist targets" section. The README is a bit confusing because I have no idea what UMD is, so it got overlooked as "never heard of it thing, clearly not what I need." Might be worth calling it out a bit more clearly before Bootstrap4 is out of beta.
