### ISSUE TITLE
How to update individual tooltip html on show() and close individual tooltip?  

### ISSUE THREAD

**Issue by oshihirii** [FezVrasta/popper.js#434]
### CodePen demo

https://codepen.io/oshihirii/pen/gGgGBw

### Steps to reproduce the problem

I have two questions:

Q1: "How do i update a tooltip's `html` when showing it"?
Q1:  Steps to reproduce:  
1.  Click on a td cell
2.  An html tooltip will show
3.  As there are multiple instances of the tooltip, how do I show custom html for each one when clicking the cell?  Is there an `update()` method available?  

Q2: "When i close the tooltip with `hide()`, i have to click twice on the element to open it again (it is like the toggle status does not change when i use `hide()`) - what is the correct way to `hide()` the tooltip so that the toggle status updates as well?

### What is the expected behavior?

1.  I want each tooltip to be injected with custom html on launch.  
2.  I want the toggle status of the tooltip to change when i use `hide()`

### What went wrong?

1.  I don't know if there is a method available to do this.  
2.  I have to click twice on the toggler after using `hide()` to open the tooltip again

### Any other comments?

I've kept working on the codepen above to achieve the desired functionality, but it uses quite a long approach - if there was default behaviour that achieved the same, it would be great to know how to do it.

**Comment by FezVrasta** [comment]
About Q1: #342
Abot Q2: I can't seem to be able to reproduce it, may you explain how can I reproduce the problem?
