### ISSUE TITLE
How to only allow programmatic control of tooltip show and hide?

### ISSUE THREAD

**Issue by oshihirii** [FezVrasta/popper.js#435]
### CodePen demo

https://codepen.io/oshihirii/pen/gGgGBw

### Steps to reproduce the problem

1.  [Documentation](https://popper.js.org/tooltip-documentation.html) states that trigger has four options (click, hover, focus, manual)
2.  If I define: `trigger: "manual"`, the on click event handler that include `$(el).show()` does not show the tooltip.  

### What is the expected behavior?

I want to only show and hide the tooltip programatically.  

I don't want the default behaviour of "toggling" show and hide by clicking on the element.  

### What went wrong?

When I use `trigger: "manual"`, `$(el).show()` does not show the tooltip.

**Comment by FezVrasta** [comment]
I think it should be enough to set `trigger` to `""`, then you show it with `instance.show();`
