### ISSUE TITLE
Reserved Keyword breaks minifying by YUICompressor

### ISSUE THREAD

**Issue by janwidmer** [FezVrasta/popper.js#437]
We are using popper.js within the CMS System AEM. Because of several technical restrictions, we are forced to use YUIcompressor for asset minification in the backend.

YUIcompressor seems to be more strict about reserved keywords and fails to compress javascript code containing reserved keywords as function / property names.

Popper.js  and popper-utils.js seem to contain such function names both in that function:

```
function runModifiers(modifiers, data, ends) {
  var modifiersToRun = ends === undefined ? modifiers : modifiers.slice(0, findIndex(modifiers, 'name', ends));

  modifiersToRun.forEach(function (modifier) {
    if (modifier.function) {
      console.warn('`modifier.function` is deprecated, use `modifier.fn`!');
    }
    var fn = modifier.function || modifier.fn;
    if (modifier.enabled && isFunction(fn)) {
      data = fn(data, modifier);
    }
  });

  return data;
}
```
Would it be possible to replace them by this code:

```diff
function runModifiers(modifiers, data, ends) {
  var modifiersToRun = ends === undefined ? modifiers : modifiers.slice(0, findIndex(modifiers, 'name', ends));

  modifiersToRun.forEach(function (modifier) {
-   if (modifier.function) {
+   if (modifier['function']) {
      console.warn('`modifier.function` is deprecated, use `modifier.fn`!');
    }

-   var fn = modifier.function || modifier.fn;
+   var fn = modifier['function'] || modifier.fn;
    if (modifier.enabled && isFunction(fn)) {
      data = fn(data, modifier);
    }
  });

  return data;
}
```

This passes the YUIcompressor.

### Steps to reproduce the problem

1.  Code can be tested here: https://99webtools.com/yui-compressor.php#output

### What is the expected behavior?

Minification by the YUIcompressor works without errors

### What went wrong?

Javascript code contains functions named after reserved keywords.

**Comment by FezVrasta** [comment]
That's a very good idea! Please may you send a PR for it?

**Comment by janwidmer** [comment]
I will do that next week :-)

**Comment by janwidmer** [comment]
Pullrequest created: https://github.com/FezVrasta/popper.js/pull/444
