### ISSUE TITLE
Tooltip with placement top, occasionally shows tooltip to the right

### ISSUE THREAD

**Issue by oshihirii** [FezVrasta/popper.js#439]
### CodePen demo

I respect the protocol required for submitting issues, however I think the instance where I am experiencing the behaviour is too complicated to reproduce in a codepen.

I am wondering, therefore, if this could be a 'generic' issue that could be fixed with some sort of "position reset" on showing the tooltip or some other generic solution? 

I instantiate tooltip on click of table `td` element with:

```js
var tooltip = new Tooltip($this, {
    placement: 'top',
    title: html,
    html: true,
    trigger: "manual",
    delay: { show: 0, hide: 0 },
    // attach this to a specified container, otherwise it messes with table width 
    // when showing the tooltip
    container: $(".my_dynamic_content")[0],
    boundariesElement: 'window'	// i tried adding this as a fix, but it didn't seem to have an effect		
}); 

// i have to do this otherwise the tooltip displays to the top left of the cell, 
// rather than the top center of the cell - it's like it doesn't have time to get ready or something
tooltip.show().hide(); 

// show the tooltip after a pause
setTimeout(function(){ 
tooltip.show();
}, 100);

```

I create the tooltip on clicking a table cell, and then, on subsequent clicks, show the existing tooltip (using the `aria-describedby` attribute of the cell for reference).  

### Steps to reproduce the problem

1.  Click on table cell

### What is the expected behavior?

I expect the tooltip to consistently show at either the top or the bottom of the cell.  

### What went wrong?

The animated gif below shows that sometimes the tooltip shows to the right of the cell (undesired), rather than the top or bottom of the cell.   After being positioned to the right, when scrolling up or down, it corrects itself and moves to the top or bottom.  

![popper to the side](https://user-images.githubusercontent.com/5090307/31042155-bb2fa20e-a5e4-11e7-852b-f9346ecb0268.gif)

### Any other comments?

Possibly relevant CSS information:

The `td` position is `relative`. 

The `tr` display is `table-row`

The `tbody` display is `table-row-group`

The `table` display is `table`

The div containing the table does not have position defined.  

The div containing the above div has these properties:

```css
box-sizing: border-box;
width: 100%;
max-width: 100%;
```

All the above sits in an `li`, within a `ul` (both of which do not have position defined) that it used to display content in an "accordion" style.  

The container of the above does not have position defined, but also has these properties:

```css
box-sizing: border-box;
width: 100%;
max-width: 100%;
```
The div `.my_dynamic_content`, which is defined as the tooltip `container`, has the following properties:

```css
overflow-y: auto;
height: calc(100% - 104px);
```
The container of the above is `position: relative` and then there are a few more divs without position defined before getting to `body` which also has no position defined.  

The first div , the site container, defined after `<body>` has these properties:

```css
background: #eee;
height: 100vh;
```

Is it possible to define rules regarding:

- What should the CSS properties be of the element that tooltip is created on?
- What should the CSS properties be of the `container` element defined in tooltip instantiation?

Would this fix the problem?  

**Edit:**  I also tried setting tooltip container to `container: $("body")[0]` with `position:relative` on `body` and have the same issue.

**Comment by FezVrasta** [comment]
Hi, I'm sorry but if it is too complicated for you to reproduce, you can't imagine how difficult can be to me to help you.

Please try to create a reproducible example on CodePen and open a new issue then.

**Comment by oshihirii** [comment]
Thanks for your reply, I've tried to recreate the issue on Codepen, but perhaps because the result is in a wrapper, the problem does not occur - are there some basic "rules" about what css characteristics (height, width, position, display etc) the highest parent of the tooltip should have? Thanks!
