### ISSUE TITLE
How to use modifiers in tooltip.js?

### ISSUE THREAD

**Issue by oshihirii** [FezVrasta/popper.js#440]
### CodePen demo

https://codepen.io/oshihirii/pen/aLwPjv

### Steps to reproduce the problem

1.  Click on tooltip

### What is the expected behavior?

No arrow is shown.

### What went wrong?

Arrow is shown.

### Any other comments?

How do you use modifiers in tooltip.js?

I tried to disable the arrow with the following (just to learn how modifiers work) and the arrow is still showing:

```js
var tooltip = new Tooltip($this, {
    placement: 'top',
    title: html,
    html: true,
    trigger: "manual",
    delay: { show: 0, hide: 0 },
    container: $("body")[0],
    popperOptions: {	
    	modifiers: {
    arrow: { enabled: false }
  }
}
}); 
```

Tooltip documentation:

https://popper.js.org/tooltip-documentation.html

says:

> options.popperOptions
> Object {}
> Popper options, will be passed directly to popper instance. For more information refer to Popper.js’ options docs

Popper documentation shows this example of modifiers:
```js
new Popper(ref, pop, {
  modifiers: {
    preventOverflow: { enabled: false }
  }
})
```

**Comment by FezVrasta** [comment]
Related to #328

**Comment by FezVrasta** [comment]
Actually, let's close this one and keep #328 as reference for the bug, so that we don't make confusion.
