### ISSUE TITLE
Performance slow because large quantity popper.

### ISSUE THREAD

**Issue by adrianoresende** [FezVrasta/popper.js#441]
![image](https://user-images.githubusercontent.com/798755/31082460-79607222-a765-11e7-8ce1-12d68b151664.png)

### The problem

Each title in list inside day has a popper, when there is a large quantity, the performance is slow.

From time to time the page gets overwhelmed due to the amount of popper executed, perceiving small freezing.

### What is the expected behavior?

Is it possible to run a popover script for all or just an HTML for all relationships or some more efficient execution? For better performance

**Comment by FezVrasta** [comment]
Hi, you may better create the Popper.js instance when actually needed, and [destroy](https://popper.js.org/popper-documentation.html#Popper.destroy) or [`disableEventListeners()`](https://popper.js.org/popper-documentation.html#Popper.disableEventListeners) when the popper is hidden.
