### ISSUE TITLE
Cannot set left offset value more when reference width

### ISSUE THREAD

**Issue by romanlex** [FezVrasta/popper.js#442]
Hello. I'm trying change popper position with offset.fn
I send PR in bootstrap dropdown menu https://github.com/twbs/bootstrap/pull/24208 for use offsets.fn function and use it
```javascript
const dropdownMegaToggle = $('.dropdown-toggle--mega');
dropdownMegaToggle.dropdown({
    offsetFn: function(data) {
        let popper = data.popper;
        popper.position = 'fixed';
        let buttonOffset = dropdownMegaToggle.offset();
        popper.top = buttonOffset.top + 60;
        popper.left = 1000;
        return data
    }
});
```
But my offset positioning not work. I can set any negative value for offset left, but can set more when reference.width (it's 90px)
![image](https://user-images.githubusercontent.com/3369304/31088966-25ecf232-a7ab-11e7-956b-95522d3bb186.png)

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
