### ISSUE TITLE
How to set popper max-height to prevent out of boundaries

### ISSUE THREAD

**Issue by urbany** [FezVrasta/popper.js#446]
### CodePen demo

https://codepen.io/jldteixeira/pen/ZXaJWa

### Steps to reproduce the problem
I want to add a "max-height" style attribute to my popper so it stays inside it's boundaries instead of overflowing.
I tried searching and doing it myself, but couldn't find a solution.
I tried to override the computeStyle.fn modifier, but then the default computeStyle doesn't run :s

### What is the expected behavior?

I want the popper to have the max-height that will make it all visible inside its boundaries.

### What went wrong?

Can't find a modifier to make that happen. Tried overriding the computeStyle modifier, but then I loose all the default computeStyle wich I still need.

### Any other comments?

There is probably a way of overriding the computeStyle and still have the default computeStyle but I couldn't find it after reading the docs and searching the repository.

Thank you very much in advance!

**Comment by FezVrasta** [comment]
https://codepen.io/FezVrasta/pen/eGeEGr

**Comment by urbany** [comment]
Thanks! It was not really clear to me that I could just make up a modifier, maybe an example like that would clear it up for lots of people.

PS: Would it be possible to add the boundariesElm offsets to data.offsets?

Thank you so much again for your time, love the plugin!

**Comment by tomaskikutis** [comment]
How does one make this work with flip enabled? I want Popper to drop to the direction where more space is available and make the content scrollable.

I ended up doing the calculations manually before Popper runs so flip works properly. This doesn't work with events since Popper can't decrease the maxHeight.

```
const rect = this.triggerElement.getBoundingClientRect();

const viewportHeight = document.documentElement.clientHeight;
const viewportWidth = document.documentElement.clientWidth;

const availableSpaceTop = rect.top - padding;
const availableSpaceBottom = (viewportHeight - rect.bottom) - padding;

const availableSpaceLeft = rect.left;
const availableSpaceRight = viewportWidth - rect.right;

this.wrapper.style.maxHeight = Math.max(availableSpaceBottom, availableSpaceTop) + 'px';
this.wrapper.style.maxWidth = Math.max(availableSpaceLeft, availableSpaceRight) + 'px';
this.wrapper.style.overflow = 'auto';

this.popperInstance.scheduleUpdate();
```

Is there a proper solution for this?
