### ISSUE TITLE
Retrieve the Tooltip Element

### ISSUE THREAD

**Issue by rmanenti** [FezVrasta/popper.js#447]
Hello there,

   I have started using Tooltip.js and would like to thank you for such a great work. However, I could not find  a function to retrieve the generated tooltip element. Is there one or could you please create it? Otherwise, I have to show it, find, and hide it again in order to store the reference.

Best regards.

**Comment by FezVrasta** [comment]
It's not a pubic API, but you can use the `_tooltipNode` property.

https://codepen.io/FezVrasta/pen/QqYWGo

**Comment by rmanenti** [comment]
Thank you!
