### ISSUE TITLE
removeOnDestroy breaks in IE

### ISSUE THREAD

**Issue by Nannakuhtum** [FezVrasta/popper.js#45]
When I have 'removeOnDestroy' options added for a popper I get 

> TypeError: Object doesn't support property or method 'remove'

in IE.

```
// remove the popper if user explicity asked for the deletion on destroy
        if (this._options.removeOnDestroy) {
            this._popper.remove();
        }
```

I had to apply the polyfill suggested in https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove to make it work.

Please fix or mention this polyfill in documentation.

**Comment by FezVrasta** [comment]
Which version of IE?

**Comment by Nannakuhtum** [comment]
IE 11.

**Comment by FezVrasta** [comment]
Added a section in the readme:
https://github.com/FezVrasta/popper.js/blob/master/README.md#internet-explorer
