### ISSUE TITLE
Are there any basic CSS characteristics that a tooltip container should have to ensure correct positioning?

### ISSUE THREAD

**Issue by oshihirii** [FezVrasta/popper.js#451]
In regards to this [closed issue](https://github.com/FezVrasta/popper.js/issues/439) where a tooltip is not displaying correctly in a scrollable area, I've tried to recreate the issue on codepen (it took an hour or so, so i did try), but, perhaps because the result is in the codepen result wrapper, the problem does not occur.

I am wondering:

- Are there some basic "rules" about what CSS characteristics (`height`, `width`, `position`, `display` etc) the tooltip `container` should have? 

- Is the position actually calculated in relation to the element defined in the `container` option, the "clickable" element, or another element?  (if so what CSS properties should it have)  

- When is the position calculated?  I am playing around with the `height`, `width`, `display`, `position` properties of parent elements in Chrome developer tools hoping that one of these combinations will make the tooltip position correctly but it is not having an effect (am i just wasting my time doing that because the positioning process starts on instantiation?)

Thanks!

**Edit:** My last attempt involved adding a div called `popper_container` as the first direct child of `<body>` (with `style="width:100%; height: 100%; position:relative"`) and setting `$("#popper_container")[0]` as the value of the `container` option.  I still get the same undesired behaviour.

**Comment by FezVrasta** [comment]
Nope, Popper.js doesn't require any specific CSS to work.

It just need both reference and popper elements to be rendered in the DOM (no `display: none`) and in some cases there could be problems if the elements have `transform`s applied to it.
