### ISSUE TITLE
Wrong placement at the first time but not the second time

### ISSUE THREAD

**Issue by Johann-S** [FezVrasta/popper.js#459]
Hi @FezVrasta, we have a strange bug with our Dropdowns on Bootstrap, when we click the first time the dropdown is not right placed but when click the second time that's fine

### CodePen demo

![gif](https://user-images.githubusercontent.com/1689750/31601811-67d65fac-b25b-11e7-8894-ee77739d32c3.gif)

Sorry but this Codepen contain Bootstrap with Popper.js 

https://codepen.io/Johann-S/pen/WZdrKj

**Comment by FezVrasta** [comment]
I can't reproduce it. From what I see it may be related to the fact that you are initializing Popper.js when the element is still hidden (or is being shown but it's still in the process).

On more powerful PCs maybe you can't reproduce the problem because everything is snappy enough, on slow PCs maybe Popper.js gets initialized while the element is still hidden.

You may have to check if this is the case. I would expect something like this in your code:


```
popper.show();
new Popper(reference, popper);
```

**Comment by Johann-S** [comment]
Ok thank you for your answer @FezVrasta ! :+1: 
To fix that issue I added that : 
```
        onCreate: () => {
          this._popper.scheduleUpdate()
        }

**Comment by FezVrasta** [comment]
Umh... a bit hacky but it should work if you don't mind an additional repaint.

The ideal solution would be to wait for the popper element to be properly showed before attempting to position it.

But then you have to:

1. Set its `visibility` to `none` or `opacity` to `0`
2. set its `display` to `block`
3. Wait for it to be rendered
4. Init Popper.js
5. Set its `visibility` to `visible` or `opacity` to `1`

**Comment by Johann-S** [comment]
Yep seems way better than my solution but I think for our Dropdown plugin it will be enough 👍

**Comment by miracle2k** [comment]
@FezVrasta I am struggling with this; Any suggestion as to how step 3  should be done? Is there some event I can listen to? I also found this commit:

https://github.com/FezVrasta/popper.js/commit/660849a3e6d73d0b6d502b2db0ed1d6cd330be9d

which seems to suggest that popper will take care of this for me.

**Comment by FezVrasta** [comment]
The commit you refer to is very old, that part of code wasn't reliable and has been removed.

Probably it's enough to use a `requestAnimationFrame` to delay the Popper.js initialization.

```js
popper.style.display = 'block';
requestAnimationFrame(() => new Popper(reference, popper));
```
https://codepen.io/FezVrasta/pen/YEwzrN

**Comment by zanderwar** [comment]
(Google brought me here)

**Bootstrap 4:**

I had to wrap it in `.navbar` to prevent this behavior within a table row

```
<nav class="navbar p-0 justify-content-end">
    <div class="dropdown">
        <button class="btn btn-no-style btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           Dropdown
        </button>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="#">Dropdown Item</a>
        </div>
    </div>
</nav>
```
