### ISSUE TITLE
Result of getOuterSizes is not consistent

### ISSUE THREAD

**Issue by rafaelverger** [FezVrasta/popper.js#46]
### Steps to reproduce the problem

1.  Go to https://popper.js.org/
2.  Scroll page to section **POPPER ON YOUR SIDE!**
3.  Wait popper elements on the left side toggle
4.  When a new popper appears, scroll the page a bit

*the change is more notable when it is the left popper that is visible*

### What is the expected behavior?

Popper element stays on the same position

### What went wrong?

Popper element reposition itself due to changes in getComputedStyle result

### Any other comments?

Check this gif:
![image](https://s3.amazonaws.com/f.cl.ly/items/1R3y0b2d2Z3D2S1w3s3C/Screen%20Recording%202016-05-06%20at%2002.41%20PM.gif?v=88c2ca12)

**Comment by rafaelverger** [comment]
I believe that the error is related to the use of `root.getComputedStyle` method with an invisible element;

**Comment by marciovicente** [comment]
I got the same error!
