### ISSUE TITLE
Can't install popper.js via NuGet into web project that targets .NET Framework 4.7

### ISSUE THREAD

**Issue by BY-DGR** [FezVrasta/popper.js#464]
### CodePen demo

Not applicable.

### Steps to reproduce the problem

1. Create a new web project in VS2017 that targets .NET Framework 4.7.
2. Open NuGet Manager and try to install popper.js.

### What is the expected behavior?

popper.js is successfully installed.

### What went wrong?

Got the error message:

Could not install package 'popper.js 1.11.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

### Any other comments?

No.

**Comment by Johann-S** [comment]
You should use the latest release of Popper.js which fix that issue :wink: 
 BTW if you install Popper.js throw Bootstrap, beta 2 is shipped with Popper.js since yesterday :+1:
