### ISSUE TITLE
Wrong documentation for modifier “order”

### ISSUE THREAD

**Issue by djibarian** [FezVrasta/popper.js#469]
The documentation stands for `order: 800` when setting up a React `applyStyle` modifier, but this order currently throws an error due to the `computeStyle` modifier having an order of 850, which forces it to run afterwards. The error thrown is `TypeError: undefined is not an object (evaluating 'data.offsets’)`.

If `order` is omitted when setting up the new modifier, everything seems to work fine (setting it up to 900 too, the same as the `applyStyle` modifier).

Apart from noting that the documentation is wrong, I would like to ask what is the effect of not setting the `order` parameter when setting up a new modifier?

**Comment by FezVrasta** [comment]
Yes that's not right, `applyStyle` has `order: 900`

**Comment by FezVrasta** [comment]
I just doublechecked it, and the documentation provides the correct value.

https://popper.js.org/popper-documentation.html#modifiers..applyStyle

**Comment by djibarian** [comment]
Not in the React example in the docs.

**Comment by FezVrasta** [comment]
Ah!
