### ISSUE TITLE
Popper overflows viewport when reference element is inside a right aligned flex item

### ISSUE THREAD

**Issue by jjenzz** [FezVrasta/popper.js#471]
### CodePen demo

https://codepen.io/jjenzz/pen/QqXGKW

### Steps to reproduce the problem

1. Configure a popper with "bottom" placement
2.  Add the reference and popper elements into a flex **item**
3.  Right align the flex item (e.g. `margin-left: auto` or `justify-content: flex-end` on the flex **container**)

### What is the expected behavior?

I would expect the popper to be positioned within the viewport

### What went wrong?

On page load, the popper overflows the viewport and there is horizontal scroll

### Any other comments?

Resizing the window appears to fix the issue.

**Comment by atomiks** [comment]
This is #401 , I think it should be reopened since it was reverted in `1.12.5`

**Comment by FezVrasta** [comment]
#251 is tracking it.
