### ISSUE TITLE
Question: Is it possible to configure popper to only align vertical axis?

### ISSUE THREAD

**Issue by burlesona** [FezVrasta/popper.js#472]
Sorry to ask this via a Github issue, as I didn't see any forum, google group, etc. place to ask a question.

I was interested in creating a layout with text content on the left and comments on the right, where comments would basically be attached to a particular paragraph. Essentially, without messing with the DOM of the content on the left, I want to position comments on the right beside the paragraph they refer to.

Popper is getting in the ballpark via the boundaries element, but I'm not having any luck getting the poppers to set only the vertical offset and thus allow the boundary element to define the position on the horizontal axis.

I realize this is pretty tricky since you'd really need to do relative positioning instead of absolute, and then just offset top / translateY rather than both x and y.

If anyone has done something similar and could point me to how to set it up, that would be awesome, and I'd be happy to expand that into docs that could be added to the project for other folks to benefit. Or if this is just not possible and I need to look elsewhere, that would also be great to know.

And if asking questions via Github is strictly off limits for this project, I apologize and won't take offense at this being closed right away :)

**Comment by FezVrasta** [comment]
May you attach some picture/example to better understand the requirement please?

**Comment by namnm** [comment]
@FezVrasta I think I need this.
Imagine we have a table header with position fixed, but we need to scroll it horizontally. Then I use popper to reposition it, but I only need the horizontal axis.
The same case for vertical axis I think.
