### ISSUE TITLE
Make it clear Yarn is required to setup the repository

### ISSUE THREAD

**Issue by ndmax** [FezVrasta/popper.js#474]
### Steps to reproduce the problem

1.  `git clone https://github.com/FezVrasta/popper.js.git`
2.  `cd popper && npm install`
3.  `lerna run build`

### What is the expected behavior?

Production files are compiled into popper/dist.

### What went wrong?
It looks like the build script is not installing [eslint-config-popper](https://www.npmjs.com/package/@popperjs%2Feslint-config-popper)

`lerna ERR! Cannot read config file: {...}/popper/packages/popper/.eslintrc.js`
`lerna ERR! Error: Cannot find module '@popperjs/eslint-config-popper'`

### Any other comments?

`npm i @popperjs/eslint-config-popper --save-dev`
`lerna run build`
`lerna success run Ran npm script 'build' in packages:`
`lerna success - popper.js`
`lerna success - tooltip.js`

**Comment by FezVrasta** [comment]
You need yarn to properly install the dependencies

**Comment by FezVrasta** [comment]
Now `npm install` will fail, and the `CONTRIBUTING.md` makes it clear Yarn is required.

**Comment by ndmax** [comment]
I'm having some trouble getting this to work.

## Setup
Then run `yarn` to install the needed dependencies.
{"Then" implies there is a previous step... am I missing something?"}

Okay so:

`git clone https://github.com/FezVrasta/popper.js.git testpopper`
`cd testpopper && yarn install` (or) `yarn`

returns:

`$ which-pm-runs --is yarn`
`/bin/sh: 1: which-pm-runs: not found`
`error Command failed with exit code 127.`

Yarn (and which-pm-runs) are installed globally and locally.  

How can I get this thing to build?

**Comment by FezVrasta** [comment]
Thanks for the follow up. I fixed the typo in the documentation and pushed a fix for the `which-pm-runs` missing.

**Comment by ndmax** [comment]
Thanks for the response!  It's building now.

In trying to find a solution, I discovered the `which-pm-runs-cli` package, which is needed (instead of `which-pm-runs`).  

And I also think I'm really going to like yarn...
