### ISSUE TITLE
Tooltip update or scheduleUpdate on DOM or style change

### ISSUE THREAD

**Issue by loftyduck** [FezVrasta/popper.js#476]
### CodePen demo

https://codepen.io/lofty/pen/eeNxwo

### Steps to reproduce the problem

When using Tooltip is it possible to manually trigger popper.update or popper.scheduleUpdate so that if the reference element moves via a style change or DOM change that the tooltip would reposition?

The codepen shows it working with Popper but I was hoping Tooltip would be able to get a reference to the underlying popper.  Maybe I'm approaching this the wrong way?

**Comment by FezVrasta** [comment]
I think you can access the instance with `.popperInstance`

**Comment by loftyduck** [comment]
You're right, thank you!

**Comment by ashclarke** [comment]
@FezVrasta - Is this still available? It shows as `undefined` for me.

Popper.js - v1.14.1
Tooltip.js - v1.2.0 via unpkg.

Actually, after reviewing what is [spit out by unpkg](https://unpkg.com/tooltip.js@1.2.0), I believe it might be because a property is not explicitly created for it.

**Comment by FezVrasta** [comment]
You must access the instance, not the constructor. You'll find `popperInstance` inside it.

**Comment by ashclarke** [comment]
@FezVrasta - *facepalm* - I was accessing the `popperInstance` property, before ever calling `.show()` 🙄

Wrapped with a check for `_isOpen`!

**Comment by FezVrasta** [comment]
Oh, I see... Yes that's confusing, I don't particularly like the way it works right now, but 🤷‍♂️
