### ISSUE TITLE
Intro to modifiers

### ISSUE THREAD

**Issue by oskarkrawczyk** [FezVrasta/popper.js#48]
Really like the project, was initially going to integrate Tether+Drop into the new JSFiddle rewrite but eventually decided on using Popper.

You mention "modifiers" a lot on the page, docs and in issues, any chance for a intro to writing modifiers?

**Comment by FezVrasta** [comment]
Hi, thanks for your interest.

Here there's an example for a simple modifier:
https://github.com/FezVrasta/popper.js/issues/23#issuecomment-209565341

You are right, there's not explicit documentation about them, I think it would be a good addition to the README.
I'm going to write something about them.

For now, you may want to check out the source code of Popper.js, for example, take a look at the PreventOverflow modifier:
https://github.com/FezVrasta/popper.js/blob/master/src/popper.js#L681-L721

**Comment by FezVrasta** [comment]
I've added a new section in the README:

https://github.com/FezVrasta/popper.js/blob/master/README.md#writing-your-own-modifiers

Let me know if it's clear enough

**Comment by jackson-sandland** [comment]
I've read the documentation and I think including simple specific examples would go a long way to improving usability. For example, I would simply like to modify where the popper appears on the Y-axis. So essentially, making an addition or subtraction to the pixel value. The docs say you can use modifiers.offset and shift along either access but then fail to show the object that the Popper API expects to receive. It's mentioned that `offset` accepts integer value, but no where is it mentioned how to simply specify an axis. How do you accomplish this?
As an example here's how the docs could look:
```
const POPPER_MODIFIERS = {
  offset: {
   y: 10
  }
};
```

**Comment by FezVrasta** [comment]
https://popper.js.org/popper-documentation.html#modifiers..offset

Valid examples are:

```
10
'10%'
'10, 10'
'10%, 10'
'10 + 10%'
'10 - 5vh + 3%'
'-10px + 5vh, 5px - 6%'
```

The correct syntax is:

```
const POPPER_MODIFIERS = {
  offset: {
   offset: 10
  }
};
```

**Comment by jackson-sandland** [comment]
In my case, this moves the popper to right.
How do you specify only operate on the Y axis?
