### ISSUE TITLE
Wrong positioning in Safari

### ISSUE THREAD

**Issue by djibarian** [FezVrasta/popper.js#481]
### Steps to reproduce the problem

1.  In Safari the vertical position is wrongly calculated on rubber scrolling past top. See https://codepen.io/anon/pen/zPrZZK

### What is the expected behavior?

Popper and reference should stay together.

### What went wrong?

Popper stays together with the reference element only when scrolling a few pixels top. Afterwards the popper scrolls with the background and should stay fixed (the reference element is fixed and the popper is inside the reference element)

### Any other comments?

In the codepen, the reference element corresponds to a fixed navigation bar and the popper to a popup menu attached to an option. It is very annoying to see the popup displaced from the navigation bar.

**Comment by FezVrasta** [comment]
What version of Safari?

**Comment by djibarian** [comment]
11

**Comment by FezVrasta** [comment]
May you share a video recording of the problem? I don't seem to reproduce it.

You may use QuickTime or [LiceCAP](https://www.cockos.com/licecap/)

**Comment by djibarian** [comment]
There it is: https://www.dropbox.com/s/cdpejt4zxdiqabz/popper.mov?dl=0

**Comment by FezVrasta** [comment]
I see, I don't think I can do anything for it. It's something handled at OS level and there aren't JS APIs for it. Sorry.

**Comment by djibarian** [comment]
Well getBoundingClientRect() for the reference element is returning correct values always at top-left corner. How is the popper position then calculated in this case to give incorrect values?
