### ISSUE TITLE
enhance arrow positioning way

### ISSUE THREAD

**Issue by Aoyue-Design** [FezVrasta/popper.js#484]
### What went wrong?

In the current versions,
The arrow position is using css "top" or "left" to positioning and transitioning.

I suggest using "transform" like that you positioning popper.
"transform" is the best way to transitioning and positioning smoothly.

It's still not smooth even though you use "will-change" to tell browser in advance. I have experimented that using "top" & "will-change: top" & "transform: translate(0,0)" is slower than "transform(x,y)" & "will-change: transform".

By the way,
I'm developing a plugin based on popper.js,
and popper.js is pretty good. Good job 👋 😄

**Comment by FezVrasta** [comment]
Thanks for the suggestion, may you provide a codepen to show the slowness? I never encountered any problem with the arrow positioning.

**Comment by Aoyue-Design** [comment]
left & top ( 30fps ) : https://codepen.io/chriscoyier/pen/pBCax
transform ( 60fps ) : https://codepen.io/chriscoyier/pen/kyctm

The current popper arrow doesn't set css transition, so positioning through top and left is no problem.
You can observe the different performance from both when setting transition for arrow.

**Comment by FezVrasta** [comment]
Yeah ok but, as you said, we don't have any transition, we are just moving a super small element on a single axis.

That's why I say that I never encountered this slowness.
