### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by Javix** [FezVrasta/popper.js#488]
Why when using a `popper.js` version (`1.12.6`) downloaded with `yarn` in a simple HTML page  as follows:
```
<!doctype html>
<html lang="en">
  <head>
    <title>Hello, world!</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css">
  </head>
  <body>
    <h1>Hello, world!</h1>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="node_modules/jquery/dist/jquery.slim.min.js"></script>
    <script src="node_modules/popper.js/dist/popper.min.js"></script>
   <script src="node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
  </body>
</html>
```

 this generates this error pointing to the `line 4`:
```
Uncaught SyntaxError: Unexpected token export, popper.min.js:4
````
If I use a CDN way to get popper.js:
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
```
it works as needed.

**Comment by FezVrasta** [comment]
I think you are having this problem because the way the Yarn package is decoded, and thus, later, encrypted, during the transition between the two network points could have been corrupted by a nondeterministic AST parser that then served to your client data structure obviously incompatible with the target environment.

Or in other words, read the README 😊

**Comment by Javix** [comment]
So what's the point ? I tried to install it both with `nom` and `yarn`on OSX without any restrictions (no proxy, no special firewall settings) and it still fails (no matter in which browser) with the same error.

**Comment by FezVrasta** [comment]
I'm very sorry man, but please, read the README and the link I left you, I can't do more than this.
