### ISSUE TITLE
`x-arrow` attribute usage/purpose is not documented

### ISSUE THREAD

**Issue by oskarkrawczyk** [FezVrasta/popper.js#49]
I went through the code and the arrow auto-insert it's intentionally omitted in anything else than parse mode.

Curious what the reasoning behind this? Are you guys open to PR so that arrow is also added when using an element reference as the popper?

**Comment by FezVrasta** [comment]
This is a positioning library, it's scope is to position a given element relatively to another given element.

The parse mode is just a simple way to test the functionalities of the library without having to add elements manually tbh.

I don't want to mess with the DOM, it's easy to manually add the arrow's `div` if needed.

Hope it makes sense.

**Comment by oskarkrawczyk** [comment]
Makes sense. It's easy but it won't reposition itself as the one added via `parse()`.

**Comment by FezVrasta** [comment]
Actually it will. The arrow element has just the `x-arrow` attribute, its position is managed by its wrapper (the popper), check out the CSS of the demo page if you have some doubts about it please.

**Comment by oskarkrawczyk** [comment]
Updated my previous comment. That said, I did try to add the arrow manually before without success because I did remove the the `x-arrow` attribute – I assumed this and inline styles were added automatically by the library. It would probably make sense to mention that the `x-arrow` attribute is required.

Thanks

**Comment by FezVrasta** [comment]
Right, I just noticed that it's not documented at all.
