### ISSUE TITLE
Double "dist" dir

### ISSUE THREAD

**Issue by Trainmaster** [FezVrasta/popper.js#491]
### Steps to reproduce the problem

1. Install `popper.js@1.12.8` with `bower`

### What is the expected behavior?

The file `popper.js` should be located in `dist/popper.js`.

### What went wrong?

The file `popper.js` is located in `dist/dist/popper.js`.

**Comment by FezVrasta** [comment]
What are you using to install the library? With npm everything seems right:
https://unpkg.com/popper.js@1.12.8/

**Comment by thlbaut** [comment]
I have the same problem with bower.

**Comment by FezVrasta** [comment]
Thanks for the heads up, I'll see what I can do ASAP

**Comment by Trainmaster** [comment]
@FezVrasta I installed it using `bower`.

**Comment by getsomecoke** [comment]
@FezVrasta  does this has to do something with [copy command](https://github.com/FezVrasta/popper.js/blob/master/packages/popper/bower-publish.sh#L8) in `bower-publish.sh`

`cp -R dist ../../dist`

This will copy the dist folder inside the other dist folder.

**Comment by FezVrasta** [comment]
Yes that's prob it

**Comment by FezVrasta** [comment]
Please try 1.12.9, it should be okay

**Comment by thlbaut** [comment]
Thank you :)
