### ISSUE TITLE
Is there a way to disable/revert "flip" when no space exists on the flip side?

### ISSUE THREAD

**Issue by greg-a-smith** [FezVrasta/popper.js#498]
### CodePen demo

https://codepen.io/anon/pen/pdLwPg

### Steps to reproduce the problem

1.  Open CodePen
2.  Begin scrolling in the container (gold region) until the reference element (red) scrolls into view

### What is the expected behavior?

The `preventOverflow` and `flip` modifiers are acting as expected, however, I'm wondering if there is a way to disable or revert the flip when there is also not enough space for the popper on the flip side.  In this CodePen example, the popper placement is `bottom-start`, but initially appears flipped to `top-start` because there is initially not enough space on the bottom (as expected).  Once scrolled up far enough, it does flip back to `bottom-start`.  However, there is a time as you scroll up when the popper (positioned on top) gets cut off as there is also not enough space above the reference.  In a case like this where there isn't enough space on either side, I would actually prefer to leave it on the bottom as it seems more natural to have content out of view off the bottom rather than flipping to the top and then not showing part of the popper.

### What went wrong?

When flipping the popper, it doesn't seem to also do a check to see if there is space available.  In an example like this, the popper is basically a dropdown for an input so moving the popper left or right isn't a good experience nor is disabling `escapeWithReference`.

**Comment by FezVrasta** [comment]
You may define the `flip: { behavior: ['top-start', 'bottom-start', 'top-start'] } }` so that if there's not space on the second placement it falls back to the first one.

Does it help?

**Comment by greg-a-smith** [comment]
@FezVrasta Thanks for the response.  That did not help.  It _kinda_ worked in that it prevented the flip to the top, but then it never flipped to the top even when there was space for it.

**Comment by DawnWright** [comment]
This is our biggest need with popper at the moment. 👍

**Comment by thielium** [comment]
Relevant issue: https://github.com/FezVrasta/popper.js/issues/550#issuecomment-374589903

The workaround in the comment actually did the trick in my case (similar, but not exactly the same).

**Comment by FezVrasta** [comment]
Oh right, going to close this and track the issue in #550
