### ISSUE TITLE
Wrong placement doc?

### ISSUE THREAD

**Issue by andresgutgon** [FezVrasta/popper.js#50]
Hi, just a question. In documentation you talk about `placement` option being `bottom-left`. But for me is working `bottom-start`.

### Steps to reproduce the problem
Go to documentation: https://popper.js.org/documentation.html#new_Popper

### What is the expected behavior?
Acurate `placement` documentation

Describe what you would have expected.
I would expect `bottom-start`, `bottom-end`,... in the doc.

### What went wrong?
I see 
![image](https://cloud.githubusercontent.com/assets/49499/15682516/5672d7ec-275e-11e6-97d0-00fbff326142.png)

### Any other comments?
Is that ok?

**Comment by FezVrasta** [comment]
Yes you are right, I thought I had already fixed it tho... Checking in few minutes

**Comment by andresgutgon** [comment]
💪

**Comment by FezVrasta** [comment]
Umh no... Must update them. Will do when I find a minute.

https://github.com/FezVrasta/popper.js/blob/master/src/popper.js#L97-L98
