### ISSUE TITLE
Specify which event to listen to with .enableEventListeners() / .disableEventListeners()

### ISSUE THREAD

**Issue by atomiks** [FezVrasta/popper.js#500]
Sometimes you want to only keep the resize listener but disable the scroll listener. Perhaps you could pass a string in to specify which one to enable or disable (default behavior is both):

```javascript
popperInstance.enableEventListeners('resize') // only listen to resize
popperInstance.disableEventListeners('resize') // don't listen to resize anymore
```

**Comment by FezVrasta** [comment]
What's the use case?

**Comment by atomiks** [comment]
You want to allow a popper to flip on initial update (i.e. on initial show) but with a disabled scroll listener so that it doesn't flip around while scrolling (can be jarring esp. with hover event), but still allow it to be correctly placed when the window is resized.

**Comment by FezVrasta** [comment]
I'd say the best way would be to disable the flip modifier after the first update, or am I missing something?

**Comment by atomiks** [comment]
That would be enough, but setting the `enabled` property of the flip modifier to false doesn't disable it, how do you do it?

**Comment by atomiks** [comment]
...Actually it seems disabling the flip modifier will make it flip back to its original position. The behavior I want is to keep it at its flipped position, just prevent it from updating the placement.

**Comment by FezVrasta** [comment]
Can't you read the flipped placement and set it as default placement?

**Comment by atomiks** [comment]
That makes things a little too complicated, it would be easier just to disable the scroll listener

**Comment by atomiks** [comment]
Reopening because I'd like this feature in Tippy... based on the last comment, is this something you would do?

**Comment by FezVrasta** [comment]
I don't think I'm going to add this sorry, the core is already complex enough.

**Comment by hypeJunction** [comment]
I must agree that flipping when scrolling makes for a very annoying user experience. After the popup is rendered is should stick to the same position, at least for vertical scroll.
