### ISSUE TITLE
Popper is not defined for bootstrap.bundle.js

### ISSUE THREAD

**Issue by myorangeca** [FezVrasta/popper.js#501]
I was trying the popper.js that comes with bootstrap.bundle.js (v2). The code to turn off gpu acceleration no longer works. `Popper.Defaults.modifiers.computeStyle.gpuAcceleration = false; `

When I link popper.js separately it works, but when in bootstrap.bundle.js - it throws an error: Uncaught Reference Error: Popper is not defined

**Comment by Johann-S** [comment]
Yep that's because Popper.js is bundled in Bootstrap, if you want to twick Popper.js config you should include it separately

**Comment by myorangeca** [comment]
@Johann-S I tried to include it separately and used gulp concat. It threw a bunch of errors and did not concatenate the files. :\

**Comment by Johann-S** [comment]
which version of Popper.js did you chose ? UMD ?

**Comment by myorangeca** [comment]
v 1.12.5, I believe that's the latest.

**Comment by Johann-S** [comment]
So I express myself very bad 😟 BTW the latest release is `1.13.0` but you have to choose the UMD version of your release of Popper.js for example : 
- https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.js
- https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.min.js
