### ISSUE TITLE
Possible enhancement: bind the scroll listener with `useCapture` instead of binding a different listener to every scrolling parent

### ISSUE THREAD

**Issue by clark-pan** [FezVrasta/popper.js#502]
Unsure if this has been tried already, but instead of [attaching a `scroll` listener to all scrollParents](https://github.com/FezVrasta/popper.js/blob/master/packages/popper/src/utils/setupEventListeners.js), would it not be simpler to just attach a `useCapture` scroll event on window?

The only down side I can see to this is the lack of ShadowDOM support, but then again I don't think if the element is part of the light DOM, and the scrolling container is part of the shadow DOM, the existing solution would work either.

I've created a [codepen](https://codepen.io/anon/pen/YEjgRx?editors=1111) to show what I'm talking about (best tested by changing view with the editors on the left, view on the right, and console panel open). Note that scrolling the `#scroll1` container, that a scroll event is still triggered.

This should make it easier to support elements that are jumping around the DOM (admittedly this is probably not a very strong usecase). There shouldn't be a performance concern, especially if you wrap the firing of the actual scheduler with an `e.target.contains(target)` check first.

I'm happy to raise a PR if you consider this a worthy change.

**Comment by FezVrasta** [comment]
I admit I'm having an hard time to understand how the `useCapture` is supposed to work, but if you can create a PR that makes all the tests pass and reduces the amount of code I'll be happy to merge it.
