### ISSUE TITLE
real working examples with fadein / fadeout needed

### ISSUE THREAD

**Issue by DanielRuf** [FezVrasta/popper.js#505]
So far I could not find any real examples or documentation about working fadein / fadeout and animate implementations.

It would be great to have some as it is quite hard to get this working.

**Comment by FezVrasta** [comment]
Check out the Tooltip.js page, that's a complete library built with Popper.js you can use to understand how to use Popper.js in your own code.

Popper.js is not a tooltip library, it only provides positioning logic

**Comment by DanielRuf** [comment]
Right. But applying any jQuery.animate / trasition / animation conflicts with the code and produces weird behaviors of the tooltip. Also the delay prevents the usage of jQuery.fadeIn/fadeOut and jQuery.stop did not solve the issues on my side even when I removed all other scripts.

Can you maybe lead me to some examples that work?
So far I have not found any animation example in the issues and the ones which are about this solved this in a quite complex way or did not provide the final solution.

**Comment by FezVrasta** [comment]
Take a look at Tippy.js, it makes use of Popper.js and adds a lot of animations.

**Comment by DanielRuf** [comment]
That is exactly what I've needed. Thanks. Is this linked in the docs?

**Comment by FezVrasta** [comment]
It's listed here https://github.com/FezVrasta/popper.js/blob/master/MENTIONS.md

**Comment by DanielRuf** [comment]
Okay thanks. I thought I would find this information on the website in the docs. Was not quite clear to me that it is there.

Thanks for your time.
