### ISSUE TITLE
CDN  Unexpected token export - yes again - for tooltip.js

### ISSUE THREAD

**Issue by phoebebright** [FezVrasta/popper.js#506]
So I have read the README up and down and back and forth and after searching through all the issues, I did find the solution to using the popper.js from the CDN but before that I tried:

"https://cdnjs.com/libraries/popper.js" - well that's what it says in the README
"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/esm/popper.min.js" - it's the first one in the list 
"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/popper.min.js" - it's the shortest link so maybe that's it
"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.min.js" - yay, the token error goes away but now it says

 Tooltip is not defined

So back to the README and the issues, the documentation, google.  The README under the heading "Tooltip.js as well:" lists, "https://cdnjs.com/libraries/popper.js", maybe this is an error? the items above say tooltip.js, so tried going to https://cdnjs.com/libraries/tooltip.js - and get a long list that includes popper.js but nothing saying tooltip.js

I'm sure there is a simple explanation, but for the moment I can't work out how to use tooltip.js from a CDN.

**Comment by FezVrasta** [comment]
You have to use the UMD version if you environment does support UMD, or ESM if your environment supports ESM. There's not much to add actually.

Obviously if you import Popper.js, Tooltip.js will not be defined, because you have to import both Popper.js and Tooltip.js

**Comment by phoebebright** [comment]
Under the heading CDN,  Tooltip.js as well,  it has the row:

cdnjs | https://cdnjs.com/libraries/popper.js

Is that correct when all the other links point to a tooltip.js ?
