### ISSUE TITLE
Incompatible with adblocker addons

### ISSUE THREAD

**Issue by UrsaForce** [FezVrasta/popper.js#509]
I don´t know if this is the correct way to point this, but when I have Adblock Plus addon activated on Chrome it bugs the library, disabling it works fine. I think this issue is directly related to Adblock technology but its worth mentioning if someone thinks this library is broken at first. Adguard adblocking engine doesn´t seem to crash it though.

**Comment by FezVrasta** [comment]
Please follow the issue template. You haven't provided enough information

**Comment by UrsaForce** [comment]
I'm sorry could you point me where is it so I can properly edit my post?

**Comment by FezVrasta** [comment]
It was the issue template you deleted when you created this issue.
