### ISSUE TITLE
Is there a way to apply `flip` before `preventOverflow`?

### ISSUE THREAD

**Issue by Justineo** [FezVrasta/popper.js#512]
### CodePen demo

https://codepen.io/Justineo/pen/QaypBM

### Steps to reproduce the problem

1. with `placement` set to `bottom-start`
2. when the reference is on the right side of the container
3. the popper is shifted (`#pop`)

### What is the expected behavior?

Provide a way to apply `flip` when the popper is placed outside the container rather than shift it. (Like `#pop2` in the CodePen demo.)

![image](https://user-images.githubusercontent.com/1726061/34097993-edb8a594-e415-11e7-8278-42b1e7407ea4.png)

### What went wrong?

Sometimes we want to flip the popper when it's outside the container, not when it overlaps with the reference element.

### Any other comments?

I've looked into how popper handles this now, but not sure how to handle this.

**Comment by arechsteiner** [comment]
I'm facing this same problem when trying to implement a navigation menu. 

I've tried setting the flip behavior but it doesn't work as expected when the popper element overflows on the right side:

```
{
  placement: 'bottom-start',
  modifiers: {
    flip: {
      behavior: ['bottom-start', 'bottom-end']
    }
  }
}
```

In this shot the "Dropdown" in the top bar is the reference, and the expanded drop down menu is the popper element.

![image](https://user-images.githubusercontent.com/1199486/34412137-ad0d2038-ebdb-11e7-89e7-131a58dbaa02.png)

**Comment by leevigraham** [comment]
Similar issue (another example):

```
{
    placement: 'bottom-start',
    modifiers: {
        flip: {
            behavior: ['bottom-start', 'bottom-end']
         }
     }
 }
```

![image](https://user-images.githubusercontent.com/25124/38767516-6f88042c-4026-11e8-84f3-43c95bbb3deb.png)

**Comment by leevigraham** [comment]
@arechsteiner setting the boundariesElement to viewport will make sure the whole popper is shown

```
{
  placement: 'bottom-start',
  modifiers: {
    preventOverflow: {
      boundariesElement: 'viewport'
    }
  }
}
```

**Comment by Justineo** [comment]
> setting the boundariesElement to viewport will make sure the whole popper is shown

It's not the desired behavior. This will shift the popper element to the left but we want its right border to align with the right border of the reference element (flip instead of shift).

**Comment by leevigraham** [comment]
@Justineo Yep I understand it's not the desirable behaviour but @arechsteiner it will atleast show all the content.

**Comment by Lehakos** [comment]
@FezVrasta any news about this feature?
