### ISSUE TITLE
Problem on IE11 and SVG

### ISSUE THREAD

**Issue by JulienJo** [FezVrasta/popper.js#515]
Hi and happy new year!

### Issue
I have an issue with SVG circle, IE11 and tippy.js (which use popper.js): The tooltips don't work. 
I have an alert message in the console: `The object does not handle the property or method "contains": 649,3` which seems to be related with popper.js (the other warning message is related to tippy.js)

Do you think you could help me?

### CodePen demo
[https://codepen.io/Julien-Jolly/pen/pprydG ](https://codepen.io/Julien-Jolly/pen/pprydG)

### What is the expected behavior?
You should see and interact with the tooltip

### What went wrong?
No tooltip at all :'-(

### Browser
IE11 on Windows 10 (work on Edge and Chrome, FF...)

**Comment by FezVrasta** [comment]
It looks like IE11 doesn't support the method "contains" on SVG nodes... I'm not surprised.

You may polyfill it:

```
SVGElement.prototype.contains = function(el){
        while (el = el.parentNode) {
            if (el === this) return true;
        }
        return false;
    }
```

Please let me know if it works.

**Comment by FezVrasta** [comment]
May you let me know if the polyfill worked for you @JulienJo ?

**Comment by lionel87** [comment]
I have the same problem and the polyfill works, but it runs very slow.

**Comment by FezVrasta** [comment]
@lionel87 great to hear it works, unfortunately I don't think we can do much to make it run faster...

**Comment by andrerfneves** [comment]
Can attest that the polyfill works for `contains`. I ran into other similar issues with IE11 and `focus` but only regarding `SVGElement`'s. Thanks @FezVrasta.

**Comment by FezVrasta** [comment]
I'm going to close this because I don't think the SVG usage is so common to justify to ship polyfills with the library, marking the issue as FAQ to make it easily discoverable.

**Comment by mangowi** [comment]
> It looks like IE11 doesn't support the method "contains" on SVG nodes... I'm not surprised.
> 
> You may polyfill it:
> 
> ```js
> SVGElement.prototype.contains = function contains(node) {
> 	if (!(0 in arguments)) {
> 		throw new TypeError('1 argument is required');
> 	}
>  
> 	do {
> 		if (this === node) {
> 			return true;
> 		}
> 	} while (node = node && node.parentNode);
>  
> 	return false;
> };
> ```
> 
> Please let me know if it works.

The polyfill works 👍

**Comment by taltrui** [comment]
@FezVrasta Sorry for bringing up such an old issue, but I've found that `contains` is present in `HTMLDivElement`, so I think it is safer and maybe faster to use a that one instead:
```javascript
if (!SVGElement.prototype.contains)  SVGElement.prototype.contains = HTMLDivElement.prototype.contains;

```
