### ISSUE TITLE
Keep together and bottom-start does not keep the popper stick.

### ISSUE THREAD

**Issue by johndavedecano** [FezVrasta/popper.js#524]
My popper does not stick to its reference if i use bottom-start. It only stick to its parent if i use right but it looks so off.

You  can see whats happening here.

https://321.show/hFczk0mRuM5

Here is my current settings

```
    this.popper = new Popper(this.reference, this.element, {
      placement: 'bottom-start',
      removeOnDestroy: true,
      modifiers: {
        offset: { offset: '0,5' },
        keepTogether: { enabled: true },
        preventOverflow: {
          enabled: true,
          padding: 10,
          escapeWithReference: false,
          boundariesElement: this.props.scrollParent,
        },
      },
    });
```

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
