### ISSUE TITLE
Positioning regression

### ISSUE THREAD

**Issue by alecpl** [FezVrasta/popper.js#532]
I built multi-level menu using Bootstrap 4 popovers. It worked like a harm with Popper 1.12.6, but since 1.12.7 menu positioning is broken. Tested with all versions including 1.13.0-next.

Looks like the second-level popover is placed incorrectly. This is quite complicated code and I can't provide a simplified test case. Any hints on what changed in 1.12.7 that can cause this issue?

The popover is initialized using:
```
   .popover({
                content: content_element,
                trigger: 'manual',
                placement: 'right',
                animation: true,
                html: true
            })
```
Again, the element on which I create the new popover is already a child of opened popover.

**Comment by alecpl** [comment]
I've found out that removing this in my stylesheet fixes the issue:
```
.popover-body { overflow-x: hidden; }
```
https://codepen.io/anon/pen/mpYmVX

**Comment by alecpl** [comment]
So, it looks that if the button is inside of an element with `overflow-x:hidden` popover positioning is broken. I need scrolling in long menus, so I can't just remove it. Any remedy?

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
