### ISSUE TITLE
Micromatch Mismatch?

### ISSUE THREAD

**Issue by ndmax** [FezVrasta/popper.js#533]
### Steps to reproduce the problem

1.  Install Yarn & Clone Popper
2.  `cd popper-dir && yarn --ignore-optional`

### What is the expected behavior?

1/4 - Resolve packages
2/4 - Fetch packages
3/4 - Link dependencies
4/4 - Build fresh packages

### What went wrong?

Step 2/4 issues a warning about micromatch package:

`warning Pattern ["micromatch@jonschlinkert/micromatch#2.2.0"] is trying to unpack in the same destination "/home/user/.cache/yarn/v1/npm-micromatch-3.1.4-bb812e741a41f982c854e42b421a7eac458796f4" as pattern ["micromatch@^3.0.4"]. This could result in a non deterministic behavior, skipping.`

### Any other comments?

Is the source of this warning from this snippet in popper.js/**yarn.lock**:

`micromatch@^3.0.4, micromatch@jonschlinkert/micromatch#2.2.0:`
`version "3.1.4"`
`resolved "https://registry.yarnpkg.com/micromatch/-/micromatch-3.1.4.tgz#bb81..."`

**Comment by FezVrasta** [comment]
`node --version` and `yarn --version`?

**Comment by ndmax** [comment]
`node --version` v8.9.4
`yarn --version` 1.3.2

I removed `micromatch@jonschlinkert/micromatch#2.2.0` from the code referenced above and the warning is no longer issued.

Also, you are literally the fastest-responding developer on GitHub.

**Comment by FezVrasta** [comment]
I encountered problems with this micromatch thing in the past but I thought I did solve them... I'll look into it once I have some time to spend on it.
