### ISSUE TITLE
Incorrect offset container used when first child of common parent is a hidden input

### ISSUE THREAD

**Issue by RKushnir** [FezVrasta/popper.js#537]
### CodePen demo

https://codepen.io/anon/pen/BYyjNM

### Steps to reproduce the problem

1.  Include a hidden input as the first child of the offset container of the elements.

### What is the expected behavior?

The "reference" and "popper" elements are aligned.

### What went wrong?

A hidden input's `offsetParent` is null, causing incorrect offset container to be chosen for the offsets calculations.

### Any other comments?

[This is the place](https://github.com/FezVrasta/popper.js/blob/150ef056629b171b96e5f2bcf6316d25ff0a146f/packages/popper/src/utils/isOffsetContainer.js#L9) where element's first child is arbitrarily chosen for a test if the element is an offset container. I think, it needs to use a child which is actually rendered.

**Comment by FezVrasta** [comment]
On snap, that's a weird one... I'll check it out tomorrow morning.

**Comment by FezVrasta** [comment]
So the problem is that `hiddenHTMLElement.offsetParent` returns `null`.

I wonder if we could do something like this:

```
let offsetParent = element && element.offsetParent;
while (offsetParent === null && element.nextElementSibling) {
	offsetParent = (element = element.nextElementSibling).offsetParent;
}
```

So that we don't add overhead on the most common use cases (where there aren't hidden children) but we address the case if needed.

I don't have time to work on a PR but feel free to take my code and send a PR that edits `utils/getOffsetParent.js`

**Comment by RKushnir** [comment]
Thank you for the quick reply, I'll have a try at a PR.

Btw, in my case the hidden input is part of the layout generated by react-select, which I cannot control, otherwise I wouldn't bother and just reorder the elements. So this may also help others.
