### ISSUE TITLE
Question: can I change reference element at runtime?

### ISSUE THREAD

**Issue by MOZGIII** [FezVrasta/popper.js#538]
Hi. Can I change reference element at runtime?

My usecase is I have an SVG map, rendered with d3. I want to implement tooltips with information about user sees on the map, and show them when user hovers a particular `svg` `path`. I figured that I'd rather change reference element from mouse over / mouse out events rather than create a popper.js instance for every `path` (there are a lot).

**Comment by atomiks** [comment]
https://codepen.io/anon/pen/eVNaJv

Set `reference` to the new element, then call `Popper#update`?

**Comment by MOZGIII** [comment]
That looks good. I expected there to be some underlying state to clean up, but seems like it's either not required, or already covered by `update()`.
I'll try this solution.

Can I detach tooltip (to hide it) by assigning `null` to `reference`?

**Comment by MOZGIII** [comment]
Turns out I can, however I can't pass to the constructor. I solved it by using `document.documentElement`:
```js
new Popper(document.documentElement, this.tooltipEl)
```

**Comment by cihad** [comment]
Is it possible on version 2? I want to change popper instance's reference element.

**Comment by cihad** [comment]
Yes it is possible:

```js
popperInstance.state.elements.reference = newReferenceDom
```

> Is it possible on version 2? I want to change popper instance's reference element.

**Comment by atomiks** [comment]
@cihad please note that `scrollParents` detection is done on create/update, so if the reference is is inside a different scrolling container that won't work. I recommend destroying the previous instance and creating a new one instead.
