### ISSUE TITLE
Tooltip not displaying for all elements

### ISSUE THREAD

**Issue by vairamsvsjdo** [FezVrasta/popper.js#543]
### CodePen demo

https://codepen.io/pen?template=wGqJEz

### Steps to reproduce the problem

1.Code pen created using template above: https://codepen.io/vairamsvsjdo/pen/zRqaqv
 

### What is the expected behavior?

Display tooltip.js template tooltip 
### What went wrong?
Displays tooltip for the first item with that class name onl

**Comment by FezVrasta** [comment]
Please convert your code snippet into a CodePen using the provided template, that will help to triage the issue.

**Comment by vairamsvsjdo** [comment]
I updated my comments to reflect the codepen created using the template given.
The template does not have no reference to the popper.js and tooltip.js libraries. So, my version has those 2 plus jquery as that is required for my use case.
