### ISSUE TITLE
Include license file in the distribution or update README.md link to the license

### ISSUE THREAD

**Issue by peterblazejewicz** [FezVrasta/popper.js#546]
That's minor and reflects production mode installation only. When the package is added as dependency there is no LICENSE file included. The link to the license in the `README.md` is relative, so it points nowhere in local installation. 
I'd ask to either update the `README.md` (I could do this) link to point to static absolute url or just ship the license file alongside the distribution.
I'm aware that `package.json` comes with license type.

Thanks!

**Comment by casdevs** [comment]
We're also having the same problem. LICENSE file is missing if npm package is installed, thus it doesn't get included in our webpack's LICENSE file collection workflow...

**Comment by FezVrasta** [comment]
The license is at the top of the dist files

**Comment by casdevs** [comment]
ok thanks for pointing me at this, but would it also be possible to include the LICENSE.md file for our npm package friends? see https://docs.npmjs.com/files/package.json#files

**Comment by FezVrasta** [comment]
please feel free to send a PR to add this

**Comment by jquense** [comment]
hey @FezVrasta newer versions of `lerna` will do this automatically. Would you mind pushing a new/next version with the latest `lerna` we'd very much appreciate it 🙏

**Comment by FezVrasta** [comment]
Do you mean Lerna will prepend the license to each file?

**Comment by jquense** [comment]
It will copy your top level license into the sub packages when publishing so it ends up in the npm package yeah

**Comment by jquense** [comment]
There isn't anything to PR I don't think. You would need to do a publish with the latest lerna, something I can't do. It's not pressing either, so no rush, but I wanted to let you know that lerna now supports what folks are asking for here without any additional work on your part 👍

**Comment by FezVrasta** [comment]
I guess Lerna needs to be updated first, that will need a PR

**Comment by jquense** [comment]
https://github.com/FezVrasta/popper.js/pull/803
