### ISSUE TITLE
What is the benefit of tooltip.js instead of using popper.js directly?

### ISSUE THREAD

**Issue by Siilwyn** [FezVrasta/popper.js#548]
Seems like the added `aria` tags are an extra but besides that I don't see anywhere what tooltip.js provides over popper. What makes it even more confusing are the examples on the popper.js website which are tooltips, but made using popper.js directly. 🤔

**Comment by FezVrasta** [comment]
Popper.js is just the positioning engine, you have to integrate it in your own code.
Tooltip.js is a tooltip library, it creates the tooltips for you.

**Comment by FezVrasta** [comment]
As said, with Popper.js you have to write all the DOM manipulation logic by yourself (create the tooltip, append to the DOM, remove from the DOM on destroy and stuff like that).

Tooltip.js does that for you

**Comment by Siilwyn** [comment]
Ah I see, thank you for your replies!
