### ISSUE TITLE
popover not aligned with reference div when using "bottom left". 

### ISSUE THREAD

**Issue by davidlygagnon** [FezVrasta/popper.js#549]
### CodePen demo
https://codepen.io/dlygagnon/pen/XZpeMx

### Steps to reproduce the problem

1. Create two divs:
```
<div id="ref" aria-describedby="pop">
  ref
</div>
<div id="pop" role="tooltip">
  pop
</div>
```

2. Set CSS for each div as follow:
```
#ref {
  background: red;
  width: 100px;
  height: 100px;
  left:60px;
  position: absolute;
}

#pop {
  background: blue;
  width: 150px;
  height: 100px;
}
```
Note the width of #ref is smaller than width of #pop

3. JS code:
```
const refEl = document.getElementById('ref');
const popEl = document.getElementById('pop');

new Popper(refEl, popEl, {
  placement: "bottom left"
});
```

Issue is #pop is not aligned with #ref.

![screen shot 2018-02-08 at 11 15 33 am](https://user-images.githubusercontent.com/1821787/35993293-b51c844c-0cc1-11e8-9203-32573ac35636.png)

### What is the expected behavior?
I expect the popover element (#pop) to be aligned with #ref.

### What went wrong?

Function `getPopperOffsets()` calculates this value using:
`popperOffsets[mainSide] = referenceOffsets[mainSide] + referenceOffsets[measurement] / 2 - popperRect[measurement] / 2;`

When it's "bottom left", it should really just be
`popperOffsets[mainSide] = referenceOffsets[mainSide]`. Same with "top left". For "top right" or bottom right", it should just be: 
`referenceOffsets[mainSide] + referenceOffsets[measurement] / 2` .

I'm not sure in which case we need to substract `popperRect[measurement] / 2`.

**Comment by FezVrasta** [comment]
Umh, which browser are you using? I see this:

![image](https://user-images.githubusercontent.com/5382443/35995021-04111914-0cc7-11e8-9e59-f616fbbd300f.png)

**Comment by FezVrasta** [comment]
Oh, I see you fixed your codepen to use `bottom-start` instead of the unsupported `bottom left`. Good to close I guess

**Comment by davidlygagnon** [comment]
Yes - "bottom-start" is the one I should be using but the calculation seems wrong to me. Can you elaborate on why it's working in that case?

**Comment by FezVrasta** [comment]
Why you say `bottom` won't work? I see it works just fine:

![image](https://user-images.githubusercontent.com/5382443/35995510-6fde003e-0cc8-11e8-96e2-6c188dc7a04e.png)

**Comment by davidlygagnon** [comment]
Shouldn't it be aligned with #ref ?

**Comment by FezVrasta** [comment]
Why should it? `bottom` doesn't specify any alignment so it fallbacks to center, which is the most common use case

**Comment by davidlygagnon** [comment]
ok - thanks. I can work with `bottom-start`.
