### ISSUE TITLE
Pixel-perfect positioning: don't floor positions with gpuAcceleration disabled

### ISSUE THREAD

**Issue by atomiks** [FezVrasta/popper.js#551]
Currently, you floor the positioning because of blurriness with fractional translation, but this inevitably causes small positioning errors because elements on the page can be positioned using subpixels.

I'm thinking of not flooring when `gpuAcceleration` is disabled. When used with `gpuAcceleration` disabled, you achieve no blurriness (due to the lack of a new layer the popper is promoted to with `translate3d`?) and pixel-perfect positioning at a minor performance cost. 

### Any other comments?

See: #277

**Comment by FezVrasta** [comment]
Fixed
