### ISSUE TITLE
Z-index on safari

### ISSUE THREAD

**Issue by blaadje** [FezVrasta/popper.js#554]
### Preview

<img height="600" src="https://trello-attachments.s3.amazonaws.com/594a792ea4caf03739e980ab/5a5f838d28724cfc34654688/5f18ccf4defe30f452db1b89d4a5fe58/IMG_1049.PNG" />

### Steps to reproduce the problem

Just put some content under a popper on Safari 

### What is the expected behavior?

The popper should be on top of the content. Z-index doesn't change anything

### What went wrong?

The popper is behind the content

By doing `transform: translate3d(0,0,1px);` its fixing it

### Browser Version
Release 49 (Safari 11.2, WebKit 12606.1.3.3)

**Comment by FezVrasta** [comment]
Popper.js doesn't handle z-index, because it's simply impossible for a 3rd party code to know how your z-index is being handled. You have to handle it by yourself.

**Comment by blaadje** [comment]
Handling z-index popper by ourselves with chrome/safari/ie works well, its not taking effect on safari tho. The only way the popper can be on top is with the `transform: translate3d(0,0,1px);`. As the transform is generated automatically by popper.js i can't handle it.

**Comment by FezVrasta** [comment]
Sorry without a codepen I can't help further
