### ISSUE TITLE
EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by weilinzung** [FezVrasta/popper.js#555]
When using `gulp-imagemin` try to optimize all build assets then if not exclude this favicon, it will gave this error message. Thanks~

`EISDIR: illegal operation on a directory, read`

`.../popper.js/docs/favicon.ico`

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
