### ISSUE TITLE
Cannot find the popper.js file for bootstrap

### ISSUE THREAD

**Issue by danielvivivi** [FezVrasta/popper.js#558]
### CodePen demo

https://codepen.io/pen?template=wGqJEz

### Steps to reproduce the problem

1.  Download popper.js-master zip file and extract
2.  Look for popper.js file
3.  

### What is the expected behavior?

To see a file called popper.js

### What went wrong?
There was no popper.js file in the zip

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/popper.js#installation
