### ISSUE TITLE
Popper unexpectedly shifted on scroll event

### ISSUE THREAD

**Issue by mir3z** [FezVrasta/popper.js#562]
### CodePen demo

I can't create minimal reproducible example on codepen so far. I will update the ticket as soon as I manage to do that. 

### Steps to reproduce the problem

Hard to provide exact steps. It's just a plain popper with `placement="left"` and the following modifiers pointing to one of the elements on the webpage:

```
arrow: {
    element: arrowElement,
    enabled: true
},
flip: {
    enabled: false
},
preventOverflow: {
    enabled: false
},
hide: {
    enabled: false
},
keepTogether: {
    enabled: true
}
```

### What is the expected behavior?

Popper element should not shift to the right or left.

### What went wrong?

Initially the popper looks fine but when I scroll the page vertically (or call `update` method) it is shifted to the right by 15px (the width of the arrow element). It is observed only when placement if `left`. It works fine with any other placement. I'm looking for any kind of advice on how to fix that or reproduce with minimal markup. I presume it works like that because of some specific markup of styling but I can't find the culprit. I've tried several reference elements and popper is shifting regardless of that.

Update: It turned out it's because of arrows. I'm adding a margin-right to the popper elements if there is an arrow on the right side. Exactly as on popper homepage. The difference is that it works there and it and broken on my page since `update` is positioning popper again and ignores that margin.

**Comment by FezVrasta** [comment]
Sorry but without a repro I can't really help. Please open reply here once you get a working repro and I will re-open the issue. Thanks for your understanding.
