### ISSUE TITLE
Publish new version of popper.js to NPM

### ISSUE THREAD

**Issue by robcrocombe** [FezVrasta/popper.js#565]
Hi, we need to use some of the new changes you've made to Popper.js, like `updateTitleContent` (#561) and fix TypeScript typings (#539). It appears the last NPM release was in November 2017. Please can we have a new version soon? Thanks!

### Steps to reproduce the problem

1. `npm install popper.js`

### What is the expected behavior?

Get the new features and fixes.

### What went wrong?

Not getting the new features and fixes.

**Comment by kellym** [comment]
This also goes for `tooltip.js`, unless we should be using the popper.js repo for tooltips. Thanks!

**Comment by gilbarbara** [comment]
Or update the `@next` tag with the recent changes! 😬

**Comment by FezVrasta** [comment]
Going to do this during the weekend, sorry guys

**Comment by FezVrasta** [comment]
popper.js@1.14.0 and tooltip.js@1.2.0 released, I hope I didn't break anything :-(

**Comment by FezVrasta** [comment]
popper.js@1.14.0 and tooltip.js@1.2.0 released, I hope I didn't break anything :-(

**Comment by Johann-S** [comment]
@FezVrasta do you have a change log ?

**Comment by FezVrasta** [comment]
I'm writing it

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/popper.js/releases/tag/v1.14.0

**Comment by wolfrubin** [comment]
@FezVrasta the typescript type definitions file has changed between 1.13 and 1.14 and this has broken a module that depends on it, namely ng2-semantic-ui. I would investigate/change it myself but I'm not sure how. Any pointers?

**Comment by FezVrasta** [comment]
I'm not the one who maintains the TS definitions... @cwmoo740 may know more?

**Comment by cwmoo740** [comment]
@wolfrubin the types are no longer exported as a namespace...

changing `import Popper from 'popper.js'`

to

`import Popper, {Modifiers, PopperOptions, Placement, Data} from 'popper.js'`;

or

`import * as Popper from 'popper.js'`;

will fix the issues.
