### ISSUE TITLE
Consider allowing popups to be placed in a different parent element

### ISSUE THREAD

**Issue by priyajeet** [FezVrasta/popper.js#567]
There are times when rendering a popup inline causes issues due to z-indexing/overflowing and/or layout of the parent element and its siblings. Under these scenarios providing a parent element where the popup should render will help.

For example, using popper.js (with react-popper) in https://github.com/bvaughn/react-virtualized doesn't work well and causes such issue:

![image](https://user-images.githubusercontent.com/1075325/36865776-5a5743f0-1d45-11e8-91cf-6ce692e914b5.png)

A similar discussion can be seen here https://github.com/bvaughn/react-virtualized/issues/876

Tether.js helps with this since it lets you render the popup in a different location, but it has its own issues like https://github.com/HubSpot/tether/issues/279 and is not a maintained project anymore :-/

**Comment by FezVrasta** [comment]
Sure you can do that easily, with `react-popper` you can use the `React.Portal` API, with plain JavaScript you can simply attach your popper wherever you prefer. Popper.js will work just fine.
