### ISSUE TITLE
"O" Supported Property Name is not considered in the "for" loop

### ISSUE THREAD

**Issue by raffo1234** [FezVrasta/popper.js#568]
I was checking your code to learn more about Popper.js implementation, and I found this line
 `for (let i = 0; i < prefixes.length - 1; i++) {` 
here https://github.com/FezVrasta/popper.js/blob/master/packages/popper/src/utils/getSupportedPropertyName.js#L12

I am a bit confused because I think this should be `for (let i = 0; i < prefixes.length; i++) {` or Is there anything that I am missing?

Thanks in advance.

**Comment by atomiks** [comment]
I also found this while implementing the same functionality last year. Luckily, "o" browsers have such low usage share that autoprefixer even with > 0.1% setting doesn't add it. Therefore I don't think it's necessary to worry about. 

But still, the code should probably be updated if any prefixes get removed from the array in the future.

**Comment by FezVrasta** [comment]
Right! Feel free to send a PR please.
