### ISSUE TITLE
Using popperjs with D3js - offset/placement not correct with svg/rects

### ISSUE THREAD

**Issue by jaredvacanti** [FezVrasta/popper.js#569]
### CodePen demo

https://codepen.io/anon/pen/Jpzbaj

### Steps to reproduce the problem

1.  Initialize popper.js instance on `popperElement`
2.  Initialize `svg` elements (`rects`, `circles`, etc)
3.  on `mouseon`, update popper position of existing (and only) popper instance

### What is the expected behavior?

I want to use popper to position an existing tooltip, instead of creating thousands of tooltips, and update the data on `mouseon`. I'd like an arrow to point to the `rect` that has focus.

### What went wrong?

The `svg` aspect seems to be messing something up, as the height of the tooltip covers some of the svg, so smaller `rects` can't display a tooltip because the tooltip covers the entire `rect` - hence no `mouseon` event.

I've printed the `data` passed to the instance on update, and I can see that the rect bounding box is correct, but it's not placing correctly.

### Any other comments?

I wasn't able to find any other instance of d3.js being used with popper. Maybe there's a conflict with the libraries?

It appears that the **center** of the div is at the top. Is it necessary to use offset manually to push it to a desired spot or is that supposed to be default functionality? I would like to have an arrow tooltip on the `svg:rect`.

Edit: Is this because I'm using popper.js and I should be using tooltip.js to create the arrow, the dom element etc? If that's the case, is there a way to only create 1 tooltip and display it programatically with new data and new positions instead of creating what could be thousands of individual tooltips? Is there an understood limit to how many DOM elements are being created? Or, is it perfectly OK to use that many tooltips?

**Comment by FezVrasta** [comment]
I can't see any tooltip at all in your demo, should I do something specific?

**Comment by denisname** [comment]
@jaredvacanti
Don't add a `div` in a `svg`. It is a [`HTMLElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement) and is not allowed in a `svg`.
Replace line 12–15:
```javascript
var div = g.append("div")
   .attr("class", "tooltip")
   .html("initial template")
   .style("opacity", 1);
```
by
```javascript
var div = d3.select("body")
  .append("div")
  .attr("class", "tooltip");
```
and also set your css correctly:
```css
.tooltip {
  background-color: #d3d3d370; 
  color: black;
  pointer-events: none;
}
```
Now it must work.

Realise also how:
```
document.getElementsByClassName("tooltip")[0].namespaceURI
```
gives different results in both cases: `http://www.w3.org/2000/svg` and `http://www.w3.org/1999/xhtml`.

Should you really want to add a `div` in a `svg`, you must use a [`foreignObject`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject). See for example: [HTML inside a SVG using foreignObject](https://bl.ocks.org/Jverma/2385cb7794d18c51e3ab). And as [_d3.append_ inherite namespace from the parent element](https://github.com/d3/d3-selection#selection_append), you will have to specify the namespace:
```javascript
var div = g.append("foreignObject")
   .append("xhtml:div")
   .attr("class", "tooltip");
```
I definitely recommend you the first method...
