### ISSUE TITLE
Enhancement: Add placement type of overlay

### ISSUE THREAD

**Issue by erslater** [FezVrasta/popper.js#574]
It would be nice to specify the placement to be an overlay of the target dom element placed in the top left corner.

I am using it as a popover to edit a piece of information and would like it place right over the element I requested.

See the small edit dialog section of: [https://material.io/guidelines/components/data-tables.html#data-tables-interaction] for an example of what I mean.

**Comment by FezVrasta** [comment]
Have you tried the `inner` modifier?
