### ISSUE TITLE
updateTitleContent doesn't exists on tooltip instance

### ISSUE THREAD

**Issue by shaharkazaz** [FezVrasta/popper.js#577]
### CodePen demo

https://codepen.io/shaharkazaz/pen/JpgqYW?editors=1111
Open the console to see the instance object and error thrown.

### Steps to reproduce the problem

1.  Install tooltip.js (I'm using v1.1.7 but also tested on v1.1.6)
2. Try to call `updateTitleContent` function from the tooltip instance

### What is the expected behavior?

The tooltip title updates to the newly passed value, as [described in the documentation](https://popper.js.org/tooltip-documentation.html#Tooltip+updateTitleContent).

### What went wrong?

It doesn't exist in the tooltip instance, not even on the prototype.
Also, I checked the tooltip.js file that was installed and the function doesn't exist there.

**Comment by FezVrasta** [comment]
I haven't yet released the new version I'm sorry :-( 

#565
