### ISSUE TITLE
1.14.0 breaks Angular5 CLI build

### ISSUE THREAD

**Issue by jasoninrapid** [FezVrasta/popper.js#581]
### CodePen demo

https://codepen.io/pen?template=wGqJEz

### Steps to reproduce the problem

1.  Have an Angular 5 project that builds with the CLI, and is using popper.js
2.  ng b
3.  See error "error TS2503: Cannot find namespace 'Popper'"

### Any other comments?

This started happening with the release of 1.14.0 this morning.  We just tried 1.13.0 and it works fine.

**Comment by FezVrasta** [comment]
Read here https://github.com/FezVrasta/popper.js/issues/565#issuecomment-372415877

**Comment by jasoninrapid** [comment]
Thanks!  I didn't see that.
