### ISSUE TITLE
Incorrect `bottom` parameter when popper element has no parent (but <html>)

### ISSUE THREAD

**Issue by marcohamersma** [FezVrasta/popper.js#585]
Hey Hey,
I stumbled upon this issue the other day, where `computeStyle` doesn't pick the right `bottom` position for my popper. I've illustrated the bug in [this CodePen demo](https://codepen.io/marcohamersma/pen/XZwLwr).

<img width="273" alt="screen shot 2018-03-13 at 18 06 35" src="https://user-images.githubusercontent.com/577144/37360883-64752412-26e9-11e8-81d8-fa2cdb69e69d.png">

### CodePen demo
https://codepen.io/marcohamersma/pen/XZwLwr

### Steps to reproduce the problem

1. Make the body stretch beyond the viewport (like make it 2000px high)
2. Create a reference inside an element with position `fixed`
3. Create a popper outside of this element
4. Open a popper with `placement:'top'` and `computeStyle.x` to 'top'

### What is the expected behavior?
The popper appears in the expected place (above the reference element)

### What went wrong?
The popper is not visible because it's off screen

### Any other comments?
I know that it's maybe not super conventional to have the popper inside a different container than the reference element, but parts of my application require that I attach the overlay to the body. If there is no easy solution for this, perhaps a way to manually define what the `offsetParent` would be?

**Comment by FezVrasta** [comment]
Thanks for the report, why do you need `x` set to `top` when you are setting the `placement` to `top`? Usually you want `x` to be the opposite of `placement`.

**Comment by marcohamersma** [comment]
The `x` needs to be `top` because the popper element that I'm using might change height, and I want it to be able be anchored from the bottom. That was mentioned in 571 as well ^_^.

Anyway, thanks a lot for looking in to it (and for the quick response, I'm not sure how you do it)

**Comment by FezVrasta** [comment]
If the popper content may change, and you want it to stay in the right position when that happens, you want `x` to be set to `bottom`, because doing so its style will be `bottom: *px`, which means that if the height changes, it will grow towards the top while its bottom will stay anchored in place.

**Comment by FezVrasta** [comment]
Umh right, actually I think it should be the opposite, I'm not sure why it's working that way...

**Comment by bimbiltu** [comment]
Im going to try fixing this in the next couple of days

**Comment by FezVrasta** [comment]
Thanks @bimbiltu! 🤩
