### ISSUE TITLE
Freeze popover

### ISSUE THREAD

**Issue by passa1248** [FezVrasta/popper.js#588]
Hi all!
I need to show up a popover inside datatable that refresh data every 3 seconds.
The problem is that after refreshing, the popover reference is destroyed and popover showed go up  to coordinate 0,0 when scroll page.
Can it be solved?
Thanks in advance! (sorry for my bad english :( )

### CodePen demo

https://www.codeply.com/go/y2VQrjqdjf

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
