### ISSUE TITLE
Freeze popover

### ISSUE THREAD

**Issue by passa1248** [FezVrasta/popper.js#589]
Hi all!
I need to show up a popover inside datatable that refresh data every 3 seconds.
The problem is that after refreshing, the popover reference is destroyed and popover showed go up  to coordinate 0,0 when scroll page.
Can it be solved?

### CodePen demo

https://www.codeply.com/go/y2VQrjqdjf

### Steps to reproduce the problem

1.  Show popover
2.  Delete popover reference
3.  Scroll down

### What is the expected behavior?

Popover stay on current position
### What went wrong?

I dont know
### Any other comments?

Thanks in advance! (sorry for my bad english :( )

**Comment by FezVrasta** [comment]
That's a Bootstrap request, please open the ticket on their repository.
