### ISSUE TITLE
Wrong poper position an edge case

### ISSUE THREAD

**Issue by borm** [FezVrasta/popper.js#590]
Duplicate of https://github.com/souporserious/react-popper/issues/113

### CodePen demo
https://react-popper-example-fies9l.stackblitz.io/

### Steps to reproduce the problem

1.  Scroll to **Toggleable Popper Example** or **Standalone Popper Example**
2.  Make sure what element have position to bottom of viewport, in my case 73px
3.  Click to reference
![image](https://user-images.githubusercontent.com/4027842/37996755-658bb2a6-3221-11e8-998e-053fa7918c8a.png)

### What is the expected behavior?
The poper should be displayed on top of reference

### What went wrong?
The poper displayed on first time on bottom, then change position to top of reference
![ezgif-5-9b3c4143e4](https://user-images.githubusercontent.com/4027842/37996860-d265a814-3221-11e8-9bd6-e50e10c4ee81.gif)

**Comment by FezVrasta** [comment]
Please may you convert this example using the issue template (no React or anything else except for Popper.js)? This helps to debug the problem.

**Comment by FezVrasta** [comment]
The OP never replied with the additional resources I required.
