### ISSUE TITLE
Usage with React

### ISSUE THREAD

**Issue by schickling** [FezVrasta/popper.js#6]
Hi @FezVrasta. Thanks for this great package!

I haven't yet looked at it too much but I'd be very interested to learn how this could (and should?) be used together with ReactJS. I think this might also be very interesting for others and therefore worthy to be added to the Readme?

Looking forward to hear your thoughts!

**Comment by FezVrasta** [comment]
I'm very interested in adding full React.js support (along with Ember.js).

I'm working to move the code which applies the style to the popper into a dedicated modifier to make possible then to write a replacement modifier which will allow you to just export the coordinates to use them wherever you want.

**Comment by schickling** [comment]
Amazing!

**Comment by eek** [comment]
React support would be epic. If you need any beta testing, count me in! :)

**Comment by mgcrea** [comment]
@FezVrasta ideally extracting the core coordinate calculus to another module would be great, eg. `popper-engine`, that would enable easy integration with either JS or even CSS frameworks.

**Comment by FezVrasta** [comment]
refer to this PR please https://github.com/FezVrasta/popper.js/pull/11

**Comment by FezVrasta** [comment]
#11 has been merged into master and released as v0.3.0

Now we plan to add a deeper integration with React.js using the API provided by v0.3.0

Any feedback or suggestion here please :)

**Comment by FezVrasta** [comment]
I have written a simple implementation of a simple `PopperLoader` React component.

http://codepen.io/FezVrasta/pen/eZVJQZ

I'd like to get feedbacks from your to understand if this could be enough or if I should write something more. Thanks!

**Comment by FezVrasta** [comment]
I've updated the component to be more modular. It now takes as arguments the reference component, the popper component and the optional configuration.

http://codepen.io/FezVrasta/pen/eZVJQZ

**Comment by ebakan** [comment]
Here's a component I've been using that accepts the reference as its first child and the popper as its second child (a la [`react-tether`](https://github.com/souporserious/react-tether))

https://gist.github.com/ebakan/f3d94874a2e8bfbb06e3f9510c78ffd1

**Comment by FezVrasta** [comment]
thanks @ebakan I've added your component to the README file.

I think now we are good with React.js support.

63b9840de3adaf0d766b92749f8ad5bd40c14036
