### ISSUE TITLE
Popper inside an element with 'position: fixed' and with 'preventOverflow'

### ISSUE THREAD

**Issue by nadiam84** [FezVrasta/popper.js#60]
Hey there,

I'm trying to reproduce a pretty common situation: a popper inside an element with position:fixed, the popper goes outside of the parent's boundaries. It's a typical case for a popper inside a modal dialog for example.

And I can't make it work... The popper element doesn't positioning itself in the right place, and it doesn't move when I scroll the parent element.

### CodePen demo

http://codepen.io/nadiam84/pen/YWZmPv

### What is the expected behavior?
Expect it to be positioned relative to the target element. And move with it on scroll event.

Could you possible take a look?

**Comment by FezVrasta** [comment]
with:

```
modifiers: ['preventOverflow']
```

you are asking Popper.js to use `only` the `preventOverflow` modifier, this makes it behave weirdly

**Comment by nadiam84** [comment]
But it stays inside of the parent container in this case. What if I want it not to be clipped by the parent?

**Comment by FezVrasta** [comment]
Yes, Popper.js doesn't move elements around the DOM. If you want your popper to not being clipped by its parent you have to move it to the outside manually.

You may write a simple modifier to automatically move it but I would suggest to manage this inside your own code together the code that takes care of the creation of the DOM elements.
