### ISSUE TITLE
License missing from tooltip.js package.json

### ISSUE THREAD

**Issue by nerdkid93** [FezVrasta/popper.js#600]
### CodePen demo

n/a

### Steps to reproduce the problem

1.  Open `packages/tooltip/package.json`
2.  Notice there is no license field in the json file

### What is the expected behavior?

Since popper.js is distributed with the MIT license, each of its packages should specify MIT in their `package.json` files.

### What went wrong?

Without the license field in `package.json`, we have to manually whitelist `tooltip.js` in our script that checks out projects dependencies for packages with un-approved licenses.

### Any other comments?

n/a

**Comment by FezVrasta** [comment]
Thanks for the issue, Tooltip.js is released under a very restrictive and secret license, you have to pay $1 bilion for each project that depends on it.














LOL, I'll fix it.
