### ISSUE TITLE
No positioning with React portals in IE11

### ISSUE THREAD

**Issue by sa-eneidhart** [FezVrasta/popper.js#603]
Wasn't sure if I should put this here, or over at [react-popper](https://github.com/souporserious/react-popper/issues), let me know if I should move it there!

### Steps to reproduce the problem

I've been making use of the advice from [this thread](https://github.com/souporserious/react-popper/issues/57) to allow elements to "escape" from a modal with `overflow: scroll`, and it's been working great in all browsers I need it to except for IE11. React-portal and react-popper both seem to work fine individually in IE11, but a popper element within a portal seems to be unaffected by the `transform: translate3d(...)` which is being used to place it; it always appears in the upper-left corner. The component within the `<Popper />` tag in question is a div with fixed positioning, giving a structure that looks more or less like this:

```jsx
<div style={{ overflow: scroll }}>
  <Manager>
    <Target>
      <MyTargetComponent />
    </Target>
    <Portal>
      <Popper>
        <div style={{ position: fixed }} />
      </Popper>
    </Portal>
  </Manager>
</div>
```

### What is the expected behavior?

The Popper component should be attached to the Target component.

### What went wrong?

The Popper component appears in the top-left corner of the screen.

**Comment by FezVrasta** [comment]
Hi, please file the issue on the react-popper repository and make sure to follow the issue template. Without a repro nobody can help you.
