### ISSUE TITLE
Do not flip if flipped doesn't fit 

### ISSUE THREAD

**Issue by whitecolor** [FezVrasta/popper.js#604]
I found this useful that if flipped position overflowed too to return it back to original.

Say we have the following options:

```
placement = 'bottom'
preventOverflow.boundariesElement = 'window'
flip.boundariesElement = 'scrollParent'
```

Say we have a situation, 
1) that popper placed at the `bottom` overflows `scrollParent` but not `window`, 
2) `flip` modifier will change  placement to the `top` (because bottom is overflowed). But say, after this popper placed at the `top` **will overflow the scrollParent.** too - flip will is not checking it will leave new `top` placement.
3)  Next `preventOverflow` modifier  will check the position (now poper is placed at the top). And say we have a situation that **it overflows window**. so will reposition popper to be inside window - and thus position will not be corrent, it will be shited (will not point to the reference element).

More correct behaviour in this case would be that flip modifer after flipping popper to the top, would try to flip it back, it would return origical "bottom" position in case if new flipped position was overflowed.

@FezVrasta 
I think the case is quite basic, tried to make my self clear, though I see that description of the situation may look kind of cumbersome/confusing.

**Comment by BrianBu01** [comment]
I think the proper title for this bug should have been, "when you flip, I flip, we flip"

**Comment by whitecolor** [comment]
> I think the proper title for this bug should have been, "when you flip, I flip, we don't fit"

Or better:

"Fit what you flip before your flipped does not fit."

**Comment by atomiks** [comment]
Isn't this #550?

**Comment by FezVrasta** [comment]
Yes right! Closing as dupe
