### ISSUE TITLE
Popper is not in the correct position and text overflow the window.

### ISSUE THREAD

**Issue by thanass** [FezVrasta/popper.js#605]
Hi,
I want to create a very simple tooltip, without arrows, on hover of an element.
The popper I will create it dynamically with Jquery and I will apppend it the element that I want to add the tooltip. In my example I created a button and on hover I show and hide the tooltip. (I choose to make it with popper.js instead of tooltip.js and maybe I am wrong with that choice.

My problems:

1.  In that code example the popper is not set in the correct position

### CodePen demo
https://codepen.io/thanassis/pen/oqQEvq

### What is the expected behavior?
1. I wanted the popper in the correct position.
2. On mobile view: I wanted the popper text to adjust in side the window. 

### What went wrong?
1. Popper is not set in the correct position.
2. Text is overflowed out of the window on mobile view.

Thank you in advance,
all my best!

**Comment by FezVrasta** [comment]
You need to manually limit the size of the tooltip to fit in the window. Popper.js doesn't provide this functionality.

**Comment by thanass** [comment]
And what about the wrong position?

**Comment by FezVrasta** [comment]
If you want it to be positioned on the right you should set `placement` to `right`, you are setting it to `bottom`

**Comment by thanass** [comment]
I wanted to set bottom but exactly under the button

**Comment by FezVrasta** [comment]
![image](https://user-images.githubusercontent.com/5382443/38457303-b853feb0-3a8e-11e8-9496-2f4b3b59b247.png)

What's wrong with this?

**Comment by thanass** [comment]
I mean I want the popper start where the button starts

**Comment by FezVrasta** [comment]
Try `bottom-start`?
