### ISSUE TITLE
Unintuitive popover position when reference element is inline, several words long, and spans two lines

### ISSUE THREAD

**Issue by beowulfenator** [FezVrasta/popper.js#609]
### CodePen demo

https://codepen.io/anon/pen/VXRYxj

### Steps to reproduce the problem

If a reference element is inline and it starts on one line and is carried over to the next line, the popover is displayed as seen in the codepen.

### What is the expected behavior?

Is it possible to position the popover closer to one of the edges of the reference element?

### What went wrong?

In this case the popover is positioned in an unintuitive way.

### Any other comments?

Is this the expected behavior?

**Comment by FezVrasta** [comment]
Sorry I'm from mobile so I can't be very specific. There was an issue a long time ago that asked for specific support for this case but nobody ever worked on it and I closed it proposing to implement it as a 3rd party modifier.

**Comment by beowulfenator** [comment]
I guess you're right about a custom modifier. Can you please also comment on the issue about the floating navbar (#518)? That one is definitely a common problem. Thanks!

**Comment by FezVrasta** [comment]
So, the issue I was referring to is #9
