### ISSUE TITLE
node_modules/popper.js/src/utils/debounce.js not found while build on ng-packagr

### ISSUE THREAD

**Issue by daituzhang** [FezVrasta/popper.js#610]
Hi team,
Thank you for the awesome library. 
I'm using popper.js in an angular app and it was built correct until I try ng-packagr
I was importing popper.js as
`import Popper from 'popper.js';`
and run `ng-packagr`

on
node: v7.75
angular: v5.2.0
popper: 1.14.3

I got error

```
BUILD ERROR
ENOENT: no such file or directory, open '/Users/vfd049/workspaces/dealer/ui-components-angular-lib/node_modules/popper.js/src/utils/debounce.js'
Error: ENOENT: no such file or directory, open '/Users/vfd049/workspaces/dealer/ui-components-angular-lib/node_modules/popper.js/src/utils/debounce.js'
```

There's no `src` folder in `popper.js`, I'm not sure why `ng-packagr` would looking for that folder.
Is there any way to fix it? Thank you!

**Comment by FezVrasta** [comment]
Why are you trying to build Popper.js from source?

Anyway, if you want to build it from source, you must clone the git repository, the npm package doesn't include the source.

**Comment by daituzhang** [comment]
@FezVrasta Is there a way that I still use npm package, and specify the source myself?

**Comment by daituzhang** [comment]
@FezVrasta Also how can I avoid building popper.js from source?

**Comment by FezVrasta** [comment]
I don't know how ng-packagr works, I never used it.

You shouldn't need to compile Popper.js from source, I don't know why your build pipeline is trying to do that. Sorry.

**Comment by daituzhang** [comment]
Thank you @FezVrasta I will find out how to avoid that.
