### ISSUE TITLE
Improve modifiers API

### ISSUE THREAD

**Issue by FezVrasta** [FezVrasta/popper.js#62]
I would like to change the way the modifiers are managed, this will be a breaking change planned for the v1 release.

## Migration instructions

To add a custom modifier, define inside the `modifiers` option object, an object containing the properties `order`, `enabled` and `function`.

- each object must be assigned to a property with the name of the modifier, this name will be used internally to identify and refer this modifier
- `order`: order of execution of the modifier, the default modifiers configuration is:
```
shift:              { order: 100, enabled: true, function: modifiersFunctions.shift },
offset:             { order: 200, enabled: true, function: modifiersFunctions.offset },
preventOverflow:    { order: 300, enabled: true, function: modifiersFunctions.preventOverflow },
keepTogether:       { order: 400, enabled: true, function: modifiersFunctions.keepTogether },
arrow:              { order: 500, enabled: true, function: modifiersFunctions.arrow },
flip:               { order: 600, enabled: true, function: modifiersFunctions.flip },
applyStyle:         { order: 700, enabled: true, function: modifiersFunctions.applyStyle }
```
- `enabled`: `true` to enable it, `false` to disable it
- `function`: the function that describes your custom modifier (the modifiers API is unaltered)

`modifiersIgnored` is deprecated, use `enabled: false` if you want to disable a specific modifier.

**Comment by FezVrasta** [comment]
Some work has been made on `v1-dev`, still working on it.

**Comment by FezVrasta** [comment]
Finished inside v1-dev, the final API specification is described in the first post of this issue and has been linked inside the changelog

**Comment by vssadineni** [comment]
I have a doubt ? regarding Tooltip.js. Options.Trigger takes only one item but in my case I need **hover** and **focus** both. how can I achieve that.

**Comment by FezVrasta** [comment]
you can put multiple values space separated

**Comment by vssadineni** [comment]
Thank you. It works.

**Comment by tang-love-1314** [comment]
how to get js ？
