### ISSUE TITLE
Scroll lag due to `updateBound` on `scroll` event

### ISSUE THREAD

**Issue by mhluska** [FezVrasta/popper.js#624]
### CodePen demo

none

### Steps to reproduce the problem

1.  Open popper with 100 items and `overflow-y: scroll` on the contents.
2.  Scroll, notice scroll lag

### What is the expected behavior?

Scroll should not lag

### What went wrong?

Scroll event fires updateBound which seems costly and pointless if the size of the popper doesn't change.

### Any other comments?

The scroll callback is bound [here](https://github.com/FezVrasta/popper.js/blob/master/packages/popper/src/utils/setupEventListeners.js#L38). Why do we need to updateBound on scroll? Can it be made opt-out if the user knows he will not need to be updating bounds?

I am using `popper.js@1.14.1` as part of the Ember library `tooltip.js@1.2.0`.

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.

**Comment by mhluska** [comment]
@FezVrasta which part of the issues template did I not follow? Do you require a CodePen for every issue?

**Comment by FezVrasta** [comment]
Yes I need a codepen to see the problem. Thanks

**Comment by mhluska** [comment]
So then why didn't you close [this bug](https://github.com/FezVrasta/popper.js/issues/604)? Or [this one](https://github.com/FezVrasta/popper.js/issues/535)?

**Comment by ralphpig** [comment]
Hey I'm having the same problem and would like to expand on this issue.

I'm using [vue-tooltip-directive](https://github.com/hekigan/vue-directive-tooltip), which is just a directive wrapper for Poppers.js.

Here is a [Codepen](https://codepen.io/ralphpig/pen/zaKOEq) showing this issue.

The lag seems to be coming from a scroll listener on the parent for each child.

**Comment by ralphpig** [comment]
Was able to fix this with: `eventsEnabled: false`, which disabled scroll listeners.

Not sure of other consequences, however, for a large list of scrollable Tooltips this works.
