### ISSUE TITLE
opacity don`t changes on hover

### ISSUE THREAD

**Issue by Krasnov8953** [FezVrasta/popper.js#626]
### CodePen demo

https://codepen.io/krasnov8953-the-vuer/pen/wjqxyw

### Steps to reproduce the problem

1.  Try to show tooltip with option { trigger: hover }

### What is the expected behavior?

If in options { trigger: hover } css-class **.tooltip** have to { opacity: 1 } on mouseenter

### What went wrong?

On hover .tooltip still have { opacity: 0 }

### Any other comments?

I have to set manually  .tooltip { opacity: 1 } to make it works

**Comment by FezVrasta** [comment]
> [`getElementsByClassName`](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementsByClassName) returns an array-like object of all child elements which have all of the given class names. 

https://codepen.io/FezVrasta/pen/JvymEG
