### ISSUE TITLE
[tooltip.js] Get tooltip element

### ISSUE THREAD

**Issue by strarsis** [FezVrasta/popper.js#629]
How can I get the tooltip element that is shown by tooltip.js (popper.js)?
Apparently there is no public API method for this, but 
also the internal ones cannot be used from the outside.
I want the popup to close when the user hovers over it instead 
staying open, hence I need the element for a adding handlers.

**Comment by FezVrasta** [comment]
There's no support for it. You can access the internal Popper.js instance (`._popperInstance`) and read the popper element from it.

**Comment by strarsis** [comment]
@FezVrasta: Thanks!
```js
        var tooltip = new Tooltip(
          el, {
            placement: 'right',
            html: true,
            title: openTooltipEl.innerHTML,
            trigger: 'hover focus',
            container: container,
          }
        );

        console.log(tooltip._popperInstance);
````
I get `undefined`. Is this version dependent?

**Comment by FezVrasta** [comment]
Sorry, it's `popperInstance`, my bad

**Comment by strarsis** [comment]
@FezVrasta: I should have created a minimal codepen for illustrating the issue.
`popperInstance` is `undefined` but I could well access it incorrectly.
Pen: https://codepen.io/strarsis/pen/erKMgy

**Comment by FezVrasta** [comment]
You need to call `Tooltip#show` at least once before the instance gets generated.
https://codepen.io/strarsis/pen/erKMgy?editors=1111

**Comment by strarsis** [comment]
@FezVrasta: Thanks! When the tooltip is hovered, it should hide. Would attaching some hover/touch/click event handlers to the tooltip element for calling `hide()` a good approach or can this be solved even better?

**Comment by FezVrasta** [comment]
This should work.
https://codepen.io/FezVrasta/pen/aGKYER
