### ISSUE TITLE
Performance optimization: rate-limiting by debouncing or throttling the on scroll and resize event listeners functions calls

### ISSUE THREAD

**Issue by creativeprogramming** [FezVrasta/popper.js#63]
I'm talking about rate limiting this code:

```
// NOTE: 1 DOM access here
        this.state.updateBound = this.update.bind(this);
        root.addEventListener('resize', this.state.updateBound);
```

```
        // NOTE: 1 DOM access here
        this.state.updateBound = this.update.bind(this);
        root.addEventListener('resize', this.state.updateBound);
```

As it can be a simpler and more effective solution for https://github.com/FezVrasta/popper.js/pull/17

To do that please see some inspiration here:

http://ejohn.org/blog/learning-from-twitter/

Anyway that's a **debouncing** and not throttling, you don't want it as it will prevent any smooth animation during user interactions

![image](https://cloud.githubusercontent.com/assets/954291/17086349/e091a884-51ef-11e6-81c4-2d5da1e040e5.png)
_Credits: http://benalman.com/projects/jquery-throttle-debounce-plugin/_

What you want instead is '**throttling** with **trailing edge**'  to get ensured the invokation of the update **at the end** of scrolling or resizing user interaction but keeping a smooth (but not resource hungry if limited in fps) visual updating during the user interaction

![image](https://cloud.githubusercontent.com/assets/954291/17086346/c35b3410-51ef-11e6-999b-18401007eb18.png)
_Credits: http://benalman.com/projects/jquery-throttle-debounce-plugin/_

To achieve that you can use requestAnimation frame too, see for inspiration 

https://gist.github.com/paulmillr/3118943

but that solution needs to be improved with a 'scrollend' (throttling trailing end) invokation ensurement - e.g. a debouncer too? )

What I suggest instead is to not use requestAnimation frame at all, as it's actually not intended for 'user input initiated' repaints but for 'javascript initiated' repaints, but use a nice throttling like the underscore.js one:

http://www.tivix.com/blog/using-underscorejs-for-easy-performance-wins/

but of course not with 'immediate' with 'trailing edge' option:

```javascript
var maxFps = this._options.maxFPS; 
var minWaitMillis  = 1000/maxFps; //eg. 16 if 60fps
var throttledUpdateBound = this._.throttle(this.state.updateBound,minWaitMillis,{leading:true,trailing: true});
root.addEventListener('resize', throttledUpdateBound );
root.addEventListener('scroll', throttledUpdateBound );
```

**Comment by FezVrasta** [comment]
As you already seen I've tried to work on perf optimization on #17 but got some troubles with it.

If you have time and you are willing to send over a PR to me with your idea I would be more than happy to review it and merge it.

**Comment by creativeprogramming** [comment]
I'm working at it good results, soon a pr

**Comment by FezVrasta** [comment]
Closing, track the progress of the performance improvements at #17
