### ISSUE TITLE
lightweight version (question/suggestion)

### ISSUE THREAD

**Issue by yairEO** [FezVrasta/popper.js#632]
Hey, great lib, really like it. been using Tether.js for many years and glad to get rid of it since the source code was really really bad.

I need to use popper for an extremely simple positioning system for dropdown list which serves as an auto-complete dropdown in my [Tagify repo](https://yaireo.github.io/tagify/) .

Problem is, `popper.js` is way _way too heavy_ for my humble needs. is there a plan to create a **lightweight version**, maybe 10% of the current source code, that could cover the most basic use-cases, (modern browsers only)?

it would really be an overkill to force people to include `popper.js` just to have an autocomplete dropdown for tags (as *not* shown in my repo's demo currently)

Thanks brother

**Comment by kyleoliveiro** [comment]
Was about to open a similar issue, till I saw this.

Seems like Popper used to be about [half the size it is today (~3.5kb gzip)](https://github.com/twbs/bootstrap/issues/19673).

I am also using Popper just for simple positioning. Would be great if there is a "lite" version available :)

**Comment by FezVrasta** [comment]
v2 is going to be way more lightweight, you can read about it here https://github.com/FezVrasta/popper.js/issues/617#issuecomment-439630720
