### ISSUE TITLE
Cannot center a popper on the screen

### ISSUE THREAD

**Issue by rwwagner90** [FezVrasta/popper.js#642]
### CodePen demo

https://codepen.io/anon/pen/WyzXEB

### Steps to reproduce the problem

1.  Go to the codepen and observe the box is not centered

### What is the expected behavior?

I would expect an offset of `50vh` and `positionFixed: true` to allow me to position a popper in the center of the screen, not attached to any specific element, but just attached to html or body.

### What went wrong?

The offsets do not work reliably, and there seems to be no way to position a popper always fixed in the center of the screen.

### Any other comments?

I really need support for centering a popper in the window, so I can finish converting Shepherd to use popper. Most of it works great, but it also needs to support showing a popper in the middle of the window centered horizontally and vertically, not attached to any elements.

**Comment by bennymeier** [comment]
I need help too. Im using my own way to position elements in the window but I'd safe a lot of time if I can do this with popper.

**Comment by rwwagner90** [comment]
We ended up using `computeStyle` for this and manually setting the styles.

```js
computeStyle: {
  enabled: true,
  fn(data) {
    data.styles = Object.assign({}, data.styles, {
      left: '50%',
      top: '50%',
      transform: 'translate(-50%, -50%)'
    });

    return data;
  }
}

**Comment by wscourge** [comment]
Little improvement on @rwwagner90 answer if you don't want your tooltip to be half window width horizontally:

```
modifiers: {
  computeStyle: {
    enabled: true,
    fn(data) {
      /* eslint-disable-next-line no-param-reassign */
      data.styles = {
        ...data.styles,
        position: 'fixed',
        left: `${(window.innerWidth - data.popper.width) / 2}px`,
        top: '50%',
        transform: 'translateY(-50%)'
      };

      return data;
    }
  }
}
```

**Comment by tminich** [comment]
In case someone needs this for Popper v2:

```ts
modifiers.push(<ComputeStylesModifier>{
    name: 'computeStyles',
    enabled: true,
    fn({state}) {
        state.styles.popper = {
            ...state.styles.popper,
            position: 'fixed',
            left: `${(window.innerWidth - state.rects.popper.width) / 2}px`,
            top: '50%',
            transform: 'translateY(-50%)',
        }

        return state
    },
})
```

**Comment by rwwagner90** [comment]
@atomiks is there a way to do this with the new Floating UI?

**Comment by atomiks** [comment]
You don't need Floating UI for that, just use pure CSS

This:

```js
        state.styles.popper = {
            ...state.styles.popper,
            position: 'fixed',
            left: `${(window.innerWidth - state.rects.popper.width) / 2}px`,
            top: '50%',
            transform: 'translateY(-50%)',
        }
```

Is just:

```css
position: fixed;
left: 50%;
top: 50%;
transform: translate(-50%, -50%);
```

**Comment by rwwagner90** [comment]
@atomiks we want to use Floating UI to create all the popovers, as we did with popper in the past. Doing so forces us to need `!important` on the styles to override the styling Floating UI is applying. Is there a way to opt out of styles?

Right now, this works, but I don't like needing to use `!important`.

```css
  .shepherd-element.shepherd-centered {
    left: 50% !important;
    position: fixed !important;
    top: 50% !important;
    transform: translate(-50%, -50%);
  }
```

**Comment by rwwagner90** [comment]
Sorry, disregard what I said above, we were setting things weird in our library. I got it to work now! 🎉
