### ISSUE TITLE
Internet Explorer: Wrong offsetParent with containers styled as tables using CSS

### ISSUE THREAD

**Issue by apisselhoy** [FezVrasta/popper.js#646]
Hi,

with Internet Explorer 11 I ran into a problem of a wrong positioning due to wrong calculated reference positions.
I found the cause for this in the special handling of TD and TABLE-tags in getOffsetParent - the special handling wont' work on other HTML-tags styled as table-cells or tables using css.

`function getOffsetParent(element) {
...
  // .offsetParent will return the closest TD or TABLE in case
  // no offsetParent is present, I hate this job...
  if (['TD', 'TABLE'].indexOf(offsetParent.nodeName) !== -1 && getStyleComputedProperty(offsetParent, 'position') === 'static') {
    return getOffsetParent(offsetParent);
  }

  return offsetParent;
}
`
I solved the issue by removing the first part of the condition  - so it always goes up in the dom if position === 'static'. jQuery does the same in their implementation of offsetParent.

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
