### ISSUE TITLE
Tooltips do not position correctly if the wrapper has an overflow: auto

### ISSUE THREAD

**Issue by khalidadil** [FezVrasta/popper.js#648]
I am running into a situation where an element inside a wrapper with an `overflow: auto` does not position the popper correctly.

### CodePen demo

https://codepen.io/khalidadil/pen/OEGRJG

### Steps to reproduce the problem

1. Create a div and wrap it in another div with the CSS `overflow: auto`.
2. Create a popper and position the popper on top of the nested div.

### What is the expected behavior?

The popper should be positioned on top of the nested div.

### What went wrong?

The position of the popper is calculated incorrectly.

### Any other comments?

This has been tested on Chrome v67.0.3396.99 on Mac OSX 10.11.6.

**Comment by FezVrasta** [comment]
It's the correct behavior, the `preventOverflow` modifier uses by default, as boundaryElement, the `scrollParent`, you can change it to `viewport` or `window` or anything else supported.

**Comment by khalidadil** [comment]
I can't seem to get this to work with either the `escapeWithReference` or `boundariesElement` options. Is there something I'm doing incorrectly?

https://codepen.io/khalidadil/pen/OEGRJG

**Comment by FezVrasta** [comment]
https://codepen.io/FezVrasta/pen/bKJgwx

**Comment by khalidadil** [comment]
Thank you!
