### ISSUE TITLE
Set same distance from border for the arrow keeping tooltip centered 

### ISSUE THREAD

**Issue by juanmaguitar** [FezVrasta/popper.js#649]
As you can see in this demo 
![demo](https://media.giphy.com/media/39lYYmxrCq31vK9PzD/giphy.gif)

if I set a placement of "top-start" the arrow is placed at different distances from the left border

Is there any way I can force (ideally through `modifiers` ) the tooltip to have a fixed distance of, let's say, 8px (no matter the width of the referenced text) from the sides while keeping the `arrow` pointing to the center of the referenced text?

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
