### ISSUE TITLE
Tooltip is moving when there is not enough space

### ISSUE THREAD

**Issue by aortmannm** [FezVrasta/popper.js#651]
Hi,

I have the case that my popper is positioned on the top of my element and the tooltip is much bigger than the reference element. The behaviour when there is not enough space on the right the tooltip is staying on top but shifting to the left. 

I want that the tooltip is not shifting but it should flip to the left of the element. I can't find a working option for this, any solution here right now?

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
