### ISSUE TITLE
Position breaks when the reference has an SVG element directly inside

### ISSUE THREAD

**Issue by diegohaz** [FezVrasta/popper.js#653]
### CodePen demo

https://codepen.io/anon/pen/djNawe

(remove the SVG element to see the difference)
(if you wrap the SVG in a `div`, it also works)

### Steps to reproduce the problem

1.  Put the popover inside its reference;
2.  Make the reference absolutely positioned and give it some `top` and `left` values;
3.  Put an SVG element inside the reference.

### What is the expected behavior?

Removing the SVG element makes it work as expected:
![image](https://user-images.githubusercontent.com/3068563/43040988-c116a7a8-8d29-11e8-8e32-0431131673e3.png)

### What went wrong?

When it has an SVG element, it breaks:

<img width="160" alt="screen shot 2018-07-21 at 21 07 14" src="https://user-images.githubusercontent.com/3068563/43040999-141a5d8c-8d2a-11e8-8f70-8ed095ac5aa6.png">

### Any other comments?

I'm trying to integrate Popper.js on my component library (https://reakit.io).

**Comment by piglovesyou** [comment]
No, `getOffsetParent` itself has a functionality to skip and try the `nextElementSibling`. I'll try this.
