### ISSUE TITLE
Cannot use tooltip's option placement with function ???

### ISSUE THREAD

**Issue by KytoSai** [FezVrasta/popper.js#654]
I use webpack 4 with two package: 
"popper.js": "^1.14.3"
"tooltip.js": "^1.2.0"

I have config tooltip with option:

```javascript
new Tooltip(document.getElementById('ttip'),{
  html: true,
  placement: 'left',
  title () {
    return this.dataset.ttipTitle
  }
})
```

It work fine. But i try change placement with function

```javascript
new Tooltip(document.getElementById('ttip'),{
  html: true,
  placement () {
    return 'left'
  },
  title () {
    return this.dataset.ttipTitle
  }
})
```

It have error

```javascript
Uncaught TypeError: placement.indexOf is not a function
```
I don't know why. Please help me fix it !

Thank you !

**Comment by KytoSai** [comment]
Document ???

http://prntscr.com/k9r7ke

**Comment by FezVrasta** [comment]
The documentation is wrong, I'm sorry. We need to update it.

**Comment by KytoSai** [comment]
Thank you ! I like popper.js plugin

**Comment by piglovesyou** [comment]
@FezVrasta So all the `PlacementFunction` in the source code are supposed to be deleted? I'll take care of it.

**Comment by piglovesyou** [comment]
It can be fixed.
