### ISSUE TITLE
dist folder is missing in version 1.14.4

### ISSUE THREAD

**Issue by pfonseca** [FezVrasta/popper.js#662]
### What went wrong?

Maybe you forgot to add the dist folder in version 1.14.4

**Comment by FezVrasta** [comment]
Where do you see it missing?

On npm is available:
https://unpkg.com/popper.js@1.14.4/dist/

**Comment by pfonseca** [comment]
You are right. My bad.

**Comment by htoomik** [comment]
I also have the problem with a missing dist folder in version 1.14.4.
We use bower for our front end dependencies, and popper is a dependency via bootstrap's bower.json file.

**Comment by FezVrasta** [comment]
@htoomik please let me know if it's working properly now.
