### ISSUE TITLE
Wrong position in IE11 if child has scroll

### ISSUE THREAD

**Issue by MhMadHamster** [FezVrasta/popper.js#663]
### CodePen demo

The bug appears only in IE11 (havent tested it in 10)
link to the full view cause it does not work with js and css editors
https://codepen.io/MhMadHamster/full/oMyryy/

### Steps to reproduce the problem

1.  Open code pen
2.  click on the red block

### What is the expected behavior?

the block with list should appear centered below the ref block

### What went wrong?
block is not centered, but if you start scrolling it will get centered

### Any other comments?
I found that this would work only if applying scroll to the popper container itself rather than child element.
I discovered that the offsetWidth of the element somehow larger than it actually is on the first calculation: https://github.com/FezVrasta/popper.js/blob/1ddf685b14489a63e389c0b52aaa9fc7484b9316/packages/popper/src/utils/getOuterSizes.js no idea if there is possible fix or some hacky solution to this problem

**Comment by MhMadHamster** [comment]
Ok, maybe helps someone, i discovered that it could be fixed by rather setting `overflow-y: scroll` or `height` instead of `max-height`, both of the solutions do not suit my case unfortunately :(

**Comment by FezVrasta** [comment]
I guess it's going to work if you call a `scheduleUpdate` after the element gets visible, it's not nice but at least you can go on with your project.

**Comment by MhMadHamster** [comment]
It seems like i found a solution via css, you need to apply `display: flex;` & `flex-direction: column;` to the element with scroll: https://codepen.io/MhMadHamster/full/JBZgWe

@FezVrasta I, however, would gladly try to fix this case in lib itself, do you have any thoughts on how to get the original size? i tried different `width` props on an element and it always gives like +20px of the original size. The only thing i can think of right now is smth like check if the children have a scroll and subtract the scroll size from the element, could be expensive probably, if a lot of nested elements.

**Comment by FezVrasta** [comment]
I'm not sure, IE has a lot of quirks... I don't even know if it's worth the effort to continue to support it.

For sure I'll not support it on v2 anyway.

**Comment by MhMadHamster** [comment]
Closing than, it does not seem to be worth fixing since the css solution mentioned above is works well and it's not that "hacky".
