### ISSUE TITLE
Bower install 1.14.4, no dist folder?

### ISSUE THREAD

**Issue by weilinzung** [FezVrasta/popper.js#666]
Bower install v1.14.4, no dist folder?

**Comment by FezVrasta** [comment]
The dist folder is there 🤷‍♂️

https://github.com/FezVrasta/popper.js/tree/v1.14.4

Something off with Bower?

**Comment by weilinzung** [comment]
I think it is only cloning the master branch and not from the tag. I will test again and let you know, thanks! @FezVrasta

**Comment by FezVrasta** [comment]
Bower bases its versions on the Git tags, it always worked fine the way this repository is setup.

**Comment by weilinzung** [comment]
Never mind, I did `bower cache clean` then everything back to normal, just not sure why it downloaded the one without `dist` at first place. good to close!

**Comment by nadavshabtai** [comment]
I have no dist folder in 1.14.4 also using bower...
