### ISSUE TITLE
interactive tooltip only available from the arrow

### ISSUE THREAD

**Issue by mikila85** [FezVrasta/popper.js#667]
I think this explains it the best:
![tooltip js](https://user-images.githubusercontent.com/3965957/44192191-2e7cbc80-a137-11e8-85a6-25258c8644e3.gif)

User can only interact with the tooltip if he goes through the small arrow which is a UX hazard!
Any way to fix this without hacking the CSS completely and potentially destabilizing the component?

**Comment by FezVrasta** [comment]
You should make the tooltip an invisible box, and put inside it the "visible" tooltip box with the background color, with some margin.

**Comment by mikila85** [comment]
**so it's a bug**, and you can't fix it so i need to do CSS or HTML fixes for this?

didnt even understood the visible box inside invisible box which has background add margin to it... what??

**Comment by FezVrasta** [comment]
if you have time to implement a better fix feel free to send a PR
