### ISSUE TITLE
Tooltip.updateTitleContent() and default options.innerSelector don't work well together

### ISSUE THREAD

**Issue by rehfeldchris** [FezVrasta/popper.js#676]
### CodePen demo

https://codepen.io/anon/pen/WgRoZp?editors=1111

### Steps to reproduce the problem

1.  Notice that all 4 tooltips start out with "default title", as they should
2.  Hover over all 4 li elements
3.  Notice that only 1 tooltip has updated to "updated title"

### What is the expected behavior?

All 4 should have updated.

### What went wrong?

The code you use in your `_updateTitleContent` (in index.js) function looks like:

```
  _updateTitleContent(title) {
    if(typeof this._tooltipNode === 'undefined') {
      if(typeof this.options.title !== 'undefined') {
        this.options.title = title;
      }
      return;
    }
    const titleNode = this._tooltipNode.parentNode.querySelector(this.options.innerSelector);
    this._clearTitleContent(titleNode, this.options.html, this.reference.getAttribute('title') || this.options.title)
    this._addTitleContent(this.reference, title, this.options.html, titleNode);
    this.options.title = title;
    this.popperInstance.update();
  }
```

Why do you use `.parentNode`? I think that should be removed. I would think the `innerSelector` should be scoped so it selects descendants of the root tooltip element. But, by using parentNode, you select from the next parent up instead (in my case, parentNode is the `ul` element). This causes the innerSelector to find too many matches, and an arbitrary single match is chosen by `querySelector()`, causing only a single tooltip update.

Also, note that this is only a problem when you have more than 1 tooltip with the same parent, like I do with my ul and 4 li tooltip children.

### Any other comments?

This is default config, and it's broken. I don't think telling people to choose a more distinct/selective `innerSelector` would be a good solution to this. It would work, but pushes tedious bookkeeping onto the client to create unique ids and stick them into the `innerSelector`. 

Off topic - thanks for the great work on this lib!

**Comment by FezVrasta** [comment]
Good point, the idea was to allow to have arrow elements outside of the tooltip, but I didn't consider this case.

Please feel free to send a PR to get rid of the `.parentNode` bit.

**Comment by alexturpin** [comment]
I've just run into this issue as well! I'd love to see the PR merged.

**Comment by vimko** [comment]
> Good point, the idea was to allow to have arrow elements outside of the tooltip, but I didn't consider this case.
> 
> Please feel free to send a PR to get rid of the `.parentNode` bit.

if ```container``` set ```body```,this problem still exists.

**Comment by jsmnbom** [comment]
@FezVrasta It looks like this has been merged?
If so, could you maybe release a new release on NPM with the fix?

**Comment by cooney** [comment]
@FezVrasta we would also be interested in an updated release on NPM with this fix.

**Comment by FezVrasta** [comment]
I already released the fix
