### ISSUE TITLE
Popper.js Named index.js

### ISSUE THREAD

**Issue by Nick-lab** [FezVrasta/popper.js#680]
took me forever to figure out this is the correct file to import into basic webpage

**Comment by Nick-lab** [comment]
Never mind what JS file is needed to use Popper in a normal vanilla site. no Ionic no Angular just strait HTML

**Comment by Nick-lab** [comment]
wow CDN but no file in the repo. . . 
https://media.giphy.com/media/HiBNkOKRhBJew/giphy.gif

**Comment by FezVrasta** [comment]
The repository is for the source code, not for the builds. You can checkout the git tags if you want the builds.
