### ISSUE TITLE
Blurry text

### ISSUE THREAD

**Issue by akinuri** [FezVrasta/popper.js#681]
I'm on Windows 10 and using Chrome 68. The content (text) of the tooltip looks blurry. I think that's because of the `transform: translate3d(498px, 78px, 0px);`.

My screen dimensions are 1920x1080 with %125 scale. This scale results in a zoom in the browser. `devicePixelRatio` is set to `1.25` by default. So browser window dimensions are 1536x728. This scale distorts the css transformations. To get a clear look, I'd have to zoom out of the page (%80 to get the devicePixelRatio to 1).

If I use `left` and `top` instead of `transform`, things are okay. So I'm wondering is there a particular reason behind using transform instead of left and top? It the reason is arbitrary, it'd be nice to have it optional.

PS: This might be a Chrome specific problem. Text looks allright in Firefox.

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.

**Comment by CarlinGebyte** [comment]
Is not of the browser, when the dropdown have a scroll the text is blurry
