### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by QuentinMcCarthy** [FezVrasta/popper.js#684]
### CodePen demo

https://codepen.io/pen?template=wGqJEz

(This issue cannot be reproduced in codepen)

### Steps to reproduce the problem

1.  Create a Vagrant server with Node in a project.
2.  Route popper.js from node_modules through Node
3.  Perform a GET request to Node for popper.js

### What is the expected behavior?

No errors to be produced in the console

### What went wrong?

The error which is the title of this issue is being produced in the console. It occurs on line 4 of popper.js; which is minified and thus difficult to find the origin.

### Any other comments?

The issue can be easily reproduced by cloning and running the [server we are working on](https://github.com/QuentinMcCarthy/ocular-web-app-portfolio). This issue was occurring before with a google charts npm package; the same exact error. It seems as though it's an issue with one of the servers not recognising the command "export". I am unsure how this affects the actual usage, as of yet we haven't used popper.js, we are using it for Bootstrap.

When googling the error beforehand with google charts, one solution mentioned was to use module.exports rather than simply export.

**Comment by FezVrasta** [comment]
Popper.js is javascript client side code, it has nothing to do with your Vagrant environment, you are simply using the wrong build dist target. The README explains it very well.

**Comment by QuentinMcCarthy** [comment]
> Popper.js is javascript client side code, it has nothing to do with your Vagrant environment, you are simply using the wrong build dist target. The README explains it very well.
I have no clue what the README is referring to. Can you please tell me which one I should be using?
