### ISSUE TITLE
No way to stick to position initially decided by the flip modifier

### ISSUE THREAD

**Issue by dvp0** [FezVrasta/popper.js#685]
https://codesandbox.io/s/yj0l1w5yrj

I want popper flip functionality to decide initial placement and than want to turn off the flip automation.  In other words, want it to stick to that initial placement regardless of how I scroll. 

Any way to do this easily ?

**Comment by dvp0** [comment]
Opened for react-popper : https://github.com/FezVrasta/react-popper/issues/216

**Comment by rukfas** [comment]
Hhh

Sent from Yahoo Mail on Android 
 
  On Wed, Sep 19, 2018 at 12:49 AM, dev<notifications@github.com> wrote:   
Closed #685.
