### ISSUE TITLE
Enable closeOnClickOutside for manual triggering

### ISSUE THREAD

**Issue by alexturpin** [FezVrasta/popper.js#689]
### Steps to reproduce the problem

1.  Initialize a popper with its `trigger` option set to `'manual'` and its `closeOnClickOutside` set to `true`
2.  Manually trigger the popper by calling `.show`
3.  Try to click outside of the popper

### What is the expected behavior?

The popper should close.

### What went wrong?

The popper doesn't close. This is on purpose and documented, but I think it makes sense for the option to work for manual triggering. As of now, I have to write extra code to make this happen.

### Any other comments?

I'm happy to provide a PR with this feature if it is deemed that it should be part of the library.

**Comment by FezVrasta** [comment]
Dupe of #688
