### ISSUE TITLE
RTL support?

### ISSUE THREAD

**Issue by skitterm** [FezVrasta/popper.js#695]
Does Popper.js have RTL support for `placement` and `offset`? I.e. if a popper was set with `placement="bottom-start"`, so it's placed like this:
```text
+--------+
| target |
+-------------+
|             |
|   popper    |
|             |
+-------------+
```

Would the same popper automatically look like this if displayed on an RTL page?
```text
     +--------+
     | target |
+-------------+
|             |
|   popper    |
|             |
+-------------+
```

**Comment by FezVrasta** [comment]
Not out of the box, but it is extremely trivial to write a [custom modifier](https://github.com/FezVrasta/popper.js#writing-your-own-modifiers) to achieve that.

**Comment by FezVrasta** [comment]
I think this should work

```js
{
  order: 0,
  enable: true,
  fn: data => {
    const hash = { end: 'start', start: 'end' };
    data.placement = placement.replace(/start|end/g, matched => hash[matched]);
	return data;
  }
}
```

**Comment by skitterm** [comment]
Thanks @FezVrasta for the quick help. It would also be awesome if RTL support made it into Popper.js natively. Where RTL is becoming more important, it'd add another feather in your library's cap to have that 😃

**Comment by FezVrasta** [comment]
We may add it into V2, but V1 at the moment is so heavy that any additional feature is out of question 🙁

**Comment by codylawson** [comment]
@FezVrasta Is there any reason your snippet wouldn't work for swapping "left" and "right" placement?

```jsx
rtl: {
  order: 0,
  enabled: true,
  fn: data => {
    if (this.props.rtl) {
      const hash = {
        end: 'start',
        start: 'end',
        left: 'right',
        right: 'left'
      };
      data.placement = data.placement.replace(
        /start|end|right|left/g,
        matched => hash[matched]
      );
    }
    return data;
  }
}
```
Resulting UI when placement is set to "right" but modifier sets to "left" for RTL:
<img width="296" alt="Screen Shot 2019-11-11 at 12 07 18 PM" src="https://user-images.githubusercontent.com/5149922/68613471-0d129980-047c-11ea-8699-86732b9ba367.png">
It appears the `data-placement` attribute is being set to the correct value so the arrow displays as expected, but the `translate3d` isn't accounting for the updated placement and is still shown on the original side of the reference.

It's interesting to note that setting placement to "\*-end" is properly changed to "\*-start" and the popper is displayed as expected.
UI when placement is set to "bottom-end" and modifier changing it to "bottom-start":
<img width="221" alt="Screen Shot 2019-11-11 at 12 26 02 PM" src="https://user-images.githubusercontent.com/5149922/68614587-74314d80-047e-11ea-9c2c-dd1e0ceb3413.png">
