### ISSUE TITLE
Popper height transition jittery in Safari

### ISSUE THREAD

**Issue by atomiks** [FezVrasta/popper.js#699]
### CodePen demo

https://codepen.io/atomiks/pen/dgzrYb

### Steps to reproduce the problem

Open the Codepen and watch on Safari. 

It's perfect on Chrome and Firefox. The idea is when the height of the popper changes (due to transition), on each animation frame the popper's position is updated to position it correctly.

### What is the expected behavior?

No jitters.

I'm pretty sure this is related: #264 

Things I've tried:

- Using `setInterval()` instead of `requestAnimationFrame()` (breaks Chrome)
- Using `.scheduleUpdate()`
- Disabling `gpuAcceleration`

None seem to help.  I'm wondering maybe updating `transform` and `top/left` inherently isn't perfect in Safari for whatever reason, causing jitters.

Maybe it's due to the debounced `update()`?

Note it doesn't happen with `placement: bottom`.

EDIT: I just saw this: https://codepen.io/FezVrasta/pen/ZKMWWg

The `taskDebounce` HOF wrap causes lots of stutters on Chrome for me. Removing it makes it smooth. On Safari, it's still jittery without it. Removing the `requestAnimationFrame` wrap results in no jitters on Safari but there are a couple minor flashes/glitches still. I think Safari does not update the DOM in sync with `requestAnimationFrame` or the next repaint properly, causing this behavior?

**Comment by atomiks** [comment]
Found a solid workaround..

Keep the height of the popper constant (no need for an update loop), and use an inner element with styles `position: absolute; bottom: 0` to position it at the bottom so it stays pinned to the reference. That way, the height transition effect is the same with no glitchiness. Use `top: 0` instead of `bottom: 0` for placement: 'bottom', and so on for left/right placement.

https://codepen.io/atomiks/pen/VEXgqb

**Comment by jozsi** [comment]
I'm also having this issue in an old, WebKit based browser embedded into an application. Spent quite some time trying to find the root of the cause, every attempt led here. With gpuAcceleration the scrollbar of the popper is misplaced (on the left), without gpuAcceleration the scrollbar of the popper is okay, however the content and app-wide scrollbar flashses. Starting to run out of clues.
