### ISSUE TITLE
how to make -start -end modifiers ignore the reference elements width

### ISSUE THREAD

**Issue by icenold** [FezVrasta/popper.js#705]
![image](https://user-images.githubusercontent.com/16298042/48031287-a08cfc80-e18e-11e8-938f-8eca73434991.png)

I've been running back and forth on the documentation for days already and I cant seem to find what needs to be done

both poppers have exact modifers with placement="bottom-end"

Problem: the above popper is shifting to the start instead of end because the reference element was too small

What im looking for: I want the above popper to behave like the popper below(shifts on the right side even if the reference element is small)

**Comment by FezVrasta** [comment]
`-start` and `-end` modifiers align the left or right border to the left or right border of the reference element, the behavior you are experiencing is correct.

I'm not sure how to achieve what you are looking for, it seems something non linear.

**Comment by icenold** [comment]
@FezVrasta so what is the recommended way to do something like bottom-left, botttom-right?

**Comment by icenold** [comment]
also do we have an official reddit/slack channel where we can ask random questions?

**Comment by FezVrasta** [comment]
There's the [Spectrum.chat](https://spectrum.chat/popper-js) channel.

I'm not sure how to achieve what you are looking for I'm sorry, a custom modifier will surely be able to do that but I don't know what to put inside it.
