### ISSUE TITLE
Export Tooltip class in tooltip.js as non-default export as well

### ISSUE THREAD

**Issue by robertjk** [FezVrasta/popper.js#707]
### What is the expected behavior?

I'd like to be able to import all members from `tooltip.js` file in a single `import` statement, like this:

```
import { Delay, Tooltip } from 'tooltip.js`;
```

### What went wrong?

Currently the above code gives me an error `Module '"/home/robert/programming/npc/gui/node_modules/tooltip.js/index"' has no exported member 'Tooltip'`. I have to do 2 separate imports:
```
import Tooltip from 'tooltip.js';
import { Delay } from 'tooltip.js';
```

That happens because `Tooltip` class is the default export of the package, but not exported as named (non-default) export.

### How to fix it?

Export `Tooltip` class as the default export *and also* as a named export. For example:

```
// Export Tooltip as a named export, so that `import { Tooltip } from 'tooltip.js'` works
export class Tooltip {
  ...
}

// Export Tooltip as a default export, so that `import Tooltip from 'tooltip.js'` works.
export default Tooltip;
```

**Comment by FezVrasta** [comment]
Why can't you do this?

```
import Tooltip, { Delay } from 'tooltip.js';
```

**Comment by robertjk** [comment]
Didn't know about this syntax! Then there is no problem.
