### ISSUE TITLE
Title attribute on element overrides the title set in options

### ISSUE THREAD

**Issue by sverrirs** [FezVrasta/popper.js#722]
Currently any title attribute value set on the attached element will override a value that is set in the options.

https://github.com/FezVrasta/popper.js/blob/master/packages/tooltip/src/index.js#L200
https://github.com/FezVrasta/popper.js/blob/master/packages/tooltip/src/index.js#L448

This behaviour is not very intuitive as you would expect explicitly set options to be favoured over those set in the markup (especially if you're using a function to compute the title of the tooltip).

If the existing behavior is as designed, it would be nice to be able to have a way to explicitly say that you want the `options.title` to take precedence over the title attribute to support both scenarios.

**Comment by FezVrasta** [comment]
If I remember correctly this is the same behavior of Bootstrap, that's what we use as reference for the tooltip API

**Comment by sverrirs** [comment]
Yeah, this is what I expected.

The reason why I had a problem with this is that the title attribute on the elements I use actually contain HTML entity characters ( <, > etc) that work just fine in the browser default tool tip but I need to explicitly escape to have them show up correctly in your tool tip control.

So I was just going to use a callback function for the tool tip and escape the chars but then discovered that nothing was ever executed of my programmed behaviour if there was already a title attrib.

**Comment by FezVrasta** [comment]
So do you have stuff such as :

```
<a title=">text<">...</a>
```

? I don't think that's valid syntax

**Comment by sverrirs** [comment]
No, what I have is
`
title="blah &gt;" 
`
But during the transfer from the attribute value the escaped values get converted back into `>` for some reason.

It is really strange and I'll provide a repro for confirmation. :)
