### ISSUE TITLE
Proper way to add space between popper and reference element?

### ISSUE THREAD

**Issue by c0bra** [FezVrasta/popper.js#723]
I asked on spectrum.chat but didn't get a response after a week.

I've done a bunch of searching through issues and haven't found anything, but maybe I'm missing it? I was hoping there would be a simple modifier property like a margin or something.

It seems like it can be done with an offset modifier function that looks at the placement and adds an offset to the correct side. Is that the only way?

**Comment by FezVrasta** [comment]
You can just use some CSS margin, it will work.

**Comment by FezVrasta** [comment]
CSS is the way I use in the examples on popper.js.org, the CSS gets conditionally applied reading the `x-placement` attribute.

I guess you can use `offset` also:

```js
{
  offset: {
    offset: '0, 10px`
  }
}
```

https://popper.js.org/popper-documentation.html#modifiers..offset

**Comment by c0bra** [comment]
Ah, `x-placement` is what I was looking for. Thanks!

And thanks for all the hard work you've put into this library. I really appreciate it!
