### ISSUE TITLE
[Question] Flip to 'bottom-start' instead of "stick" to viewport

### ISSUE THREAD

**Issue by Ashot-KR** [FezVrasta/popper.js#731]
Got popper with placement set to 'bottom-end'. When popper element "touches" left edge of viewport is "sticks" to it, but i want it "flips" to `bottom-start`. Can i implement such behaviour?

What i've got
![image](https://user-images.githubusercontent.com/899218/49790365-11e83e00-fd3f-11e8-86e7-601bfc007116.png)

What i want
![image](https://user-images.githubusercontent.com/899218/49791468-99cf4780-fd41-11e8-8708-a94e4e3878c8.png)

http://jsfiddle.net/0ejkmbqf/1/

Thanks in advance

**Comment by FezVrasta** [comment]
Sorry I don't think I understand the question, may you elaborate?

**Comment by Ashot-KR** [comment]
looks like i'm bad to explain it in english 😬 
So i better show you
![](https://habrastorage.org/webt/w5/rn/wb/w5rnwb72255t8gks8zo8unmg7wg.gif)
I want to implement this behavior

**Comment by FezVrasta** [comment]
I see, I don't think it is supported out of the box at the moment, but you can implement that writing a custom modifier if you want to get your hands dirty.

**Comment by airtable-JayRansijn** [comment]
For those looking, here is the modifier I created for `usePopper`:
```
    // Custom modifier to make tooltips shift to "start" or "bottom", instead of pushing in the tooltip in a little bit.
    const niceAlignmentModifier: PopperJS.Modifier<PopperJS.Options> = React.useMemo(
        () => ({
            name: 'niceAlignment',
            enabled: true,
            phase: 'main',
            fn: ({state}: PopperJS.ModifierArguments<PopperJS.Options>) => {
                if (state.modifiersData.preventOverflow.x > 0) {
                    if (state.placement === 'bottom') {
                        state.placement = 'bottom-start';
                        state.reset = true;
                    } else if (state.placement === 'top') {
                        state.placement = 'top-start';
                        state.reset = true;
                    }
                } else if (state.modifiersData.preventOverflow.x < 0) {
                    if (state.placement === 'bottom') {
                        state.placement = 'bottom-end';
                        state.reset = true;
                    } else if (state.placement === 'top') {
                        state.placement = 'top-end';
                        state.reset = true;
                    }
                }
            },
        }),
        [],
    );
```
