### ISSUE TITLE
Flip modifier `behavior`  doesn't work correctly with `variation`

### ISSUE THREAD

**Issue by wuweiweiwu** [FezVrasta/popper.js#736]
### CodePen demo

https://codepen.io/wuxx1045/pen/roKWJJ

### Steps to reproduce the problem

1.  drag the window so that the popper overflows
2.  observe that the flip to the left doesnt happen
3.  change `bottom-end` to `bottom` (by uncommenting) and see that it now works

### What is the expected behavior?

should flip to the left when overflowing

### What went wrong?

`variation` seems to break flip behavior

another note is that if the original placement isnt the first element of the `behavior` array, flip behavior doesn't work at all

### Any other comments?

related to #696

**Comment by FezVrasta** [comment]
It seems the same problem as #755 to me
