### ISSUE TITLE
Add Popper automatic hiding possibilities

### ISSUE THREAD

**Issue by hltfe** [FezVrasta/popper.js#737]
If the parent of reference is scrollable, it is recommended to add poppver auto-hiding function if reference is not in the scope of screen display. When reference reappears on the screen, the user triggers its display

Think about the following scenarios：
the parent of reference is scrollable  and position is Fixed
the popper's position is Fixed too,  when parent scroll, popper will be overflow

**Comment by FezVrasta** [comment]
I think you are looking for the `hide` modifier that adds an attribute to let you know when to hide the popper.

Anyway, please, next time follow the issue template. Thanks!
