### ISSUE TITLE
Examples on popper.js.org are broken due to a broken link to popper.js

### ISSUE THREAD

**Issue by gillisig** [FezVrasta/popper.js#738]
As the title says, all the examples on popper.js.org are broken because https://unpkg.com/popper.js@1.14.6/index.js is returning a 404

**Comment by FezVrasta** [comment]
I don't see any error, may you post a screenshot of the network tab where the error is reported please?

**Comment by FezVrasta** [comment]
![image](https://user-images.githubusercontent.com/5382443/51337130-9d639600-1a86-11e9-86e3-c4934a815c9d.png)

This is what I see

**Comment by gillisig** [comment]
Here you go:

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/5390864/51337631-88cfcf80-1a7f-11e9-86a9-d212921bb59e.png">

I tried it in every browser and turned off every extension thinking something might be blocking it but I get the same results everywhere. Also tried it on another computer.

**Comment by FezVrasta** [comment]
The thing is that I don't import the js file directly, I leave this to the resolution system of unpkg.com:

https://github.com/FezVrasta/popper.js/blob/fec3de12c87af087e049d4a868ef7b97494e4f0b/docs/_includes/scripts.html#L10

Maybe they are having some problems on their side.

**Comment by gillisig** [comment]
Yeah most likely, when I got to that address in my browser it says ```Cannot find "/index.js" in popper.js@1.14.6```

**Comment by mjackson** [comment]
You probably want to use https://unpkg.com/popper.js@1.14.6/dist/popper.js

unpkg doesn't magically find files in the `dist` directory for you unless you specify them in the `main` field in `package.json`

**Comment by FezVrasta** [comment]
@mjackson the dist bundle is defined in the `main` field:
https://github.com/FezVrasta/popper.js/blob/master/packages/popper/package.json#L27
