### ISSUE TITLE
Popper with perfect-scroll-bar not working as expected

### ISSUE THREAD

**Issue by NetanelBasal** [FezVrasta/popper.js#739]
Hey, thanks for this great library. We're using [perfect-scroll-bar](https://github.com/utatti/perfect-scrollbar) in our application. When we initialized Popper inside it and scrolling, the Popper element doesn't stick to the origin. It seems like the scroll events don't work.

After a little investigating I saw the following method in the source code:

```ts
  // Firefox want us to check `-x` and `-y` variations as well
  const { overflow, overflowX, overflowY } = getStyleComputedProperty(element);
  if (/(auto|scroll|overlay)/.test(overflow + overflowY + overflowX)) {
    return element;
  }

  return getScrollParent(getParentNode(element));
```

And I assume that it's not working because the library sets `overflow: hidden` for the container.

![image](https://user-images.githubusercontent.com/6745730/51473905-59260d80-1d86-11e9-8a7c-7429de8258de.png)

Do you know any workaround that can be used? 

Thanks in advance.

**Comment by NetanelBasal** [comment]
After further investigation, I saw that you're using the following way to set the scrollable parent:

```ts
var scrollElement = getScrollParent(reference);
attachToScrollParents(scrollElement, 'scroll', state.updateBound, state.scrollParents);
state.scrollElement = scrollElement;
```

What do you think about allowing setting the scrollable parent programmatically?

**Comment by FezVrasta** [comment]
You can do that manually:

```
addEventListener('scroll', popperInstance.scheduleUpdate);
```

**Comment by NetanelBasal** [comment]
Thanks, that's what I did.
