### ISSUE TITLE
System.InvalidOperationException: 'popper' is not a valid script name.  The name must end in '.js'.

### ISSUE THREAD

**Issue by GuitarHero1969** [FezVrasta/popper.js#747]
I'm getting the above error page when running my asp.net web forms application (.net 4.7.2)

If the name MUST end in .js, then why don't MsAjaxBundle, jquery and bootstrap script references in Site.Master also end in .js ?

Why is there no less than THREE !! lots of popper.js in the project files, one under Scripts/esm, one under Scripts/umd and a third under Scripts ?

Do I need to reference popper.js in the asp:ScriptManager of Site.Master ?

popper.js is referenced as a package in packages.config

popper.js has also generated 79 errors (ESLint) (although this doesn't stop the application running!

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.

**Comment by GuitarHero1969** [comment]
What do you need ? Code ? Errors ? Exceptions ?

This is in the Site.Master 

` <asp:ScriptManager runat="server">
            <Scripts>
                <%--To learn more about bundling scripts in ScriptManager see https://go.microsoft.com/fwlink/?LinkID=301884 --%>
                <%--Framework Scripts--%>
                <asp:ScriptReference Name="MsAjaxBundle" />
                <asp:ScriptReference Name="jquery" />
                <asp:ScriptReference Name="popper.js" Path="~/Scripts/umd/popper.js"/>
                <asp:ScriptReference Name="bootstrap" />
                <asp:ScriptReference Name="WebForms.js" Assembly="System.Web" Path="~/Scripts/WebForms/WebForms.js" />
                <asp:ScriptReference Name="WebUIValidation.js" Assembly="System.Web" Path="~/Scripts/WebForms/WebUIValidation.js" />
                <asp:ScriptReference Name="MenuStandards.js" Assembly="System.Web" Path="~/Scripts/WebForms/MenuStandards.js" />
                <asp:ScriptReference Name="GridView.js" Assembly="System.Web" Path="~/Scripts/WebForms/GridView.js" />
                <asp:ScriptReference Name="DetailsView.js" Assembly="System.Web" Path="~/Scripts/WebForms/DetailsView.js" />
                <asp:ScriptReference Name="TreeView.js" Assembly="System.Web" Path="~/Scripts/WebForms/TreeView.js" />
                <asp:ScriptReference Name="WebParts.js" Assembly="System.Web" Path="~/Scripts/WebForms/WebParts.js" />
                <asp:ScriptReference Name="Focus.js" Assembly="System.Web" Path="~/Scripts/WebForms/Focus.js" />
                
                <asp:ScriptReference Name="WebFormsBundle" />
                <%--Site Scripts--%>`


This is the page output in Chrome

`

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
--

`
(it would'nt let me copy and paste the entire page content :( )
