### ISSUE TITLE
UMD file does not work with Bootstrap 4 dropdowns

### ISSUE THREAD

**Issue by Crocmagnon** [FezVrasta/popper.js#748]
I'm having this issue in an Angular 7 app. I **was not** able to reproduce it with pure Bootstrap CSS/JS and Popper.js.

### Steps to reproduce the problem

1. Create an angular app with ng-cli
1. Install bootstrap and bootstrap types:
    - `npm install --save bootstrap @types/bootstrap`. 
    - `@types/bootstrap` requires `popper.js` as a dependency.
1.  Include Bootstrap 4 CSS and JS files
2.  Include Popper JS UMD file
3.  Try to use Bootstrap 4 dropdown in navbar

Relevant excerpt from `angular.json` :

```json
"styles": [
  "node_modules/bootstrap/dist/css/bootstrap.min.css",
  "node_modules/@fortawesome/fontawesome-free/css/all.css",
  "src/styles.scss"
],
"scripts": [
  "node_modules/jquery/dist/jquery.slim.js",
  "node_modules/popper.js/dist/esm/popper.js",
  "node_modules/bootstrap/js/dist/util.js",
  "node_modules/bootstrap/js/dist/alert.js",
  "node_modules/bootstrap/js/dist/button.js",
  "node_modules/bootstrap/js/dist/carousel.js",
  "node_modules/bootstrap/js/dist/collapse.js",
  "node_modules/bootstrap/js/dist/dropdown.js",
  "node_modules/bootstrap/js/dist/modal.js",
  "node_modules/bootstrap/js/dist/scrollspy.js",
  "node_modules/bootstrap/js/dist/tab.js",
  "node_modules/bootstrap/js/dist/toast.js",
  "node_modules/bootstrap/js/dist/tooltip.js",
  "node_modules/bootstrap/js/dist/popover.js"
]
``` 

### What is the expected behavior?
The dropdown should toggle

### What went wrong?
The dropdown doesn't toggle at all

### Any other comments?
I tried to include Popper ESM files in my `angular.json` file. Everything now works fine, except that I get an error in the console.

```
Uncaught SyntaxError: Unexpected token export
```

I tried to use a bootstrap tooltip (which requires popper.js as per [Bootstrap's docs](https://getbootstrap.com/docs/4.2/getting-started/introduction/)) and it works without issues regardless of the included file (UMD or ESM)

Do I miss something here ?

**Comment by FezVrasta** [comment]
`node_modules/popper.js/dist/esm/popper.js`, you are using ESM rather than UMD, switch to UMD to get it working

**Comment by Crocmagnon** [comment]
Sorry, the `esm` mention in my first message was a typo. As I mentioned, I tried both UMD and ESM.
- UMD breaks dropdowns
- ESM gives an error in the console but everything works fine

**Comment by FezVrasta** [comment]
the error you reported is because you are using ESM, you haven't provided the error you get with UMD.

**Comment by Crocmagnon** [comment]
When working with UMD, the dropdown doesn't work. That's my unexpected behavior.

**Comment by FezVrasta** [comment]
How am I supposed to help you? 😅

**Comment by Crocmagnon** [comment]
Well I don't understand why everything works fine with ESM except for that console error but when I try to use the UMD build, which everyone recommends, some components break.

**Comment by FezVrasta** [comment]
I don't know I'm sorry 🔮

**Comment by Crocmagnon** [comment]
Where do you suggest I could help with that issue ? It seemed pretty popper.js-related to me so that's why I posted this issue.

**Comment by FezVrasta** [comment]
Maybe on StackOverflow, but the thing is that if you don't provide a reproducible example I doubt anybody will ever be able to help you. We are not in your computer.

**Comment by Crocmagnon** [comment]
Here's a MWE if you want to reproduce : https://github.com/Crocmagnon/angular-bootstrap4-dropdown-issue

I'll try to post on SO

**Comment by Crocmagnon** [comment]
Here's the SO question for reference : https://stackoverflow.com/questions/54407072/bootstrap-4-dropdown-breaks-with-popper-js-umd-build-in-angular-7
