### ISSUE TITLE
Misplaced tooltips on page overflow

### ISSUE THREAD

**Issue by hdodov** [FezVrasta/popper.js#752]
I'm implementing tooltips on a Vue application and basically all third party components use popper. In the design, there are no tooltip arrows and I decided to exclude the styles for them.

Well, it took me about 5 hours and going through all available Vue components to figure out that one very simple CSS rule is causing an overflow issue, coming from popper.js core:

```css
.tooltip-arrow {
  width: 0 !important;
}
```

Without the rule:
![image](https://user-images.githubusercontent.com/5570098/52207043-dd978680-2884-11e9-9f27-9841ec2ac50e.png)

With the rule:
![image](https://user-images.githubusercontent.com/5570098/52207065-ef792980-2884-11e9-84f7-625a4fa2ac4e.png)

If you don't have the rule and you've got very long text, it goes out of the page.

---

Seems pretty confusing that the position of the popper is determined by the position of its arrow. I think it should be the other way around.

The most stupidly wasted hours of my life... Hope that I save someone's time if they bump into this.

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
