### ISSUE TITLE
Can this be done with Popper?

### ISSUE THREAD

**Issue by johnknoop** [FezVrasta/popper.js#756]
I tried using the Spectrum chat, but got "internal server error" when I uploaded images, so I'll try my luck here instead.

Using the default modifiers, the vertical flipping works great, but if it doesn't fit in the viewport horizontally, it doesn't do any alignment at all.

Here's my default placement:

![bottom_start](https://user-images.githubusercontent.com/3394270/53745953-74fdf280-3ea0-11e9-8576-9e73b01f38bf.png)

If it cant fit vertically, it flips as it should:

![top_start](https://user-images.githubusercontent.com/3394270/53745968-7cbd9700-3ea0-11e9-8a6d-a819bc718ef5.png)

However, if it doesn't fit horizontally, it just positions itself somewhere along the x-axis without any alignment:

![top_bad](https://user-images.githubusercontent.com/3394270/53746002-8ba44980-3ea0-11e9-8ee2-d7fa3fb6144a.png)

Instead I would like it to align to the end:

![top_end](https://user-images.githubusercontent.com/3394270/53746018-94951b00-3ea0-11e9-83bd-ef46ba6aa089.png)

Is this achievable?

**Comment by johnknoop** [comment]
Looks like I managed to solve it using a customer shift function:

```js
shift: {
	enabled: true,
	fn: (data: Data, options: Object) => {
		const { offsets } = data;
		const { popper, reference } = offsets;

		// Can it fit if left-aligned?
		if (reference.left + popper.width < window.innerWidth) {

			popper.left = reference.left;

			data.placement = data.flipped
				? 'top-start'
				: 'bottom-start';

		} else {
			// Otherwise, right-align it
			const referenceRight = reference.left + reference.width;
			popper.left = referenceRight - popper.width;

			data.placement = data.flipped
				? 'top-end'
				: 'bottom-end';
		}

		return data;
	}
},
```
Is this the way to do it, or am I mutating the wrong properties or something? (I'm a Popper newbie)

**Comment by FezVrasta** [comment]
Have you tried to use the `flipVariations` option of `flip`?

**Comment by johnknoop** [comment]
> Have you tried to use the `flipVariations` option of `flip`?

Hi @FezVrasta 

No, I wasn't even aware of those. That doesn't seem to be described in the documentation, nor in the TypeScript definitions.

**Comment by atomicbrainman** [comment]
> Have you tried to use the `flipVariations` option of `flip`?

@FezVrasta It's not released yet.
https://github.com/FezVrasta/popper.js/releases
Can you please make fresh releases for `popper.js` and `react-popper`?

**Comment by FezVrasta** [comment]
`flipVariations` is now released

**Comment by johnknoop** [comment]
`flipVariationsByContent` seems to be the one I want. However it doesn't seem to work under all conditions.

These options:
```js
placement: 'bottom-start',
modifiers: {
	flip: {
		enabled: true,
		flipVariationsByContent: true,
		boundariesElement: 'viewport',
		behavior: 'flip'
	},
	shift: {
		enabled: true,
	},
	preventOverflow: {
		boundariesElement: 'viewport',
		padding: Number(this.preventOverflowPadding),
	},
	computeStyle: {
		gpuAcceleration: false
	},
}
```
work for one of my top-menu fly-outs:
![image](https://user-images.githubusercontent.com/3394270/62417036-531ebc80-b646-11e9-88d9-16bdd7196753.png)

...but not the other:
![image](https://user-images.githubusercontent.com/3394270/62417057-de984d80-b646-11e9-82f3-440ffa0e4317.png)
I've highlighted the reference element with a red pencil. The `x-placement` attribute is 'bottom-start', making the arrow appear in the top-left corner, but the placement is obviously bottom-end.

I'll have to stick to my custom shift function until this is fixed.
