### ISSUE TITLE
No popover within swiper

### ISSUE THREAD

**Issue by nanmaniac** [FezVrasta/popper.js#757]
Hello,
I'm using bootstrap ans swiper (https://idangero.us/swiper/get-started/). No popover is working within the swiper. I click on the link and no window is showing up. If I right click on the link, then it shows!!
Can anyone give me a clue how to fix it? Thank you!!

### Steps to reproduce the problem

1.  Go to http://pf2.easytool.es/index.php?id=2745&advancement=0
2.  Click on telepathy (pink link). No popover!!
3.  Right Click on telepathy. Now, yes!!

### What is the expected behavior?

When you click on pink link , a popover window should pop up.

### What went wrong?

No pop up window!

### Any other comments?

If you right click on the pink link, then it pops up!

**Comment by FezVrasta** [comment]
I'm sorry you are facing this issue, but it doesn't seem to be an issue related with Popper.js. You may try to contract the Swiper developers.
