### ISSUE TITLE
Remove arrow modifier requirement in applyStyle modifier

### ISSUE THREAD

**Issue by alexpusch** [FezVrasta/popper.js#76]
In the applyStyle modifier, there is an [explicit dependency](https://github.com/FezVrasta/popper.js/blob/master/src/popper.js#L674) on the arrow modifier

This prevents users from creating their own modifier that work on the arrow attributes

Can this dependency be removed? The only validation needed is that the arrow attributes exists in the received data.

**Comment by FezVrasta** [comment]
Good point, going to fix it and release a patch version ASAP.

**Comment by FezVrasta** [comment]
Waiting for the build to pass and I'll release the v0.6.3 with the fix

**Comment by FezVrasta** [comment]
released  [v0.6.3](https://github.com/FezVrasta/popper.js/releases/tag/v0.6.3) on npm and Bower.

**Comment by FezVrasta** [comment]
merged into `v1-dev`

**Comment by alexpusch** [comment]
Wow you are fast! Thanks! 👍

**Comment by FezVrasta** [comment]
Eheh.

If/when you build something awesome with Popper please post it here or send me an email 🙃
