### ISSUE TITLE
with bootstrap.css seem not run

### ISSUE THREAD

**Issue by mtugnoli** [FezVrasta/popper.js#762]
Simply add     <link href='bootstrap.css' rel='stylesheet' /> on header page,
and popper semm not run

Any Idea ?

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
