### ISSUE TITLE
Seem not run with bootstrap

### ISSUE THREAD

**Issue by mtugnoli** [FezVrasta/popper.js#763]
### CodePen demo
https://codepen.io/mtugnoli/pen/jJpjjB?editors=0010

### Steps to reproduce the problem

1.  I use your https://fullcalendar.io/docs/event-tooltip-demo sample
2.   I insert bootstrap.css 
3.  and than tooltip don't run !
4. If you remove bootstrap.css  reference all run ok

### What is the expected behavior?

I'm asking if popper run also with bootstrap

### What went wrong?

Is popper compatible with bootstrap.css ?

### Any other comments?

no comment

**Comment by FezVrasta** [comment]
Please consider opening an issue on the Bootstrap repository, this same codepen should be helpful to them.
