### ISSUE TITLE
Ship tooltip.js with popper.js bundled

### ISSUE THREAD

**Issue by brettz9** [FezVrasta/popper.js#765]
### CodePen demo

This is a build bug rather than a code bug, so I can't demo it at Codepen.

### Steps to reproduce the problem

1.  Add the line `import Tooltip from './node_modules/tooltip.js/dist/esm/tooltip.js';` into one's code.
2.  See it fail to import the code in console.

### What is the expected behavior?

Per https://github.com/rollup/rollup/wiki/pkg.module#user-content-wait-it-just-means-import-and-export--not-other-future-javascript-features , transpilation is to take place on the file pointed to by `module` so that the code that is shipped can be used in the supporting environment. While this page refers to transpilation rather than compilation, I think the same must apply. If people wanted to be bothered with compilation steps, they could read through your own Rollup files and compile from your source themselves. The `dist` file pointed to by `module` ought to avoid this necessity.

So, I would expect no `import` statement in `tooltip.js/dist/esm/tooltip.js` (or at least a working relative path import like `./popper.js` instead of `popper.js`) and just have popper bundled within the `module`-pointed `dist` file for tooltip.js.

### What went wrong?

The `module` `package.json` of `tooltip.js` points to `./dist/esm/tooltip.js` which has the line `import Popper from 'popper.js';`. This reference to `popper.js` is not a path that can be resolved directly in the browser without compiling.

So importing `/dist/esm/tooltip.js` directly in the browser (i.e., without first compiling it oneself) will not work.

### Any other comments?

No.

**Comment by FezVrasta** [comment]
imports without paths refer to node_modules dependencies. It's the standard way to import them

**Comment by brettz9** [comment]
I'm aware that they refer to `node_modules` dependencies, but it is not a "standard" way to import them as far as the browser; it *is* a common convention for bundlers or bundler plugins to recognize the Node resolution algorithm when building browser bundles, but my point is that you have no tooltips file which can be consumed directly by the browser.

**Comment by FezVrasta** [comment]
You can use UMD and CJS builds. Please refer to the readme file

**Comment by brettz9** [comment]
I know, but I'd really rather not. I like using ESM as a format, thereby avoiding clutter in HTML (and avoiding my application's consumers needing to do so as well, e.g., for `import()`-driven plugins).

**Comment by FezVrasta** [comment]
I understand. But there's not any convention to define how to import dependencies from a native ES module.

If I change the import to be a relative path it would break the usage with module bundlers such as webpack and rollup

**Comment by brettz9** [comment]
But why can't you just let Rollup bundle popper.js into the file? I also wouldn't expect it to break webpack/rollup, both of which seem to have no trouble importing relative paths when I have used them...

**Comment by FezVrasta** [comment]
Because that's not how a modular dependency system works. The modules must be isolated and refer to their dependencies. 

If everything was bundled inside the package you'd be forced to use the specific version I defined, you would have to ship it twice if you are using other modules that depend upon it and I would have to update the module every time I release a new Popper.js version

**Comment by brettz9** [comment]
ES Modules were not designed solely to be used by bundlers which could, as is indeed ideal, strip out redundancies, but to be usable in live code and not force the consumer to be aware of any dependencies--that's one of their big appeals. So, imo, it is better to accommodate consumers who just want things to work even if that ties them to a particular version. Those with complex set-ups requiring the same module multiple times and wishing to take advantage of avoiding redundancies or getting the latest patch upgrade can do their own compilation from source. But, that's just my opinion anyways.
