### ISSUE TITLE
NPM for tooltip.js version 1.3.1 is not up to date

### ISSUE THREAD

**Issue by cooney** [FezVrasta/popper.js#771]
### CodePen demo

https://codepen.io/anon/pen/WgRoZp?editors=1111

### Steps to reproduce the problem

1.  Notice that all 4 tooltips start out with "default title", as they should
2.  Hover over all 4 li elements
3.  Notice that only 1 tooltip has updated to "updated title"

### What is the expected behavior?

All 4 should have updated.

### What went wrong?

This has actually been fixed with #676, but the NPM version has not been updated in 5 months (https://www.npmjs.com/package/tooltip.js/v/1.3.1).  
You can see the outdated code: https://unpkg.com/tooltip.js@1.3.1/dist/umd/tooltip.js `var titleNode = this._tooltipNode.parentNode`

**Comment by JvanderHeide** [comment]
+1 ran in to this after finding out my issue was supposedly fixed in #677

**Comment by FezVrasta** [comment]
Sorry, I forgot to publish Tooltip.js, now you should see a 1.3.2 version on npm

**Comment by cooney** [comment]
@FezVrasta thank you for the quick turnaround, much appreciated!

**Comment by JvanderHeide** [comment]
@FezVrasta thanks heaps!
