### ISSUE TITLE
How to make a transfer bottom, if there is not enough space on top, but there will be scrolling bottom ?

### ISSUE THREAD

**Issue by golubvladimir** [FezVrasta/popper.js#772]
How to make a transfer bottom, if there is not enough space on top, but there will be scrolling bottom ?

     popperPlacement='bottom-end'
     preventOverflow: {enabled: true, priority: ['bottom','left','right','top'], 

The window pops up and has an overlapped area.

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
