### ISSUE TITLE
Library minification and bundling fails

### ISSUE THREAD

**Issue by pavlexander** [FezVrasta/popper.js#774]
### CodePen demo

n/a (errors during minification&bundling)

### Steps to reproduce the problem

1. Create new MVC .Net Core 2.1 solution in Visual Studio 2017 (15.9.7).
2. Download `popper.js@1.15.0` library and put into "wwwroot/lib/popper.js/popper.js"
3. Install Nuget package: BuildBundlerMinifier
4. In project root create: `bundleconfig.json`
```json
[
  {
    "outputFileName": "wwwroot/js/vendor.min.js",
    "inputFiles": [
      "wwwroot/lib/popper.js/popper.js"
    ],
    "minify": {
      "enabled": true
    }
  }
]
```
5. Try to build solution.

### What is the expected behavior?

Solution is built. Library is minified into `vendor.min.js`

### What went wrong?

Exceptions during minification:

```js
Implicit property name must be identifier: primary(placement) {
  let value = popper[placement];
  if (popper[placement] < boundaries[placement] && !options.escapeWithReference) {
	value = Math.max(popper[placement], boundaries[placement]);
  }
  return { [placement]: value };
}

Implicit property name must be identifier: secondary(placement) {
  const mainSide = placement === 'right' ? 'left' : 'top';
  let value = popper[mainSide];
  if (popper[placement] > boundaries[placement] && !options.escapeWithReference) {
	value = Math.min(popper[mainSide], boundaries[placement] - (placement === 'right' ? popper.width : popper.height));
  }
  return { [mainSide]: value };
}

Strict-mode does not allow duplicate property names: secondary(placement) {
  const mainSide = placement === 'right' ? 'left' : 'top';
  let value = popper[mainSide];
  if (popper[placement] > boundaries[placement] && !options.escapeWithReference) {
	value = Math.min(popper[mainSide], boundaries[placement] - (placement === 'right' ? popper.width : popper.height));
  }
  return { [mainSide]: value };
}
```
i.e. errors:
* Implicit property name must be identifier: primary(placement) {
* Implicit property name must be identifier: secondary(placement) {
* Strict-mode does not allow duplicate property names: secondary(placement) {

### Any other comments?

I don't know exactly, if this is some issue with the library itself, or a tool that does the minifaction. I would assume that there is something wrong with the `javascript` code, therefore minification fails. The minification process works flawlessly for other libraries such as jquery, bootstrap, plotly, etc... But for this - fails. Please look into this problem.

**Comment by FezVrasta** [comment]
Please make sure you are targeting the `umd` build, your minifier may not support ES6 features.
