### ISSUE TITLE
Below-start and below-end placements bugged

### ISSUE THREAD

**Issue by ehtonay** [FezVrasta/popper.js#775]
Using react-popper, the placement options "below-end" and "below-start" do not work correctly:

**Below** (Working correctly)
![Screen Shot 2019-04-15 at 1 18 53 PM](https://user-images.githubusercontent.com/33971189/56149263-87307d80-5f82-11e9-9f08-f57ea3a7123b.png)

**Below-end**
![Screen Shot 2019-04-15 at 1 19 38 PM](https://user-images.githubusercontent.com/33971189/56149297-98798a00-5f82-11e9-92dc-ee41f2d56c25.png)

**Below-start**
![Screen Shot 2019-04-15 at 1 19 18 PM](https://user-images.githubusercontent.com/33971189/56149289-91eb1280-5f82-11e9-8d61-eed6501718fc.png)

**Comment by ehtonay** [comment]
I looked at the resulting **transform: translate3d()** values, and hope these findings help:

**Below**
translate3d(-199px, 28px, 0px) _(correct)_

**Below-start: resulting CSS**
translate3d(-199px, 0px, 0px) _(incorrect)_

_It should be:_
translate3d(0, 28px, 0px)

**Below-end: resulting CSS**
translate3d(-199px, -264px, 0px)  _(incorrect)_

_It should be:_
translate3d(-398px, 28px, 0)

**Comment by FezVrasta** [comment]
I have no idea what `below` is, the placement is called `bottom`.

**Comment by ehtonay** [comment]
We may have aliased them differently, but the problem persists. I'd appreciate you not closing the issue prematurely.

**Comment by FezVrasta** [comment]
You haven't followed the issue template. I can't help you without that.
