### ISSUE TITLE
https://unpkg.com/popper.js is redirecting to https://unpkg.com/popper.js@1.15.0/dist/umd/popper.min.js

### ISSUE THREAD

**Issue by jensenbox** [FezVrasta/popper.js#778]
This is more or less a DevOps style issue.

The README.md is perfect the way it is but if you click the link it will take you to the minified version when you click the un-minified version.

You can manually take off the `min` and get the file you want, however.

In actuality, there are 2 redirects:

The first location: /popper.js@1.15.0
and then the second: location: /popper.js@1.15.0/dist/umd/popper.min.js

These appear to be on the Cloudflare side of things.

**Comment by atomiks** [comment]
Most people using a CDN just link to the minified version without changing it, so it's short and clean to write. To get the latest, minified v1 version:

```html
<script src="https://unpkg.com/popper.js@1"></script>
```

Is there a reason to use the unminified version when sourcemaps are available? Also there were also 2 redirects before the `"unpkg"` field was added linking to `.min` in 1.15.0:

> The first location: /popper.js@1.15.0
> and then the second: location: /popper.js@1.15.0/dist/umd/popper.js

**Comment by FezVrasta** [comment]
I updated the docs to reflect that
