### ISSUE TITLE
Blurry text on browser zoom

### ISSUE THREAD

**Issue by kaiserkiwi** [FezVrasta/popper.js#779]
Hi,
I just noticed that the text on any tooltip gets blurry if I use the integrated zoom in any browser. I first thought it was some mistake on my end, but even on your demo page you can see this problem on all tooltips. (See screenshot, Browserzoom 90%)

![image](https://user-images.githubusercontent.com/8428551/56570776-d77b9100-65bb-11e9-8461-37ddb9368c28.png)

I figured out that the reason is the positioning of the tooltips. If you use transform to position an element in CSS most browsers have problems to position them correctly if you zoom in or out. If you would switch to the standard position properties (top, left, right bottom) this would fix the problem.

**Comment by FezVrasta** [comment]
If this is a problem for you the `gpuAcceleration` option can be set to `false` to avoid the issue
