### ISSUE TITLE
Improve detection strategy of flip modifier

### ISSUE THREAD

**Issue by FezVrasta** [FezVrasta/popper.js#78]
> @nadiam84 commented:
> @FezVrasta Popper behaves a bit weird inside a scrollable container (alfa-version).
> 
> https://codepen.io/nadiam84/pen/grywdy
> 
> When it's scrolled vertically, it waits when the parent will be completely hidden, and only than start to move itself. When it's scrolled horizontally, it doesn't go away at all.
>
>  ![d58dee92-69e2-11e6-8ca2-a28c14fae970](https://cloud.githubusercontent.com/assets/5382443/17923861/6d6becfc-69e6-11e6-8427-240f34d3060a.gif)

> 
> Is there a way to make it permanently attached to its refElement? Isn't 'keepTogether' options suppose to do this?

------

So, nothing new so far, seems like this behavior is not supported.

https://codepen.io/FezVrasta/pen/pbXozA

We use `preventOverflow` modifier to keep the popper inside the boundaries.
`flip` modifier flips the popper when it detects that it's overlapping its reference element.

We should probably change `flip` to use a different detecting strategy (aka, check the boundaries overflow like `preventOverflow` does, but flip the popper instead of move its offsets to stay within the boundaries.)
We should then apply the `flip` modifier **before** the `preventOverflow` modifier.

I hope it makes sense. I'm quite busy in these days so I don't know when I'll be able to work on it. The good thing is that whoever wants to work on this can just edit the `flip` modifier copying how `preventOverflow` works without having to fiddle with the rest of the code.

**Comment by nadiam84** [comment]
Created a PR for this, @FezVrasta could you please take a look?
Tests locally are all green.
