### ISSUE TITLE
 a is not a constructor at g.value

### ISSUE THREAD

**Issue by Balduin94** [FezVrasta/popper.js#780]
Hello,
I have an issue using tooltip and popper js in a flask web page.
I use : python for backend, jinja2, html, js
this is my import:
```
<script src="https://unpkg.com/popper.js/dist/umd/popper.min.js"></script>
<script src="https://unpkg.com/tooltip.js/dist/umd/tooltip.min.js"></script>
```

```
 eventRender: function(info) {
                 var tooltip = new Tooltip(info.el, {
                        title: "info.event.extendedProps.description",
                        placement: 'top',
                        trigger: 'hover',
                        container: 'body'
                      });
            },
```

its suppose to be a very basic function but i got a wierd bug:

the tooltip elem is created in the html when hovering on it but i got this error:

```
Uncaught TypeError: a is not a constructor
    at g.value (index.js:246)
    at index.js:381

```
referencing 

```
    this.popperInstance = new Popper(
      reference,
      tooltipNode,
      this._popperOptions
    );
```

if someone as an idea

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.

**Comment by NicolasPerl** [comment]
I was experiencing this same issue. Make sure both scripts are fully loaded before trying to create a new popper instance.

Hope this helps!
