### ISSUE TITLE
Wrong position at popper js at 1300 720 screen

### ISSUE THREAD

**Issue by salemalem** [FezVrasta/popper.js#782]
Wrong position.
https://i.imgur.com/qaN0WYc.png
![image](https://user-images.githubusercontent.com/42411937/56861145-13e62d00-69c0-11e9-85eb-7426bf32140b.png)

But when I zoom out my screen it's OK. 
Despite of this I think It will be fixed.
![image](https://user-images.githubusercontent.com/42411937/56861092-98847b80-69bf-11e9-86d3-d18777f8a298.png)
https://i.imgur.com/Vx3ue3y.png

**Comment by FezVrasta** [comment]
That's because the examples have the flip modifier enabled. If there's not enough space on a side that go on the opposite
