### ISSUE TITLE
HTML form inside popper?

### ISSUE THREAD

**Issue by hartey11** [FezVrasta/popper.js#788]
Hi,
Is it possible to include a form inside a popper? I've included a CodePen with the HTML and js that I'm using. The popper shows but it's empty.

### CodePen demo
https://codepen.io/hartey11/pen/byYaxP

### Steps to reproduce the problem
1.  Use do_shortcode() to add a form to a popper data attribute
2.  popper is empty

### What is the expected behaviour?
To see the form within the popper

### Any other comments?
Using WordPress plugin search filter pro to generate the form

**Comment by FezVrasta** [comment]
Hi, it seems like you are using Bootstrap, not Tooltip.js, you should ask on the Bootstrap issue tracker.
