### ISSUE TITLE
removeOnDestroy not working in IE11

### ISSUE THREAD

**Issue by fatbrain** [FezVrasta/popper.js#79]
### CodePen demo

http://codepen.io/anon/pen/jAjamG

### Steps to reproduce the problem

1.  Open in IE11, look in console

### What is the expected behavior?

Popper DOM element is removed.

### What went wrong?

Error in console, Popper DOM element is NOT removed.

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/popper.js#internet-explorer
