### ISSUE TITLE
Tooltips incorrectly placed on divs with `overflow: auto`

### ISSUE THREAD

**Issue by bitonic** [FezVrasta/popper.js#798]
### CodePen demo

I used JSfiddle to narrow this down from my website: https://jsfiddle.net/2hcn1t8x/1/ . Here is a video: https://mazzo.li/dump/popperjs-tooltip-edge.mp4 .

You can also see this live at https://benaco.com/view/a354cd2d-9e3b-41c2-a09d-8099f2a548db (hover on the toolbox on the right). I will deploy a fix soon though. _Edit_: I've now deployed a workaround to the website, please see the jsfiddle.

### Steps to reproduce the problem

Put a tooltip with left placement on an element in a div with `overflow: auto`.

### What is the expected behavior?

The tooltip is placed to the left of the element.

### What went wrong?

The tooltip is placed to the right of the element.

### Any other comments?

This is done through bootstrap, but I believe the issue lies in popper. I used bootstrap for the repro for simplicity.

**Comment by bitonic** [comment]
Actually I just noticed that on the JSfiddle it fails on Firefox and Chrome too. On the website it only fails on Edge because the `overflow: auto` is only applied to Edge, for unrelated reasons.

**Comment by qurben** [comment]
Example using only Popper: https://codepen.io/anon/pen/rXBpQo

**Comment by empty-space** [comment]
**Possible solution:**
Setup `preventOverflow` option for your needs. 
This worked for me: 
```
{  
    placement: "top",
    modifiers: {  
        preventOverflow: {  
            enabled: true,
            boundariesElement: "viewport"
        }
    }
}
```

**Comment by imageslr** [comment]
@empty-space  Thank you! That solved my problem!

**Comment by FezVrasta** [comment]
The `overflow: auto` container creates a new boundary for the tooltip, and since it has the same size of the button you experience this issue.

See @empty-space's code for a possible solution.
