### ISSUE TITLE
Hover | Animations of Poppers

### ISSUE THREAD

**Issue by eek** [FezVrasta/popper.js#8]
Got 3 questions: 

- [ ] Is any way to actually show them only on hover?
- [ ] Is there a way to add animations when adding a popper (for example I need to trigger a popper on a error so that the user knows what he inputed was bad)
- [x] Any examples with how a popper can be deleted? :)

**Comment by FezVrasta** [comment]
Hi, managing the in/out effects is not the scope of this project. But nothing prevents you from writing a modifier to add such behaviors.

There's not currently a way to delete the DOM element, you can just destory the instance, removing event listeners and so on. I think this should be added to the `destroy` method tho.

**Comment by dodas** [comment]
Perhaps point 3. can now be archieved with `removeOnDestroy: true` ?

**Comment by FezVrasta** [comment]
Yes it does exactly that.

**Comment by FezVrasta** [comment]
Closing because, as explained, this kind of behavior is not Popper.js' job, some 3rd party library could use Popper.js to position the tooltips, and add support for all these kind of behaviors.
