### ISSUE TITLE
why popper element must be in the DOM before creating the popper

### ISSUE THREAD

**Issue by taburetkin** [FezVrasta/popper.js#807]
### CodePen demo

https://codepen.io/dimatabu/pen/PMqZyo

### Steps to reproduce the problem

1.  create popper element with javascript
2.  DON'T append it to the dom
3.  create the popper

### What is the expected behavior?

I expect that popper place the popper element to the right place in the dom whether or not it is already in the tree.

### What went wrong?

popper element don't added to the dom

**Comment by jorenbroekema** [comment]
In order for Popper to be able to position the popper element properly relative to the reference elements, both elements must exist and have a bounding box. The bounding boxes are necessary for calculating the position.

A work-around for your issue could be to do this:
```
const popper = new Popper(......);

// Once elements are appended to DOM and rendered (ready), update popper
popper.update();
```

**Comment by taburetkin** [comment]
Ok. i can take it.
