### ISSUE TITLE
Cannot get the simplest example to work (problem with documentation?)

### ISSUE THREAD

**Issue by David263** [FezVrasta/popper.js#809]
### CodePen demo

https://codepen.io/pen?template=wGqJEz

### Steps to reproduce the problem

1.  Please visit https://codepen.io/david263/pen/MNbQjR
2. 
3.  

### What is the expected behavior?

The output doesn't look like the first example on page https://popper.js.org/index.html .

### What went wrong?
The output doesn't look like the first example on page https://popper.js.org/index.html .

### Any other comments?

I've looked at the website and the documentation page and cannot find a way to put text into a tooltip. **This needs to be documented clearly.**

**Comment by FezVrasta** [comment]
Please read the README
