### ISSUE TITLE
React Event system do not allow to listen to scroll events

### ISSUE THREAD

**Issue by andresgutgon** [FezVrasta/popper.js#81]
### CodePen demo
Not a code pen. Is just a question.

### Steps to reproduce the problem
Use popper.js inside a React component as described here https://gist.github.com/FezVrasta/6533adf4358a6927b48f7478706a5f23

### What is the expected behavior?
Popper `onUpdate` callback to be called.

### What went wrong?
`scroll` event is captured by Event system and never arrives to Popper.js `eventListener` so no `onUpdate` callback there

### Any other comments?
In React documentation describe a posible work around. Not sure if Popper.js can do something to solve it. Letting here:
https://facebook.github.io/react/tips/dom-event-listeners.html

**Comment by FezVrasta** [comment]
We don't listen for `scroll` in React, we use the native event. What's the problem? I use Popper with React daily and it works just fine.

**Comment by andresgutgon** [comment]
How do you use it? Do you have a poppers on window or inside divs with scroll?

In the second case how?

**Comment by FezVrasta** [comment]
I use an approach similar to the one of the gist you provided, I know several people that use it with React successfully.

**Comment by andresgutgon** [comment]
ok but popper is doing the `scroll` listening for you? or are you doing it on your react component?

I'm doing this:
``` javascript
componentDidMount() {
    document.addEventListener('scroll', this.onReferenceParentScroll, true);
}

onReferenceParentScroll(event) {
  const parentReferenceWithScroll = this.getParentRefenceWithScroll();

  if (event.target !== parentReferenceWithScroll) return;
  
  this.popper && this.popper.update();
}
```

Listening directly to `document` is the only way I found of bypassing React Event System.

Again they suggest this method: https://facebook.github.io/react/tips/dom-event-listeners.html

**Comment by FezVrasta** [comment]
Why are you listening to scroll manually? Popper already sets all its needed event listeners automatically.

**Comment by andresgutgon** [comment]
> You should listen to popper.onUpdate to update React when needed.

I know :/ That's the issue. The callback is not arriving. Anyway thanks for your help and the lib 😃

**Comment by FezVrasta** [comment]
Remember that the `onUpdate` callback doesn't get called when the Popper is instantiated. You have to listen for `onCreate` or manually trigger an `update` (I usually do `window.setTimeou(() => instance.update())`)

On v1 this stuff will be easier to work on

**Comment by andresgutgon** [comment]
Yep, I'm doing `instance.update()` after create the instance. 

The problem is after that we scroll on the DIV that has scroll and contains my `reference`

**Comment by andresgutgon** [comment]
For more reference this is what I'm talking about https://medium.com/@ericclemmons/react-event-preventdefault-78c28c950e46#.mm9lk76ju

**Comment by FezVrasta** [comment]
This has nothing to do with the ability of Popper to detect the scrolling I think.

Maybe ask on StackOverflow, I'm sure someone will know how to help you
