### ISSUE TITLE
Don't async tooltips

### ISSUE THREAD

**Issue by mcandre** [FezVrasta/popper.js#815]
Please offer a way to hide and show tooltips synchronously, so that more complex pages, such as tooltips on modal toggle buttons, fully disappear. Right now, popper tooltips continue to display on top of raised modals for several seconds.

**Comment by Johann-S** [comment]
Hi @mcandre you just have to pass `animation` at false on Bootstrap's tooltip see: https://getbootstrap.com/docs/4.3/components/tooltips/#options
