### ISSUE TITLE
Grunt uglify cannot process popper.js anymore because of const use

### ISSUE THREAD

**Issue by KnottA** [FezVrasta/popper.js#816]
My packing script doesn't work with popper.js anymore with version v1.15.0 ..
My uglify setup in gruntfile.js:
`    uglify: {
      options: {
        banner: "<%= meta.banner %>",
        manage: false,
        //preserveComments: 'all' //preserve all comments on JS files
      },
      main: {
        files: [
          {
            expand: true,
            cwd: DIST_DIR + '/',
            src: ['**/*.js', '!*.min.js', '!**/'+ BOOTSTRAP_FOLDER +'/**'],
            dest: DIST_DIR + '/'
          }
        ]
      }
    },`

I get these errors:

  message: 'Unexpected token: keyword (const)',
  filename: 'popper.js',
  line: 27,
  col: 0,
  pos: 1371 }
>> Uglifying source public_html/dist/js/popper.js failed.
Warning: Uglification failed.
Unexpected token: keyword (const).
Line 27 in public_html/dist/js/popper.js

**Comment by FezVrasta** [comment]
You are using the wrong dist target, you most likely want to use `dist/umd` or `dist/cjs` depending by your setup.
