### ISSUE TITLE
Error: TOOLTIP: Option "template" provided type "object" but expected type "string".

### ISSUE THREAD

**Issue by NishealJ** [FezVrasta/popper.js#817]
Hello,

I'm getting this error :

`Error: TOOLTIP: Option "template" provided type "object" but expected type "string".`

while I tried migrating this library https://github.com/abhikmitra/ng-joyride to bootstrap4.

**Comment by NishealJ** [comment]
<img width="1155" alt="Screenshot 2019-08-11 at 11 49 19 AM" src="https://user-images.githubusercontent.com/41017303/62830531-19dde200-bc2e-11e9-8dd1-852d98fa7c8c.png">
@AndreaScn @FezVrasta  PTAL Thanks!

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
