### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by melanie-wilson** [FezVrasta/popper.js#818]
### CodePen demo

https://codepen.io/pen?template=wGqJEz

### Steps to reproduce the problem

1.  Go to README.md
2.  Look for <img src="http://img.badgesize.io/https://unpkg.com/popper.js/dist/popper.min.js?compression=gzip" alt="Stable Release Size"/>
http://img.badgesize.io/https://unpkg.com/popper.js/dist/popper.min.js?compression=gzip
3.  'http' needs to be 'https'

### What is the expected behavior?

'http' needs to be 'https'

### What went wrong?

The current version of README.md creates a mixed content warning.

### Any other comments?

nope

**Comment by FezVrasta** [comment]
Fixed, thanks!
