### ISSUE TITLE
CUSTOM FLIP BEHAVIOR with drag functionality does not work as documented  

### ISSUE THREAD

**Issue by nishantgiri** [FezVrasta/popper.js#821]
### CodePen demo

https://codepen.io/girinishant/pen/abomZLo?#anon-signup

### Steps to reproduce the problem

1.  try to drag the the 'drag me' text as per documentation 'https://popper.js.org/index.html#example10'-->CUSTOM FLIP BEHAVIOR
2.  it does not work as explained in the documentation.
3.  unable to drag the 'drag me' text 

### What is the expected behaviour?

1. Ideally I should able to drag the 'drag me' text and popper should adjust itself based on the availability of space but unfortunately it is not happening.
### What went wrong?

1. Unable to drag the popover or 'drag me' text.

### Any other comments?
Please suggest is it WIP functionality or I am making any blunder here.

**Comment by FezVrasta** [comment]
I see there's an error in your code, `interact` is not defined.

Note that the drag-n-drop behavior is not provided by Popper.js, it's just used for demo purposes.
