### ISSUE TITLE
How do I include Tooltip class?

### ISSUE THREAD

**Issue by onassar** [FezVrasta/popper.js#822]
I know I'm gonna get yelled at, but that's partially why I'm asking the question:
Why isn't the `Tooltip` class included in the `/dist` directory?

Seems like an oversight to not have it there, and force developers to download it from the CDN.

**Comment by FezVrasta** [comment]
On git you find source code. Not build artifacts.

Handling build artifacts on git is difficult and time consuming.

You should use a package manager such as npm to handle your dependencies.

Cheers

**Comment by FezVrasta** [comment]
I keep Popper.js build artifacts on github because of historical reasons (Bower) but I can't keep both projects builds on the same repository because Bower doesn't support it.

The plan is to get rid of Bower eventually once we reach the v2 release
