### ISSUE TITLE
Popper.js is not working with XHTML pages

### ISSUE THREAD

**Issue by semyonc** [FezVrasta/popper.js#824]
The function attachToScrollParents() in the module packages\popper\src\utils\setupEventListeners.js is throws "Uncaught RangeError: Maximum call stack size exceeded" in a case of loading XHTML files in Chrome.

It's happening because in the case of XHTML the property nodeName preserve lowercase
body tag name. So the condition scrollParent.nodeName === 'BODY' is never reached.

Please change code to condition scrollParent.nodeName === 'BODY' || scrollParent.nodeName === 'body' for this case.

**Comment by FezVrasta** [comment]
There's already an issue tracking this. I'm not able to link you to it but a quick search will get you there.
