### ISSUE TITLE
Basic viewport flipping (bottom to top) not working

### ISSUE THREAD

**Issue by robrez** [FezVrasta/popper.js#828]
### CodePen demo

https://codepen.io/robrez/pen/GRKGOGV

### Steps to reproduce the problem

_note: Everything works correctly in the codepen, however when serving that exact html file locally things do not work (as outlined below)_

1.  import popper
2.  create instance w/ `placement: bottom`
3.  use scrolling to test viewport boundaries

### What is the expected behavior?

Popper w/ placement `bottom` should flip to `top` whenever viewport boundary is encountered

### What went wrong?

Popper doesn't flip from bottom to top. Oddly, flipping works from `top` to `bottom`.  I'm pretty sure right->left, left->right work as well.

### Any other comments?

As indicated in the note above, this has been a confusing issue because it works in "js snippet" environments like codepen or jsfiddle.

I have taken the exact code from the codepen above and tested it on two PCs and four browsers. _with mixed results_:

browser  |  UMD works?   |  ESM works?
------------|---------------|----------------------------
chrome v 77.0.3865.75 (Official Build) (64-bit) |  no | no
firefox v 69.0 (64-bit) | no | no
edge v 42.17134.1.0 | _yes_ | _yes_
ie v 11.9570.17134.0  | _yes_ | n/a

**Comment by FezVrasta** [comment]
I'm sorry but I'm not sure how to reproduce your issue if it's happening only on your machine. Consider to publish a repository on GitHub I can clone and run locally to see the issue.
