### ISSUE TITLE
Make popper flow in the opposite direction

### ISSUE THREAD

**Issue by s-panferov** [FezVrasta/popper.js#83]
Hi, thanks for the amazing lib. 

I'm wondering if `popper.js` allows to do things like this: http://www.material-ui.com/#/components/select-field

To make selects like this you need to be able to say something like "I want my popper to be attached with it's top border to the parent's top border"

Another question if it's able to express center positioning: "always align popper at the center of the target element"

**Comment by FezVrasta** [comment]
Hey! Thanks for the question. This is literally something I never thought about.

I don't think there's an easy/clean way to do so but it's definitely something I want to add.

**Comment by FezVrasta** [comment]
Oh well, thinking about it, you could use the `translateY` property set to 100℅ to make it flip in the direction you want.

By the way I'll add a built in way soon

**Comment by FezVrasta** [comment]
The approach I'd like to follow is to add an `inset` option that will make the popper flow in the opposite direction (towards the inner of the reference element).

I think it's easy to use and understand and provides the needed feature.

**Comment by FezVrasta** [comment]
@s-panferov sorry for the time it took, but finally we have this feature 😬

If you are still interested in it, I would love to hear feedbacks from you.
