### ISSUE TITLE
Prevent popup to be placed ABOVE reference

### ISSUE THREAD

**Issue by Tucsky** [FezVrasta/popper.js#831]
### CodePen demo

https://jsfiddle.net/9xgmqnfb/

### Steps to reproduce the problem

1.  Setup the simplest popper ever (no options needed)
2.  Resize the window so the popup can't fit below / above popup
3.  Popup is above reference

### What is the expected behavior?

Since I setup a page with lot of vertical scrolling, and since viewport couldn't contain the full reference and popup i expected to see the popup below reference even if it would require some scrolling to see it fully

Here is what Im trying to achieve
![image](https://user-images.githubusercontent.com/5738336/65720133-9d04ab80-e0a7-11e9-84d7-eb4d38c4befc.png)

### Any other comments?

How do i specify popper.js to NOT place the popup above the reference, in any situations?

**Comment by FezVrasta** [comment]
You can define a custom flip behavior and omit the   "top" placement from the list. You can find docs about it in the website.

**Comment by Tucsky** [comment]
@FezVrasta Thanks, but what if I need the popup to be placed **above** when there is enough space ? and force it to be **below** when not enough space above (and scroll is enough to make it fit in the body height)

**Comment by FezVrasta** [comment]
I guess you want to change [this option](https://popper.js.org/popper-documentation.html#modifiers..preventOverflow.boundariesElement), try them all and see if one works for you.

**Comment by atomiks** [comment]
@Tucsky isn't that #550? Saw another issue that seemed to be that one as well a couple days ago 🤔 

You only want to use the "flipped" placement if it has enough space, otherwise use the default placement (even if it doesn't either)?

**Comment by Tucsky** [comment]
@atomiks Thanks man its doing exactly what I wanted!! 👍 
Sorry about the duplicate...
