### ISSUE TITLE
TooltipJS - Hidden tooltip takes up space in layout

### ISSUE THREAD

**Issue by ssylvia** [FezVrasta/popper.js#836]
### Description

The tooltip hide/show methods only toggles the visibility of the tooltip by toggling the `_tooltipNode` visibility style to `hidden` or `visible`: https://github.com/FezVrasta/popper.js/blob/master/packages/tooltip/src/index.js#L266. However, because the tooltip node is not actually removed from the DOM, it still takes up space in the layout and can cause unintended consequences: https://developer.mozilla.org/en-US/docs/Web/CSS/visibility.

We have an application that uses drawer menu component that includes tooltips within it. When the drawer is pushed off screen, the tooltip elements are still positioned over the drawer and cause horizontal scrollbars to appear in the app.

### What is the expected behavior?

Hidden tooltips should be hidden and removed from the layout.

### What went wrong?

When the drawer is pushed off screen, the tooltip elements are still positioned over the drawer and cause horizontal scrollbars to appear in our app.

**Comment by FezVrasta** [comment]
Take a look at Tippy.js for a more complete tooltip library, Tooltip.js is simple on purpose, removing and adding DOM nodes would add a lot of complexities.
