### ISSUE TITLE
What's the yellow flicker when opening a dropdown or popover?

### ISSUE THREAD

**Issue by Korthoutrody** [FezVrasta/popper.js#838]
It also happens on the documentation website. https://getbootstrap.com/docs/4.1/components/popovers/ - When clicking the popover, the header of the popover has a minisecond of a yellow colored background flicker. Can't find anything on Google.

**Comment by FezVrasta** [comment]
Hi, I don't see any yellow flicker. Also, this is the Popper.js repository, not the Bootstrap one. You are in the wrong place.
