### ISSUE TITLE
move attributes creation to `applyStyle` modifier

### ISSUE THREAD

**Issue by FezVrasta** [FezVrasta/popper.js#93]
Right now the data attributes are added directly by the modifiers. I'd like to move them to `applyStyle` (and  maybe rename it to `updateDOM` for clarity).

In this way all the DOM write operations will be in a single modifier that can be replaced with an implementation with React or any other view library.

**Comment by lukebatchelor** [comment]
I'll try to pick this up too if you like. Not sure if we can move the actual DOM manipulations to one place, stuff like the `x-out-of-boundaries` would need to stay in hide.js right? We could do something similar to what we did for #105 though, checking if the `applyStyles` modifier is enabled (we'd need to find a way to pass that into the hide.js).

Alternatively, we could make a util function (probably not exposed) called `setAttributeIfApplyStylesEnabled` (or a not terrible name) and we could pass the attributes and the options to that. 

Probably over-engineered, up to you.

**Comment by FezVrasta** [comment]
i would prefer a kind of "virtual DOM" like approach, the modifier adds the attribute to an "attributes" array in the data and applyStyle reads and applies them. we did the same for the custom styles

**Comment by FezVrasta** [comment]
To make it clear what I'm reffering to:
https://github.com/FezVrasta/popper.js/blob/v1-dev/src/popper/modifiers/applyStyle.js#L37-L43
