### ISSUE TITLE
Ready for 1.0.0?

### ISSUE THREAD

**Issue by joscha** [FezVrasta/popper.js#98]
Are we ready to make that `1.0.0-alpha.3` a final? It's been out quite a while and seems fairly stable, no?

**Comment by FezVrasta** [comment]
Hi, sorry but we have still some issues that prevent us to release the first RC... I have no time to work on these issues at the moment and I hope to find some in the next weeks. Any contributions to close the remaining issues assigned to the Project "v1" are more than welcome tho.

**Comment by FezVrasta** [comment]
Especially, this issue is the ones that is blocking a lot of PRs:
https://github.com/FezVrasta/popper.js/pull/92
