### ISSUE TITLE
Using 'hide' modifier not working on 1.0.0-alpha.3

### ISSUE THREAD

**Issue by burnmail123** [FezVrasta/popper.js#99]
When I tried to use 'hide' modifier on my popper it throws error:
`TypeError: Cannot create property 'name' on string 'hide'(…)`

and it points on the line 1419 containing  `modifier.name = name;`

Code with my popper config looks like this:

```
        poppy = new Popper(container[0],document.querySelector('.textc'),{
            placement: 'bottom',
            boundariesElement: $('#grid')[0],
            modifiers:['hide']
        })
```

Problem occurs when trying to open popper.

**Solution** for this problem would be changing line 1417 from 
`if (DEFAULTS.modifiers[name] === undefined) {`
to
`if (DEFAULTS.modifiers[options.modifiers[name]] === undefined) {`

After making this modification, the code behaves as expected.

**Comment by FezVrasta** [comment]
Hi, thanks for your feedback and sorry for the late reply.

May you provide a codepen example of the problem so that I can easily reproduce it?

Thank you

**Comment by FezVrasta** [comment]
This should be fixed thanks to the recent commits. There's not yet an alpha release to test it via npm but you may want to test downloading the source files and running `grunt dist`.

I'm closing it, feel free to reply if something is still wrong.

**Comment by burnmail123** [comment]
Thank you, I appreciate your support. I would provide some example, but deadlines are near and my project is now in different stage.
